# $Id: Makefile.kmk 115056 2026-08-17 16:44:52Z andreas.loeffler@oracle.com $
## @file
# Sub-Makefile for the Shared Clipboard Host Service testcase.
#

#
# Copyright (C) 2011-2026 Oracle and/or its affiliates.
#
# This file is part of VirtualBox base platform packages, as
# available from https://www.virtualbox.org.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, in version 3 of the
# License.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, see <https://www.gnu.org/licenses>.
#
# SPDX-License-Identifier: GPL-3.0-only
#

SUB_DEPTH = ../../../../..
include $(KBUILD_PATH)/subheader.kmk

if defined(VBOX_WITH_TESTCASES) && !defined(VBOX_ONLY_ADDITIONS) && !defined(VBOX_ONLY_SDK)
 PROGRAMS += tstClipboardHostService
 tstClipboardHostService_TEMPLATE = VBoxR3TstExe
 tstClipboardHostService_DEFS     = VBOX_WITH_HGCM VBOX_WITH_SHARED_CLIPBOARD_HOST UNIT_TEST
 tstClipboardHostService_SOURCES  = \
 	../VBoxSharedClipboardSvc.cpp \
 	../VBoxSharedClipboardSvc-ext.cpp \
 	../VBoxSharedClipboardSvc-client.cpp \
 	../VBoxSharedClipboardSvc-host.cpp \
 	../VBoxSharedClipboardSvc-transport.cpp \
 	$(PATH_ROOT)/src/VBox/GuestHost/SharedClipboard/clipboard-common.cpp \
 	$(PATH_ROOT)/src/VBox/GuestHost/SharedClipboard/clipboard-helper.cpp \
 	tstClipboardHostService.cpp
 tstClipboardHostService_LIBS     = $(LIB_RUNTIME)
 tstClipboardHostService_CLEAN    = $(tstClipboardHostService_0_OUTDIR)/tstClipboardHostService.run

 if defined(VBOX_WITH_SHARED_CLIPBOARD_TRANSFERS)
  tstClipboardHostService_DEFS    += VBOX_WITH_SHARED_CLIPBOARD_TRANSFERS
  tstClipboardHostService_SOURCES += \
  	../VBoxSharedClipboardSvc-transfers.cpp \
  	$(PATH_ROOT)/src/VBox/GuestHost/SharedClipboard/clipboard-path.cpp \
  	$(PATH_ROOT)/src/VBox/GuestHost/SharedClipboard/clipboard-transfers.cpp
 endif

 $$(tstClipboardHostService_0_OUTDIR)/tstClipboardHostService.run: $$(tstClipboardHostService_1_STAGE_TARGET) | $$(dir $$@) $$(VBOX_RUN_TARGET_ORDER_DEPS)
	export VBOX_LOG_DEST=nofile; $(tstClipboardHostService_1_STAGE_TARGET) quiet
	$(QUIET)$(APPEND) -t "$@" "done"

 ifeq ($(KBUILD_TARGET).$(KBUILD_TARGET_ARCH),$(KBUILD_HOST).$(KBUILD_HOST_ARCH))
  TESTING += $(tstClipboardHostService_0_OUTDIR)/tstClipboardHostService.run
 endif
endif

include $(FILE_KBUILD_SUB_FOOTER)
