# $Id: Makefile.kmk 114993 2026-08-11 14:46:01Z andreas.loeffler@oracle.com $
## @file
# Sub-Makefile for the Shared Clipboard Host Service.
#

#
# Copyright (C) 2006-2026 Oracle and/or its affiliates.
#
# This file is part of VirtualBox base platform packages, as
# available from https://www.virtualbox.org.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, in version 3 of the
# License.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, see <https://www.gnu.org/licenses>.
#
# SPDX-License-Identifier: GPL-3.0-only
#

SUB_DEPTH = ../../../..
include $(KBUILD_PATH)/subheader.kmk

# Include sub-makefile(s).
include $(PATH_SUB_CURRENT)/testcase/Makefile.kmk

#
# The Shared Clipboard service DLL.
#
DLLS += VBoxSharedClipboard
VBoxSharedClipboard_TEMPLATE  = VBoxR3Dll
VBoxSharedClipboard_DEFS      = \
	VBOX_WITH_SHARED_CLIPBOARD_HOST \
	VBOX_WITH_HGCM \
	$(if $(VBOX_WITH_SHARED_CLIPBOARD_TRANSFERS),VBOX_WITH_SHARED_CLIPBOARD_TRANSFERS,)
VBoxSharedClipboard_INCS.win  = \
	$(VBOX_PATH_SDK)

VBoxSharedClipboard_SOURCES = \
	VBoxSharedClipboardSvc.cpp \
	VBoxSharedClipboardSvc-backend.cpp \
	VBoxSharedClipboardSvc-client.cpp \
	VBoxSharedClipboardSvc-host.cpp \
	$(PATH_ROOT)/src/VBox/GuestHost/SharedClipboard/clipboard-common.cpp \
	$(PATH_ROOT)/src/VBox/GuestHost/SharedClipboard/clipboard-helper.cpp
VBoxSharedClipboard_SOURCES.win = \
	VBoxSharedClipboardSvc.rc
ifdef VBOX_WITH_SHARED_CLIPBOARD_TRANSFERS
 VBoxSharedClipboard_SOURCES += \
 	VBoxSharedClipboardSvc-transfers.cpp \
 	$(PATH_ROOT)/src/VBox/GuestHost/SharedClipboard/clipboard-path.cpp \
 	$(PATH_ROOT)/src/VBox/GuestHost/SharedClipboard/clipboard-transfers.cpp
endif

VBoxSharedClipboard_LIBS = \
	$(LIB_RUNTIME)

VBoxSharedClipboard_LDFLAGS.darwin = \
	-install_name $(VBOX_DYLD_EXECUTABLE_PATH)/VBoxSharedClipboard.dylib

include $(FILE_KBUILD_SUB_FOOTER)
