# $Id: Makefile.kmk 115154 2026-09-03 12:05:59Z aleksey.ilyushin@oracle.com $
## @file
# OpenSSL Sub-Makefile.
#

#
# Copyright (C) 2019-2026 Oracle and/or its affiliates.
#
# This file is part of VirtualBox base platform packages, as
# available from https://www.virtualbox.org.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, in version 3 of the
# License.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, see <https://www.gnu.org/licenses>.
#
# SPDX-License-Identifier: GPL-3.0-only
#

SUB_DEPTH = ../../../../..
include $(KBUILD_PATH)/subheader.kmk

#	slh_dsa_cfb.c \
#	slh_dsa_ecb.c \
#	slh_dsa_ofb.c

LIBRARIES += crypto_slh_dsa
crypto_slh_dsa_TEMPLATE = SubLibCrypto
crypto_slh_dsa_DEFS = OPENSSL_NO_DEPRECATED
crypto_slh_dsa_SOURCES = \
	slh_adrs.c \
	slh_dsa.c \
	slh_dsa_hash_ctx.c \
	slh_dsa_key.c \
	slh_fors.c \
	slh_hash.c \
	slh_hypertree.c \
	slh_params.c \
	slh_wots.c \
	slh_xmss.c

$(evalcall VBOX_OPENSSL_X86,crypto_slh_dsa)

include $(FILE_KBUILD_SUB_FOOTER)
