# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401


from vbox_server.models.base_model_ import Model
from vbox_server.models.appliance import Appliance
from vbox_server import util


class ApplianceResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, appliance: Appliance=None):  # noqa: E501
        """ApplianceResponse - a model defined in Swagger

        :param appliance: The appliance of this ApplianceResponse.  # noqa: E501
        :type appliance: Appliance
        """
        self.swagger_types = {
            'appliance': Appliance
        }

        self.attribute_map = {
            'appliance': 'appliance'
        }

        self._appliance = appliance

    @classmethod
    def from_dict(cls, dikt) -> 'ApplianceResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Appliance_response of this ApplianceResponse.  # noqa: E501
        :rtype: ApplianceResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def appliance(self) -> Appliance:
        """Gets the appliance of this ApplianceResponse.


        :return: The appliance of this ApplianceResponse.
        :rtype: Appliance
        """
        return self._appliance

    @appliance.setter
    def appliance(self, appliance: Appliance):
        """Sets the appliance of this ApplianceResponse.


        :param appliance: The appliance of this ApplianceResponse.
        :type appliance: Appliance
        """

        self._appliance = appliance
