# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401


from vbox_server.models.base_model_ import Model
from vbox_server import util


class BandwidthControl(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, num_groups: int=None):  # noqa: E501
        """BandwidthControl - a model defined in Swagger

        :param num_groups: The num_groups of this BandwidthControl.  # noqa: E501
        :type num_groups: int
        """
        self.swagger_types = {
            'num_groups': int
        }

        self.attribute_map = {
            'num_groups': 'numGroups'
        }

        self._num_groups = num_groups

    @classmethod
    def from_dict(cls, dikt) -> 'BandwidthControl':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BandwidthControl of this BandwidthControl.  # noqa: E501
        :rtype: BandwidthControl
        """
        return util.deserialize_model(dikt, cls)

    @property
    def num_groups(self) -> int:
        """Gets the num_groups of this BandwidthControl.


        :return: The num_groups of this BandwidthControl.
        :rtype: int
        """
        return self._num_groups

    @num_groups.setter
    def num_groups(self, num_groups: int):
        """Sets the num_groups of this BandwidthControl.


        :param num_groups: The num_groups of this BandwidthControl.
        :type num_groups: int
        """

        self._num_groups = num_groups
