# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401


from vbox_server.models.base_model_ import Model
from vbox_server import util


class CloneOptions(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    LINK = "LINK"
    KEEPALLMACS = "KEEPALLMACS"
    KEEPNATMACS = "KEEPNATMACS"
    KEEPDISKNAMES = "KEEPDISKNAMES"
    KEEPHWUUIDS = "KEEPHWUUIDS"

    def __init__(self):  # noqa: E501
        """CloneOptions - a model defined in Swagger

        """
        self.swagger_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'CloneOptions':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CloneOptions of this CloneOptions.  # noqa: E501
        :rtype: CloneOptions
        """
        return util.deserialize_model(dikt, cls)
