# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401


from vbox_server.models.base_model_ import Model
from vbox_server.models.cloud_machine_state import CloudMachineState
from vbox_server.models.virtual_box_error_info import VirtualBoxErrorInfo
from vbox_server import util


class CloudMachine(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, id: str=None, cloud_id: str=None, accessible: bool=None, access_error: VirtualBoxErrorInfo=None, name: str=None, os_type_id: str=None, state: CloudMachineState=None, console_connection_fingerprint: str=None, serial_console_command: str=None, serial_console_command_windows: str=None, vnc_console_command: str=None, vnc_console_command_windows: str=None):  # noqa: E501
        """CloudMachine - a model defined in Swagger

        :param id: The id of this CloudMachine.  # noqa: E501
        :type id: str
        :param cloud_id: The cloud_id of this CloudMachine.  # noqa: E501
        :type cloud_id: str
        :param accessible: The accessible of this CloudMachine.  # noqa: E501
        :type accessible: bool
        :param access_error: The access_error of this CloudMachine.  # noqa: E501
        :type access_error: VirtualBoxErrorInfo
        :param name: The name of this CloudMachine.  # noqa: E501
        :type name: str
        :param os_type_id: The os_type_id of this CloudMachine.  # noqa: E501
        :type os_type_id: str
        :param state: The state of this CloudMachine.  # noqa: E501
        :type state: CloudMachineState
        :param console_connection_fingerprint: The console_connection_fingerprint of this CloudMachine.  # noqa: E501
        :type console_connection_fingerprint: str
        :param serial_console_command: The serial_console_command of this CloudMachine.  # noqa: E501
        :type serial_console_command: str
        :param serial_console_command_windows: The serial_console_command_windows of this CloudMachine.  # noqa: E501
        :type serial_console_command_windows: str
        :param vnc_console_command: The vnc_console_command of this CloudMachine.  # noqa: E501
        :type vnc_console_command: str
        :param vnc_console_command_windows: The vnc_console_command_windows of this CloudMachine.  # noqa: E501
        :type vnc_console_command_windows: str
        """
        self.swagger_types = {
            'id': str,
            'cloud_id': str,
            'accessible': bool,
            'access_error': VirtualBoxErrorInfo,
            'name': str,
            'os_type_id': str,
            'state': CloudMachineState,
            'console_connection_fingerprint': str,
            'serial_console_command': str,
            'serial_console_command_windows': str,
            'vnc_console_command': str,
            'vnc_console_command_windows': str
        }

        self.attribute_map = {
            'id': 'id',
            'cloud_id': 'cloudId',
            'accessible': 'accessible',
            'access_error': 'accessError',
            'name': 'name',
            'os_type_id': 'OSTypeId',
            'state': 'state',
            'console_connection_fingerprint': 'consoleConnectionFingerprint',
            'serial_console_command': 'serialConsoleCommand',
            'serial_console_command_windows': 'serialConsoleCommandWindows',
            'vnc_console_command': 'VNCConsoleCommand',
            'vnc_console_command_windows': 'VNCConsoleCommandWindows'
        }

        self._id = id
        self._cloud_id = cloud_id
        self._accessible = accessible
        self._access_error = access_error
        self._name = name
        self._os_type_id = os_type_id
        self._state = state
        self._console_connection_fingerprint = console_connection_fingerprint
        self._serial_console_command = serial_console_command
        self._serial_console_command_windows = serial_console_command_windows
        self._vnc_console_command = vnc_console_command
        self._vnc_console_command_windows = vnc_console_command_windows

    @classmethod
    def from_dict(cls, dikt) -> 'CloudMachine':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CloudMachine of this CloudMachine.  # noqa: E501
        :rtype: CloudMachine
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this CloudMachine.


        :return: The id of this CloudMachine.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this CloudMachine.


        :param id: The id of this CloudMachine.
        :type id: str
        """

        self._id = id

    @property
    def cloud_id(self) -> str:
        """Gets the cloud_id of this CloudMachine.


        :return: The cloud_id of this CloudMachine.
        :rtype: str
        """
        return self._cloud_id

    @cloud_id.setter
    def cloud_id(self, cloud_id: str):
        """Sets the cloud_id of this CloudMachine.


        :param cloud_id: The cloud_id of this CloudMachine.
        :type cloud_id: str
        """

        self._cloud_id = cloud_id

    @property
    def accessible(self) -> bool:
        """Gets the accessible of this CloudMachine.


        :return: The accessible of this CloudMachine.
        :rtype: bool
        """
        return self._accessible

    @accessible.setter
    def accessible(self, accessible: bool):
        """Sets the accessible of this CloudMachine.


        :param accessible: The accessible of this CloudMachine.
        :type accessible: bool
        """

        self._accessible = accessible

    @property
    def access_error(self) -> VirtualBoxErrorInfo:
        """Gets the access_error of this CloudMachine.


        :return: The access_error of this CloudMachine.
        :rtype: VirtualBoxErrorInfo
        """
        return self._access_error

    @access_error.setter
    def access_error(self, access_error: VirtualBoxErrorInfo):
        """Sets the access_error of this CloudMachine.


        :param access_error: The access_error of this CloudMachine.
        :type access_error: VirtualBoxErrorInfo
        """

        self._access_error = access_error

    @property
    def name(self) -> str:
        """Gets the name of this CloudMachine.


        :return: The name of this CloudMachine.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this CloudMachine.


        :param name: The name of this CloudMachine.
        :type name: str
        """

        self._name = name

    @property
    def os_type_id(self) -> str:
        """Gets the os_type_id of this CloudMachine.


        :return: The os_type_id of this CloudMachine.
        :rtype: str
        """
        return self._os_type_id

    @os_type_id.setter
    def os_type_id(self, os_type_id: str):
        """Sets the os_type_id of this CloudMachine.


        :param os_type_id: The os_type_id of this CloudMachine.
        :type os_type_id: str
        """

        self._os_type_id = os_type_id

    @property
    def state(self) -> CloudMachineState:
        """Gets the state of this CloudMachine.


        :return: The state of this CloudMachine.
        :rtype: CloudMachineState
        """
        return self._state

    @state.setter
    def state(self, state: CloudMachineState):
        """Sets the state of this CloudMachine.


        :param state: The state of this CloudMachine.
        :type state: CloudMachineState
        """

        self._state = state

    @property
    def console_connection_fingerprint(self) -> str:
        """Gets the console_connection_fingerprint of this CloudMachine.


        :return: The console_connection_fingerprint of this CloudMachine.
        :rtype: str
        """
        return self._console_connection_fingerprint

    @console_connection_fingerprint.setter
    def console_connection_fingerprint(self, console_connection_fingerprint: str):
        """Sets the console_connection_fingerprint of this CloudMachine.


        :param console_connection_fingerprint: The console_connection_fingerprint of this CloudMachine.
        :type console_connection_fingerprint: str
        """

        self._console_connection_fingerprint = console_connection_fingerprint

    @property
    def serial_console_command(self) -> str:
        """Gets the serial_console_command of this CloudMachine.


        :return: The serial_console_command of this CloudMachine.
        :rtype: str
        """
        return self._serial_console_command

    @serial_console_command.setter
    def serial_console_command(self, serial_console_command: str):
        """Sets the serial_console_command of this CloudMachine.


        :param serial_console_command: The serial_console_command of this CloudMachine.
        :type serial_console_command: str
        """

        self._serial_console_command = serial_console_command

    @property
    def serial_console_command_windows(self) -> str:
        """Gets the serial_console_command_windows of this CloudMachine.


        :return: The serial_console_command_windows of this CloudMachine.
        :rtype: str
        """
        return self._serial_console_command_windows

    @serial_console_command_windows.setter
    def serial_console_command_windows(self, serial_console_command_windows: str):
        """Sets the serial_console_command_windows of this CloudMachine.


        :param serial_console_command_windows: The serial_console_command_windows of this CloudMachine.
        :type serial_console_command_windows: str
        """

        self._serial_console_command_windows = serial_console_command_windows

    @property
    def vnc_console_command(self) -> str:
        """Gets the vnc_console_command of this CloudMachine.


        :return: The vnc_console_command of this CloudMachine.
        :rtype: str
        """
        return self._vnc_console_command

    @vnc_console_command.setter
    def vnc_console_command(self, vnc_console_command: str):
        """Sets the vnc_console_command of this CloudMachine.


        :param vnc_console_command: The vnc_console_command of this CloudMachine.
        :type vnc_console_command: str
        """

        self._vnc_console_command = vnc_console_command

    @property
    def vnc_console_command_windows(self) -> str:
        """Gets the vnc_console_command_windows of this CloudMachine.


        :return: The vnc_console_command_windows of this CloudMachine.
        :rtype: str
        """
        return self._vnc_console_command_windows

    @vnc_console_command_windows.setter
    def vnc_console_command_windows(self, vnc_console_command_windows: str):
        """Sets the vnc_console_command_windows of this CloudMachine.


        :param vnc_console_command_windows: The vnc_console_command_windows of this CloudMachine.
        :type vnc_console_command_windows: str
        """

        self._vnc_console_command_windows = vnc_console_command_windows
