# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401


from vbox_server.models.base_model_ import Model
from vbox_server.models.event_source import EventSource
from vbox_server.models.host_usb_device import HostUSBDevice
from vbox_server.models.keyboard import Keyboard
from vbox_server.models.machine_debugger import MachineDebugger
from vbox_server.models.machine_state import MachineState
from vbox_server.models.mouse import Mouse
from vbox_server.models.pci_device_attachment import PCIDeviceAttachment
from vbox_server.models.shared_folder import SharedFolder
from vbox_server.models.usb_device import USBDevice
from vbox_server.models.vrde_server_info import VRDEServerInfo
from vbox_server import util


class Console(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, machine: str=None, state: MachineState=None, keyboard: Keyboard=None, mouse: Mouse=None, debugger: MachineDebugger=None, usb_devices: List[USBDevice]=None, remote_usb_devices: List[HostUSBDevice]=None, shared_folders: List[SharedFolder]=None, vrde_server_info: VRDEServerInfo=None, event_source: EventSource=None, attached_pci_devices: List[PCIDeviceAttachment]=None, use_host_clipboard: bool=None):  # noqa: E501
        """Console - a model defined in Swagger

        :param machine: The machine of this Console.  # noqa: E501
        :type machine: str
        :param state: The state of this Console.  # noqa: E501
        :type state: MachineState
        :param keyboard: The keyboard of this Console.  # noqa: E501
        :type keyboard: Keyboard
        :param mouse: The mouse of this Console.  # noqa: E501
        :type mouse: Mouse
        :param debugger: The debugger of this Console.  # noqa: E501
        :type debugger: MachineDebugger
        :param usb_devices: The usb_devices of this Console.  # noqa: E501
        :type usb_devices: List[USBDevice]
        :param remote_usb_devices: The remote_usb_devices of this Console.  # noqa: E501
        :type remote_usb_devices: List[HostUSBDevice]
        :param shared_folders: The shared_folders of this Console.  # noqa: E501
        :type shared_folders: List[SharedFolder]
        :param vrde_server_info: The vrde_server_info of this Console.  # noqa: E501
        :type vrde_server_info: VRDEServerInfo
        :param event_source: The event_source of this Console.  # noqa: E501
        :type event_source: EventSource
        :param attached_pci_devices: The attached_pci_devices of this Console.  # noqa: E501
        :type attached_pci_devices: List[PCIDeviceAttachment]
        :param use_host_clipboard: The use_host_clipboard of this Console.  # noqa: E501
        :type use_host_clipboard: bool
        """
        self.swagger_types = {
            'machine': str,
            'state': MachineState,
            'keyboard': Keyboard,
            'mouse': Mouse,
            'debugger': MachineDebugger,
            'usb_devices': List[USBDevice],
            'remote_usb_devices': List[HostUSBDevice],
            'shared_folders': List[SharedFolder],
            'vrde_server_info': VRDEServerInfo,
            'event_source': EventSource,
            'attached_pci_devices': List[PCIDeviceAttachment],
            'use_host_clipboard': bool
        }

        self.attribute_map = {
            'machine': 'machine',
            'state': 'state',
            'keyboard': 'keyboard',
            'mouse': 'mouse',
            'debugger': 'debugger',
            'usb_devices': 'USBDevices',
            'remote_usb_devices': 'remoteUSBDevices',
            'shared_folders': 'sharedFolders',
            'vrde_server_info': 'VRDEServerInfo',
            'event_source': 'eventSource',
            'attached_pci_devices': 'attachedPCIDevices',
            'use_host_clipboard': 'useHostClipboard'
        }

        self._machine = machine
        self._state = state
        self._keyboard = keyboard
        self._mouse = mouse
        self._debugger = debugger
        self._usb_devices = usb_devices
        self._remote_usb_devices = remote_usb_devices
        self._shared_folders = shared_folders
        self._vrde_server_info = vrde_server_info
        self._event_source = event_source
        self._attached_pci_devices = attached_pci_devices
        self._use_host_clipboard = use_host_clipboard

    @classmethod
    def from_dict(cls, dikt) -> 'Console':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Console of this Console.  # noqa: E501
        :rtype: Console
        """
        return util.deserialize_model(dikt, cls)

    @property
    def machine(self) -> str:
        """Gets the machine of this Console.


        :return: The machine of this Console.
        :rtype: str
        """
        return self._machine

    @machine.setter
    def machine(self, machine: str):
        """Sets the machine of this Console.


        :param machine: The machine of this Console.
        :type machine: str
        """

        self._machine = machine

    @property
    def state(self) -> MachineState:
        """Gets the state of this Console.


        :return: The state of this Console.
        :rtype: MachineState
        """
        return self._state

    @state.setter
    def state(self, state: MachineState):
        """Sets the state of this Console.


        :param state: The state of this Console.
        :type state: MachineState
        """

        self._state = state

    @property
    def keyboard(self) -> Keyboard:
        """Gets the keyboard of this Console.


        :return: The keyboard of this Console.
        :rtype: Keyboard
        """
        return self._keyboard

    @keyboard.setter
    def keyboard(self, keyboard: Keyboard):
        """Sets the keyboard of this Console.


        :param keyboard: The keyboard of this Console.
        :type keyboard: Keyboard
        """

        self._keyboard = keyboard

    @property
    def mouse(self) -> Mouse:
        """Gets the mouse of this Console.


        :return: The mouse of this Console.
        :rtype: Mouse
        """
        return self._mouse

    @mouse.setter
    def mouse(self, mouse: Mouse):
        """Sets the mouse of this Console.


        :param mouse: The mouse of this Console.
        :type mouse: Mouse
        """

        self._mouse = mouse

    @property
    def debugger(self) -> MachineDebugger:
        """Gets the debugger of this Console.


        :return: The debugger of this Console.
        :rtype: MachineDebugger
        """
        return self._debugger

    @debugger.setter
    def debugger(self, debugger: MachineDebugger):
        """Sets the debugger of this Console.


        :param debugger: The debugger of this Console.
        :type debugger: MachineDebugger
        """

        self._debugger = debugger

    @property
    def usb_devices(self) -> List[USBDevice]:
        """Gets the usb_devices of this Console.


        :return: The usb_devices of this Console.
        :rtype: List[USBDevice]
        """
        return self._usb_devices

    @usb_devices.setter
    def usb_devices(self, usb_devices: List[USBDevice]):
        """Sets the usb_devices of this Console.


        :param usb_devices: The usb_devices of this Console.
        :type usb_devices: List[USBDevice]
        """

        self._usb_devices = usb_devices

    @property
    def remote_usb_devices(self) -> List[HostUSBDevice]:
        """Gets the remote_usb_devices of this Console.


        :return: The remote_usb_devices of this Console.
        :rtype: List[HostUSBDevice]
        """
        return self._remote_usb_devices

    @remote_usb_devices.setter
    def remote_usb_devices(self, remote_usb_devices: List[HostUSBDevice]):
        """Sets the remote_usb_devices of this Console.


        :param remote_usb_devices: The remote_usb_devices of this Console.
        :type remote_usb_devices: List[HostUSBDevice]
        """

        self._remote_usb_devices = remote_usb_devices

    @property
    def shared_folders(self) -> List[SharedFolder]:
        """Gets the shared_folders of this Console.


        :return: The shared_folders of this Console.
        :rtype: List[SharedFolder]
        """
        return self._shared_folders

    @shared_folders.setter
    def shared_folders(self, shared_folders: List[SharedFolder]):
        """Sets the shared_folders of this Console.


        :param shared_folders: The shared_folders of this Console.
        :type shared_folders: List[SharedFolder]
        """

        self._shared_folders = shared_folders

    @property
    def vrde_server_info(self) -> VRDEServerInfo:
        """Gets the vrde_server_info of this Console.


        :return: The vrde_server_info of this Console.
        :rtype: VRDEServerInfo
        """
        return self._vrde_server_info

    @vrde_server_info.setter
    def vrde_server_info(self, vrde_server_info: VRDEServerInfo):
        """Sets the vrde_server_info of this Console.


        :param vrde_server_info: The vrde_server_info of this Console.
        :type vrde_server_info: VRDEServerInfo
        """

        self._vrde_server_info = vrde_server_info

    @property
    def event_source(self) -> EventSource:
        """Gets the event_source of this Console.


        :return: The event_source of this Console.
        :rtype: EventSource
        """
        return self._event_source

    @event_source.setter
    def event_source(self, event_source: EventSource):
        """Sets the event_source of this Console.


        :param event_source: The event_source of this Console.
        :type event_source: EventSource
        """

        self._event_source = event_source

    @property
    def attached_pci_devices(self) -> List[PCIDeviceAttachment]:
        """Gets the attached_pci_devices of this Console.


        :return: The attached_pci_devices of this Console.
        :rtype: List[PCIDeviceAttachment]
        """
        return self._attached_pci_devices

    @attached_pci_devices.setter
    def attached_pci_devices(self, attached_pci_devices: List[PCIDeviceAttachment]):
        """Sets the attached_pci_devices of this Console.


        :param attached_pci_devices: The attached_pci_devices of this Console.
        :type attached_pci_devices: List[PCIDeviceAttachment]
        """

        self._attached_pci_devices = attached_pci_devices

    @property
    def use_host_clipboard(self) -> bool:
        """Gets the use_host_clipboard of this Console.


        :return: The use_host_clipboard of this Console.
        :rtype: bool
        """
        return self._use_host_clipboard

    @use_host_clipboard.setter
    def use_host_clipboard(self, use_host_clipboard: bool):
        """Sets the use_host_clipboard of this Console.


        :param use_host_clipboard: The use_host_clipboard of this Console.
        :type use_host_clipboard: bool
        """

        self._use_host_clipboard = use_host_clipboard
