# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401


from vbox_server.models.base_model_ import Model
from vbox_server import util


class DHCPIndividualConfig(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, mac_address: str=None, machine_id: str=None, slot: int=None, fixed_address: str=None):  # noqa: E501
        """DHCPIndividualConfig - a model defined in Swagger

        :param mac_address: The mac_address of this DHCPIndividualConfig.  # noqa: E501
        :type mac_address: str
        :param machine_id: The machine_id of this DHCPIndividualConfig.  # noqa: E501
        :type machine_id: str
        :param slot: The slot of this DHCPIndividualConfig.  # noqa: E501
        :type slot: int
        :param fixed_address: The fixed_address of this DHCPIndividualConfig.  # noqa: E501
        :type fixed_address: str
        """
        self.swagger_types = {
            'mac_address': str,
            'machine_id': str,
            'slot': int,
            'fixed_address': str
        }

        self.attribute_map = {
            'mac_address': 'MACAddress',
            'machine_id': 'machineId',
            'slot': 'slot',
            'fixed_address': 'fixedAddress'
        }

        self._mac_address = mac_address
        self._machine_id = machine_id
        self._slot = slot
        self._fixed_address = fixed_address

    @classmethod
    def from_dict(cls, dikt) -> 'DHCPIndividualConfig':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DHCPIndividualConfig of this DHCPIndividualConfig.  # noqa: E501
        :rtype: DHCPIndividualConfig
        """
        return util.deserialize_model(dikt, cls)

    @property
    def mac_address(self) -> str:
        """Gets the mac_address of this DHCPIndividualConfig.


        :return: The mac_address of this DHCPIndividualConfig.
        :rtype: str
        """
        return self._mac_address

    @mac_address.setter
    def mac_address(self, mac_address: str):
        """Sets the mac_address of this DHCPIndividualConfig.


        :param mac_address: The mac_address of this DHCPIndividualConfig.
        :type mac_address: str
        """

        self._mac_address = mac_address

    @property
    def machine_id(self) -> str:
        """Gets the machine_id of this DHCPIndividualConfig.


        :return: The machine_id of this DHCPIndividualConfig.
        :rtype: str
        """
        return self._machine_id

    @machine_id.setter
    def machine_id(self, machine_id: str):
        """Sets the machine_id of this DHCPIndividualConfig.


        :param machine_id: The machine_id of this DHCPIndividualConfig.
        :type machine_id: str
        """

        self._machine_id = machine_id

    @property
    def slot(self) -> int:
        """Gets the slot of this DHCPIndividualConfig.


        :return: The slot of this DHCPIndividualConfig.
        :rtype: int
        """
        return self._slot

    @slot.setter
    def slot(self, slot: int):
        """Sets the slot of this DHCPIndividualConfig.


        :param slot: The slot of this DHCPIndividualConfig.
        :type slot: int
        """

        self._slot = slot

    @property
    def fixed_address(self) -> str:
        """Gets the fixed_address of this DHCPIndividualConfig.


        :return: The fixed_address of this DHCPIndividualConfig.
        :rtype: str
        """
        return self._fixed_address

    @fixed_address.setter
    def fixed_address(self, fixed_address: str):
        """Sets the fixed_address of this DHCPIndividualConfig.


        :param fixed_address: The fixed_address of this DHCPIndividualConfig.
        :type fixed_address: str
        """

        self._fixed_address = fixed_address
