# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401


from vbox_server.models.base_model_ import Model
from vbox_server.models.dhcp_config_scope import DHCPConfigScope
from vbox_server.models.dhcp_option import DHCPOption
from vbox_server import util


class DHCPConfig(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, scope: DHCPConfigScope=None, min_lease_time: int=None, default_lease_time: int=None, max_lease_time: int=None, forced_options: List[DHCPOption]=None, suppressed_options: List[DHCPOption]=None):  # noqa: E501
        """DHCPConfig - a model defined in Swagger

        :param scope: The scope of this DHCPConfig.  # noqa: E501
        :type scope: DHCPConfigScope
        :param min_lease_time: The min_lease_time of this DHCPConfig.  # noqa: E501
        :type min_lease_time: int
        :param default_lease_time: The default_lease_time of this DHCPConfig.  # noqa: E501
        :type default_lease_time: int
        :param max_lease_time: The max_lease_time of this DHCPConfig.  # noqa: E501
        :type max_lease_time: int
        :param forced_options: The forced_options of this DHCPConfig.  # noqa: E501
        :type forced_options: List[DHCPOption]
        :param suppressed_options: The suppressed_options of this DHCPConfig.  # noqa: E501
        :type suppressed_options: List[DHCPOption]
        """
        self.swagger_types = {
            'scope': DHCPConfigScope,
            'min_lease_time': int,
            'default_lease_time': int,
            'max_lease_time': int,
            'forced_options': List[DHCPOption],
            'suppressed_options': List[DHCPOption]
        }

        self.attribute_map = {
            'scope': 'scope',
            'min_lease_time': 'minLeaseTime',
            'default_lease_time': 'defaultLeaseTime',
            'max_lease_time': 'maxLeaseTime',
            'forced_options': 'forcedOptions',
            'suppressed_options': 'suppressedOptions'
        }

        self._scope = scope
        self._min_lease_time = min_lease_time
        self._default_lease_time = default_lease_time
        self._max_lease_time = max_lease_time
        self._forced_options = forced_options
        self._suppressed_options = suppressed_options

    @classmethod
    def from_dict(cls, dikt) -> 'DHCPConfig':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DHCPConfig of this DHCPConfig.  # noqa: E501
        :rtype: DHCPConfig
        """
        return util.deserialize_model(dikt, cls)

    @property
    def scope(self) -> DHCPConfigScope:
        """Gets the scope of this DHCPConfig.


        :return: The scope of this DHCPConfig.
        :rtype: DHCPConfigScope
        """
        return self._scope

    @scope.setter
    def scope(self, scope: DHCPConfigScope):
        """Sets the scope of this DHCPConfig.


        :param scope: The scope of this DHCPConfig.
        :type scope: DHCPConfigScope
        """

        self._scope = scope

    @property
    def min_lease_time(self) -> int:
        """Gets the min_lease_time of this DHCPConfig.


        :return: The min_lease_time of this DHCPConfig.
        :rtype: int
        """
        return self._min_lease_time

    @min_lease_time.setter
    def min_lease_time(self, min_lease_time: int):
        """Sets the min_lease_time of this DHCPConfig.


        :param min_lease_time: The min_lease_time of this DHCPConfig.
        :type min_lease_time: int
        """

        self._min_lease_time = min_lease_time

    @property
    def default_lease_time(self) -> int:
        """Gets the default_lease_time of this DHCPConfig.


        :return: The default_lease_time of this DHCPConfig.
        :rtype: int
        """
        return self._default_lease_time

    @default_lease_time.setter
    def default_lease_time(self, default_lease_time: int):
        """Sets the default_lease_time of this DHCPConfig.


        :param default_lease_time: The default_lease_time of this DHCPConfig.
        :type default_lease_time: int
        """

        self._default_lease_time = default_lease_time

    @property
    def max_lease_time(self) -> int:
        """Gets the max_lease_time of this DHCPConfig.


        :return: The max_lease_time of this DHCPConfig.
        :rtype: int
        """
        return self._max_lease_time

    @max_lease_time.setter
    def max_lease_time(self, max_lease_time: int):
        """Sets the max_lease_time of this DHCPConfig.


        :param max_lease_time: The max_lease_time of this DHCPConfig.
        :type max_lease_time: int
        """

        self._max_lease_time = max_lease_time

    @property
    def forced_options(self) -> List[DHCPOption]:
        """Gets the forced_options of this DHCPConfig.


        :return: The forced_options of this DHCPConfig.
        :rtype: List[DHCPOption]
        """
        return self._forced_options

    @forced_options.setter
    def forced_options(self, forced_options: List[DHCPOption]):
        """Sets the forced_options of this DHCPConfig.


        :param forced_options: The forced_options of this DHCPConfig.
        :type forced_options: List[DHCPOption]
        """

        self._forced_options = forced_options

    @property
    def suppressed_options(self) -> List[DHCPOption]:
        """Gets the suppressed_options of this DHCPConfig.


        :return: The suppressed_options of this DHCPConfig.
        :rtype: List[DHCPOption]
        """
        return self._suppressed_options

    @suppressed_options.setter
    def suppressed_options(self, suppressed_options: List[DHCPOption]):
        """Sets the suppressed_options of this DHCPConfig.


        :param suppressed_options: The suppressed_options of this DHCPConfig.
        :type suppressed_options: List[DHCPOption]
        """

        self._suppressed_options = suppressed_options
