# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401


from vbox_server.models.base_model_ import Model
from vbox_server.models.dhcp_server import DHCPServer
from vbox_server import util


class DHCPServerResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, server: DHCPServer=None):  # noqa: E501
        """DHCPServerResponse - a model defined in Swagger

        :param server: The server of this DHCPServerResponse.  # noqa: E501
        :type server: DHCPServer
        """
        self.swagger_types = {
            'server': DHCPServer
        }

        self.attribute_map = {
            'server': 'server'
        }

        self._server = server

    @classmethod
    def from_dict(cls, dikt) -> 'DHCPServerResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DHCPServer_response of this DHCPServerResponse.  # noqa: E501
        :rtype: DHCPServerResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def server(self) -> DHCPServer:
        """Gets the server of this DHCPServerResponse.


        :return: The server of this DHCPServerResponse.
        :rtype: DHCPServer
        """
        return self._server

    @server.setter
    def server(self, server: DHCPServer):
        """Sets the server of this DHCPServerResponse.


        :param server: The server of this DHCPServerResponse.
        :type server: DHCPServer
        """

        self._server = server
