# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401


from vbox_server.models.base_model_ import Model
from vbox_server import util


class DHCPServerSetConfigurationRequestBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, ip_address: str=None, network_mask: str=None, from_ip_address: str=None, to_ip_address: str=None):  # noqa: E501
        """DHCPServerSetConfigurationRequestBody - a model defined in Swagger

        :param ip_address: The ip_address of this DHCPServerSetConfigurationRequestBody.  # noqa: E501
        :type ip_address: str
        :param network_mask: The network_mask of this DHCPServerSetConfigurationRequestBody.  # noqa: E501
        :type network_mask: str
        :param from_ip_address: The from_ip_address of this DHCPServerSetConfigurationRequestBody.  # noqa: E501
        :type from_ip_address: str
        :param to_ip_address: The to_ip_address of this DHCPServerSetConfigurationRequestBody.  # noqa: E501
        :type to_ip_address: str
        """
        self.swagger_types = {
            'ip_address': str,
            'network_mask': str,
            'from_ip_address': str,
            'to_ip_address': str
        }

        self.attribute_map = {
            'ip_address': 'IPAddress',
            'network_mask': 'networkMask',
            'from_ip_address': 'FromIPAddress',
            'to_ip_address': 'ToIPAddress'
        }

        self._ip_address = ip_address
        self._network_mask = network_mask
        self._from_ip_address = from_ip_address
        self._to_ip_address = to_ip_address

    @classmethod
    def from_dict(cls, dikt) -> 'DHCPServerSetConfigurationRequestBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DHCPServerSetConfigurationRequestBody of this DHCPServerSetConfigurationRequestBody.  # noqa: E501
        :rtype: DHCPServerSetConfigurationRequestBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def ip_address(self) -> str:
        """Gets the ip_address of this DHCPServerSetConfigurationRequestBody.


        :return: The ip_address of this DHCPServerSetConfigurationRequestBody.
        :rtype: str
        """
        return self._ip_address

    @ip_address.setter
    def ip_address(self, ip_address: str):
        """Sets the ip_address of this DHCPServerSetConfigurationRequestBody.


        :param ip_address: The ip_address of this DHCPServerSetConfigurationRequestBody.
        :type ip_address: str
        """

        self._ip_address = ip_address

    @property
    def network_mask(self) -> str:
        """Gets the network_mask of this DHCPServerSetConfigurationRequestBody.


        :return: The network_mask of this DHCPServerSetConfigurationRequestBody.
        :rtype: str
        """
        return self._network_mask

    @network_mask.setter
    def network_mask(self, network_mask: str):
        """Sets the network_mask of this DHCPServerSetConfigurationRequestBody.


        :param network_mask: The network_mask of this DHCPServerSetConfigurationRequestBody.
        :type network_mask: str
        """

        self._network_mask = network_mask

    @property
    def from_ip_address(self) -> str:
        """Gets the from_ip_address of this DHCPServerSetConfigurationRequestBody.


        :return: The from_ip_address of this DHCPServerSetConfigurationRequestBody.
        :rtype: str
        """
        return self._from_ip_address

    @from_ip_address.setter
    def from_ip_address(self, from_ip_address: str):
        """Sets the from_ip_address of this DHCPServerSetConfigurationRequestBody.


        :param from_ip_address: The from_ip_address of this DHCPServerSetConfigurationRequestBody.
        :type from_ip_address: str
        """

        self._from_ip_address = from_ip_address

    @property
    def to_ip_address(self) -> str:
        """Gets the to_ip_address of this DHCPServerSetConfigurationRequestBody.


        :return: The to_ip_address of this DHCPServerSetConfigurationRequestBody.
        :rtype: str
        """
        return self._to_ip_address

    @to_ip_address.setter
    def to_ip_address(self, to_ip_address: str):
        """Sets the to_ip_address of this DHCPServerSetConfigurationRequestBody.


        :param to_ip_address: The to_ip_address of this DHCPServerSetConfigurationRequestBody.
        :type to_ip_address: str
        """

        self._to_ip_address = to_ip_address
