# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401


from vbox_server.models.base_model_ import Model
from vbox_server.models.guest_os_type import GuestOSType
from vbox_server import util


class GuestOSTypeResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, type: GuestOSType=None):  # noqa: E501
        """GuestOSTypeResponse - a model defined in Swagger

        :param type: The type of this GuestOSTypeResponse.  # noqa: E501
        :type type: GuestOSType
        """
        self.swagger_types = {
            'type': GuestOSType
        }

        self.attribute_map = {
            'type': 'type'
        }

        self._type = type

    @classmethod
    def from_dict(cls, dikt) -> 'GuestOSTypeResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GuestOSType_response of this GuestOSTypeResponse.  # noqa: E501
        :rtype: GuestOSTypeResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def type(self) -> GuestOSType:
        """Gets the type of this GuestOSTypeResponse.


        :return: The type of this GuestOSTypeResponse.
        :rtype: GuestOSType
        """
        return self._type

    @type.setter
    def type(self, type: GuestOSType):
        """Sets the type of this GuestOSTypeResponse.


        :param type: The type of this GuestOSTypeResponse.
        :type type: GuestOSType
        """

        self._type = type
