# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401


from vbox_server.models.base_model_ import Model
from vbox_server import util


class GuestUserState(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    UNKNOWN = "UNKNOWN"
    LOGGEDIN = "LOGGEDIN"
    LOGGEDOUT = "LOGGEDOUT"
    LOCKED = "LOCKED"
    UNLOCKED = "UNLOCKED"
    DISABLED = "DISABLED"
    IDLE = "IDLE"
    INUSE = "INUSE"
    CREATED = "CREATED"
    DELETED = "DELETED"
    SESSIONCHANGED = "SESSIONCHANGED"
    CREDENTIALSCHANGED = "CREDENTIALSCHANGED"
    ROLECHANGED = "ROLECHANGED"
    GROUPADDED = "GROUPADDED"
    GROUPREMOVED = "GROUPREMOVED"
    ELEVATED = "ELEVATED"

    def __init__(self):  # noqa: E501
        """GuestUserState - a model defined in Swagger

        """
        self.swagger_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'GuestUserState':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GuestUserState of this GuestUserState.  # noqa: E501
        :rtype: GuestUserState
        """
        return util.deserialize_model(dikt, cls)
