# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401


from vbox_server.models.base_model_ import Model
from vbox_server.models.audio_codec_type import AudioCodecType
from vbox_server.models.audio_controller_type import AudioControllerType
from vbox_server.models.chipset_type import ChipsetType
from vbox_server.models.firmware_type import FirmwareType
from vbox_server.models.graphics_controller_type import GraphicsControllerType
from vbox_server.models.iommu_type import IommuType
from vbox_server.models.network_adapter_type import NetworkAdapterType
from vbox_server.models.platform_architecture import PlatformArchitecture
from vbox_server.models.storage_bus import StorageBus
from vbox_server.models.storage_controller_type import StorageControllerType
from vbox_server.models.tpm_type import TpmType
from vbox_server import util


class GuestOSType(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, family_id: str=None, family_description: str=None, id: str=None, subtype: str=None, description: str=None, is64_bit: bool=None, platform_architecture: PlatformArchitecture=None, recommended_ioapic: bool=None, recommended_virt_ex: bool=None, recommended_ram: int=None, recommended_graphics_controller: GraphicsControllerType=None, recommended_vram: int=None, recommended2_d_video_acceleration: bool=None, recommended3_d_acceleration: bool=None, recommended_hdd: int=None, adapter_type: NetworkAdapterType=None, recommended_pae: bool=None, recommended_dvd_storage_controller: StorageControllerType=None, recommended_dvd_storage_bus: StorageBus=None, recommended_hd_storage_controller: StorageControllerType=None, recommended_hd_storage_bus: StorageBus=None, recommended_firmware: FirmwareType=None, recommended_usbhid: bool=None, recommended_hpet: bool=None, recommended_usb_tablet: bool=None, recommended_rtc_use_utc: bool=None, recommended_chipset: ChipsetType=None, recommended_iommu_type: IommuType=None, recommended_audio_controller: AudioControllerType=None, recommended_audio_codec: AudioCodecType=None, recommended_floppy: bool=None, recommended_usb: bool=None, recommended_usb3: bool=None, recommended_tf_reset: bool=None, recommended_x2_apic: bool=None, recommended_cpu_count: int=None, recommended_tpm_type: TpmType=None, recommended_secure_boot: bool=None, recommended_wddm_graphics: bool=None, guest_additions_install_package_name: str=None):  # noqa: E501
        """GuestOSType - a model defined in Swagger

        :param family_id: The family_id of this GuestOSType.  # noqa: E501
        :type family_id: str
        :param family_description: The family_description of this GuestOSType.  # noqa: E501
        :type family_description: str
        :param id: The id of this GuestOSType.  # noqa: E501
        :type id: str
        :param subtype: The subtype of this GuestOSType.  # noqa: E501
        :type subtype: str
        :param description: The description of this GuestOSType.  # noqa: E501
        :type description: str
        :param is64_bit: The is64_bit of this GuestOSType.  # noqa: E501
        :type is64_bit: bool
        :param platform_architecture: The platform_architecture of this GuestOSType.  # noqa: E501
        :type platform_architecture: PlatformArchitecture
        :param recommended_ioapic: The recommended_ioapic of this GuestOSType.  # noqa: E501
        :type recommended_ioapic: bool
        :param recommended_virt_ex: The recommended_virt_ex of this GuestOSType.  # noqa: E501
        :type recommended_virt_ex: bool
        :param recommended_ram: The recommended_ram of this GuestOSType.  # noqa: E501
        :type recommended_ram: int
        :param recommended_graphics_controller: The recommended_graphics_controller of this GuestOSType.  # noqa: E501
        :type recommended_graphics_controller: GraphicsControllerType
        :param recommended_vram: The recommended_vram of this GuestOSType.  # noqa: E501
        :type recommended_vram: int
        :param recommended2_d_video_acceleration: The recommended2_d_video_acceleration of this GuestOSType.  # noqa: E501
        :type recommended2_d_video_acceleration: bool
        :param recommended3_d_acceleration: The recommended3_d_acceleration of this GuestOSType.  # noqa: E501
        :type recommended3_d_acceleration: bool
        :param recommended_hdd: The recommended_hdd of this GuestOSType.  # noqa: E501
        :type recommended_hdd: int
        :param adapter_type: The adapter_type of this GuestOSType.  # noqa: E501
        :type adapter_type: NetworkAdapterType
        :param recommended_pae: The recommended_pae of this GuestOSType.  # noqa: E501
        :type recommended_pae: bool
        :param recommended_dvd_storage_controller: The recommended_dvd_storage_controller of this GuestOSType.  # noqa: E501
        :type recommended_dvd_storage_controller: StorageControllerType
        :param recommended_dvd_storage_bus: The recommended_dvd_storage_bus of this GuestOSType.  # noqa: E501
        :type recommended_dvd_storage_bus: StorageBus
        :param recommended_hd_storage_controller: The recommended_hd_storage_controller of this GuestOSType.  # noqa: E501
        :type recommended_hd_storage_controller: StorageControllerType
        :param recommended_hd_storage_bus: The recommended_hd_storage_bus of this GuestOSType.  # noqa: E501
        :type recommended_hd_storage_bus: StorageBus
        :param recommended_firmware: The recommended_firmware of this GuestOSType.  # noqa: E501
        :type recommended_firmware: FirmwareType
        :param recommended_usbhid: The recommended_usbhid of this GuestOSType.  # noqa: E501
        :type recommended_usbhid: bool
        :param recommended_hpet: The recommended_hpet of this GuestOSType.  # noqa: E501
        :type recommended_hpet: bool
        :param recommended_usb_tablet: The recommended_usb_tablet of this GuestOSType.  # noqa: E501
        :type recommended_usb_tablet: bool
        :param recommended_rtc_use_utc: The recommended_rtc_use_utc of this GuestOSType.  # noqa: E501
        :type recommended_rtc_use_utc: bool
        :param recommended_chipset: The recommended_chipset of this GuestOSType.  # noqa: E501
        :type recommended_chipset: ChipsetType
        :param recommended_iommu_type: The recommended_iommu_type of this GuestOSType.  # noqa: E501
        :type recommended_iommu_type: IommuType
        :param recommended_audio_controller: The recommended_audio_controller of this GuestOSType.  # noqa: E501
        :type recommended_audio_controller: AudioControllerType
        :param recommended_audio_codec: The recommended_audio_codec of this GuestOSType.  # noqa: E501
        :type recommended_audio_codec: AudioCodecType
        :param recommended_floppy: The recommended_floppy of this GuestOSType.  # noqa: E501
        :type recommended_floppy: bool
        :param recommended_usb: The recommended_usb of this GuestOSType.  # noqa: E501
        :type recommended_usb: bool
        :param recommended_usb3: The recommended_usb3 of this GuestOSType.  # noqa: E501
        :type recommended_usb3: bool
        :param recommended_tf_reset: The recommended_tf_reset of this GuestOSType.  # noqa: E501
        :type recommended_tf_reset: bool
        :param recommended_x2_apic: The recommended_x2_apic of this GuestOSType.  # noqa: E501
        :type recommended_x2_apic: bool
        :param recommended_cpu_count: The recommended_cpu_count of this GuestOSType.  # noqa: E501
        :type recommended_cpu_count: int
        :param recommended_tpm_type: The recommended_tpm_type of this GuestOSType.  # noqa: E501
        :type recommended_tpm_type: TpmType
        :param recommended_secure_boot: The recommended_secure_boot of this GuestOSType.  # noqa: E501
        :type recommended_secure_boot: bool
        :param recommended_wddm_graphics: The recommended_wddm_graphics of this GuestOSType.  # noqa: E501
        :type recommended_wddm_graphics: bool
        :param guest_additions_install_package_name: The guest_additions_install_package_name of this GuestOSType.  # noqa: E501
        :type guest_additions_install_package_name: str
        """
        self.swagger_types = {
            'family_id': str,
            'family_description': str,
            'id': str,
            'subtype': str,
            'description': str,
            'is64_bit': bool,
            'platform_architecture': PlatformArchitecture,
            'recommended_ioapic': bool,
            'recommended_virt_ex': bool,
            'recommended_ram': int,
            'recommended_graphics_controller': GraphicsControllerType,
            'recommended_vram': int,
            'recommended2_d_video_acceleration': bool,
            'recommended3_d_acceleration': bool,
            'recommended_hdd': int,
            'adapter_type': NetworkAdapterType,
            'recommended_pae': bool,
            'recommended_dvd_storage_controller': StorageControllerType,
            'recommended_dvd_storage_bus': StorageBus,
            'recommended_hd_storage_controller': StorageControllerType,
            'recommended_hd_storage_bus': StorageBus,
            'recommended_firmware': FirmwareType,
            'recommended_usbhid': bool,
            'recommended_hpet': bool,
            'recommended_usb_tablet': bool,
            'recommended_rtc_use_utc': bool,
            'recommended_chipset': ChipsetType,
            'recommended_iommu_type': IommuType,
            'recommended_audio_controller': AudioControllerType,
            'recommended_audio_codec': AudioCodecType,
            'recommended_floppy': bool,
            'recommended_usb': bool,
            'recommended_usb3': bool,
            'recommended_tf_reset': bool,
            'recommended_x2_apic': bool,
            'recommended_cpu_count': int,
            'recommended_tpm_type': TpmType,
            'recommended_secure_boot': bool,
            'recommended_wddm_graphics': bool,
            'guest_additions_install_package_name': str
        }

        self.attribute_map = {
            'family_id': 'familyId',
            'family_description': 'familyDescription',
            'id': 'id',
            'subtype': 'subtype',
            'description': 'description',
            'is64_bit': 'is64Bit',
            'platform_architecture': 'platformArchitecture',
            'recommended_ioapic': 'recommendedIOAPIC',
            'recommended_virt_ex': 'recommendedVirtEx',
            'recommended_ram': 'recommendedRAM',
            'recommended_graphics_controller': 'recommendedGraphicsController',
            'recommended_vram': 'recommendedVRAM',
            'recommended2_d_video_acceleration': 'recommended2DVideoAcceleration',
            'recommended3_d_acceleration': 'recommended3DAcceleration',
            'recommended_hdd': 'recommendedHDD',
            'adapter_type': 'adapterType',
            'recommended_pae': 'recommendedPAE',
            'recommended_dvd_storage_controller': 'recommendedDVDStorageController',
            'recommended_dvd_storage_bus': 'recommendedDVDStorageBus',
            'recommended_hd_storage_controller': 'recommendedHDStorageController',
            'recommended_hd_storage_bus': 'recommendedHDStorageBus',
            'recommended_firmware': 'recommendedFirmware',
            'recommended_usbhid': 'recommendedUSBHID',
            'recommended_hpet': 'recommendedHPET',
            'recommended_usb_tablet': 'recommendedUSBTablet',
            'recommended_rtc_use_utc': 'recommendedRTCUseUTC',
            'recommended_chipset': 'recommendedChipset',
            'recommended_iommu_type': 'recommendedIommuType',
            'recommended_audio_controller': 'recommendedAudioController',
            'recommended_audio_codec': 'recommendedAudioCodec',
            'recommended_floppy': 'recommendedFloppy',
            'recommended_usb': 'recommendedUSB',
            'recommended_usb3': 'recommendedUSB3',
            'recommended_tf_reset': 'recommendedTFReset',
            'recommended_x2_apic': 'recommendedX2APIC',
            'recommended_cpu_count': 'recommendedCPUCount',
            'recommended_tpm_type': 'recommendedTpmType',
            'recommended_secure_boot': 'recommendedSecureBoot',
            'recommended_wddm_graphics': 'recommendedWDDMGraphics',
            'guest_additions_install_package_name': 'guestAdditionsInstallPackageName'
        }

        self._family_id = family_id
        self._family_description = family_description
        self._id = id
        self._subtype = subtype
        self._description = description
        self._is64_bit = is64_bit
        self._platform_architecture = platform_architecture
        self._recommended_ioapic = recommended_ioapic
        self._recommended_virt_ex = recommended_virt_ex
        self._recommended_ram = recommended_ram
        self._recommended_graphics_controller = recommended_graphics_controller
        self._recommended_vram = recommended_vram
        self._recommended2_d_video_acceleration = recommended2_d_video_acceleration
        self._recommended3_d_acceleration = recommended3_d_acceleration
        self._recommended_hdd = recommended_hdd
        self._adapter_type = adapter_type
        self._recommended_pae = recommended_pae
        self._recommended_dvd_storage_controller = recommended_dvd_storage_controller
        self._recommended_dvd_storage_bus = recommended_dvd_storage_bus
        self._recommended_hd_storage_controller = recommended_hd_storage_controller
        self._recommended_hd_storage_bus = recommended_hd_storage_bus
        self._recommended_firmware = recommended_firmware
        self._recommended_usbhid = recommended_usbhid
        self._recommended_hpet = recommended_hpet
        self._recommended_usb_tablet = recommended_usb_tablet
        self._recommended_rtc_use_utc = recommended_rtc_use_utc
        self._recommended_chipset = recommended_chipset
        self._recommended_iommu_type = recommended_iommu_type
        self._recommended_audio_controller = recommended_audio_controller
        self._recommended_audio_codec = recommended_audio_codec
        self._recommended_floppy = recommended_floppy
        self._recommended_usb = recommended_usb
        self._recommended_usb3 = recommended_usb3
        self._recommended_tf_reset = recommended_tf_reset
        self._recommended_x2_apic = recommended_x2_apic
        self._recommended_cpu_count = recommended_cpu_count
        self._recommended_tpm_type = recommended_tpm_type
        self._recommended_secure_boot = recommended_secure_boot
        self._recommended_wddm_graphics = recommended_wddm_graphics
        self._guest_additions_install_package_name = guest_additions_install_package_name

    @classmethod
    def from_dict(cls, dikt) -> 'GuestOSType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GuestOSType of this GuestOSType.  # noqa: E501
        :rtype: GuestOSType
        """
        return util.deserialize_model(dikt, cls)

    @property
    def family_id(self) -> str:
        """Gets the family_id of this GuestOSType.


        :return: The family_id of this GuestOSType.
        :rtype: str
        """
        return self._family_id

    @family_id.setter
    def family_id(self, family_id: str):
        """Sets the family_id of this GuestOSType.


        :param family_id: The family_id of this GuestOSType.
        :type family_id: str
        """

        self._family_id = family_id

    @property
    def family_description(self) -> str:
        """Gets the family_description of this GuestOSType.


        :return: The family_description of this GuestOSType.
        :rtype: str
        """
        return self._family_description

    @family_description.setter
    def family_description(self, family_description: str):
        """Sets the family_description of this GuestOSType.


        :param family_description: The family_description of this GuestOSType.
        :type family_description: str
        """

        self._family_description = family_description

    @property
    def id(self) -> str:
        """Gets the id of this GuestOSType.


        :return: The id of this GuestOSType.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this GuestOSType.


        :param id: The id of this GuestOSType.
        :type id: str
        """

        self._id = id

    @property
    def subtype(self) -> str:
        """Gets the subtype of this GuestOSType.


        :return: The subtype of this GuestOSType.
        :rtype: str
        """
        return self._subtype

    @subtype.setter
    def subtype(self, subtype: str):
        """Sets the subtype of this GuestOSType.


        :param subtype: The subtype of this GuestOSType.
        :type subtype: str
        """

        self._subtype = subtype

    @property
    def description(self) -> str:
        """Gets the description of this GuestOSType.


        :return: The description of this GuestOSType.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this GuestOSType.


        :param description: The description of this GuestOSType.
        :type description: str
        """

        self._description = description

    @property
    def is64_bit(self) -> bool:
        """Gets the is64_bit of this GuestOSType.


        :return: The is64_bit of this GuestOSType.
        :rtype: bool
        """
        return self._is64_bit

    @is64_bit.setter
    def is64_bit(self, is64_bit: bool):
        """Sets the is64_bit of this GuestOSType.


        :param is64_bit: The is64_bit of this GuestOSType.
        :type is64_bit: bool
        """

        self._is64_bit = is64_bit

    @property
    def platform_architecture(self) -> PlatformArchitecture:
        """Gets the platform_architecture of this GuestOSType.


        :return: The platform_architecture of this GuestOSType.
        :rtype: PlatformArchitecture
        """
        return self._platform_architecture

    @platform_architecture.setter
    def platform_architecture(self, platform_architecture: PlatformArchitecture):
        """Sets the platform_architecture of this GuestOSType.


        :param platform_architecture: The platform_architecture of this GuestOSType.
        :type platform_architecture: PlatformArchitecture
        """

        self._platform_architecture = platform_architecture

    @property
    def recommended_ioapic(self) -> bool:
        """Gets the recommended_ioapic of this GuestOSType.


        :return: The recommended_ioapic of this GuestOSType.
        :rtype: bool
        """
        return self._recommended_ioapic

    @recommended_ioapic.setter
    def recommended_ioapic(self, recommended_ioapic: bool):
        """Sets the recommended_ioapic of this GuestOSType.


        :param recommended_ioapic: The recommended_ioapic of this GuestOSType.
        :type recommended_ioapic: bool
        """

        self._recommended_ioapic = recommended_ioapic

    @property
    def recommended_virt_ex(self) -> bool:
        """Gets the recommended_virt_ex of this GuestOSType.


        :return: The recommended_virt_ex of this GuestOSType.
        :rtype: bool
        """
        return self._recommended_virt_ex

    @recommended_virt_ex.setter
    def recommended_virt_ex(self, recommended_virt_ex: bool):
        """Sets the recommended_virt_ex of this GuestOSType.


        :param recommended_virt_ex: The recommended_virt_ex of this GuestOSType.
        :type recommended_virt_ex: bool
        """

        self._recommended_virt_ex = recommended_virt_ex

    @property
    def recommended_ram(self) -> int:
        """Gets the recommended_ram of this GuestOSType.


        :return: The recommended_ram of this GuestOSType.
        :rtype: int
        """
        return self._recommended_ram

    @recommended_ram.setter
    def recommended_ram(self, recommended_ram: int):
        """Sets the recommended_ram of this GuestOSType.


        :param recommended_ram: The recommended_ram of this GuestOSType.
        :type recommended_ram: int
        """

        self._recommended_ram = recommended_ram

    @property
    def recommended_graphics_controller(self) -> GraphicsControllerType:
        """Gets the recommended_graphics_controller of this GuestOSType.


        :return: The recommended_graphics_controller of this GuestOSType.
        :rtype: GraphicsControllerType
        """
        return self._recommended_graphics_controller

    @recommended_graphics_controller.setter
    def recommended_graphics_controller(self, recommended_graphics_controller: GraphicsControllerType):
        """Sets the recommended_graphics_controller of this GuestOSType.


        :param recommended_graphics_controller: The recommended_graphics_controller of this GuestOSType.
        :type recommended_graphics_controller: GraphicsControllerType
        """

        self._recommended_graphics_controller = recommended_graphics_controller

    @property
    def recommended_vram(self) -> int:
        """Gets the recommended_vram of this GuestOSType.


        :return: The recommended_vram of this GuestOSType.
        :rtype: int
        """
        return self._recommended_vram

    @recommended_vram.setter
    def recommended_vram(self, recommended_vram: int):
        """Sets the recommended_vram of this GuestOSType.


        :param recommended_vram: The recommended_vram of this GuestOSType.
        :type recommended_vram: int
        """

        self._recommended_vram = recommended_vram

    @property
    def recommended2_d_video_acceleration(self) -> bool:
        """Gets the recommended2_d_video_acceleration of this GuestOSType.


        :return: The recommended2_d_video_acceleration of this GuestOSType.
        :rtype: bool
        """
        return self._recommended2_d_video_acceleration

    @recommended2_d_video_acceleration.setter
    def recommended2_d_video_acceleration(self, recommended2_d_video_acceleration: bool):
        """Sets the recommended2_d_video_acceleration of this GuestOSType.


        :param recommended2_d_video_acceleration: The recommended2_d_video_acceleration of this GuestOSType.
        :type recommended2_d_video_acceleration: bool
        """

        self._recommended2_d_video_acceleration = recommended2_d_video_acceleration

    @property
    def recommended3_d_acceleration(self) -> bool:
        """Gets the recommended3_d_acceleration of this GuestOSType.


        :return: The recommended3_d_acceleration of this GuestOSType.
        :rtype: bool
        """
        return self._recommended3_d_acceleration

    @recommended3_d_acceleration.setter
    def recommended3_d_acceleration(self, recommended3_d_acceleration: bool):
        """Sets the recommended3_d_acceleration of this GuestOSType.


        :param recommended3_d_acceleration: The recommended3_d_acceleration of this GuestOSType.
        :type recommended3_d_acceleration: bool
        """

        self._recommended3_d_acceleration = recommended3_d_acceleration

    @property
    def recommended_hdd(self) -> int:
        """Gets the recommended_hdd of this GuestOSType.


        :return: The recommended_hdd of this GuestOSType.
        :rtype: int
        """
        return self._recommended_hdd

    @recommended_hdd.setter
    def recommended_hdd(self, recommended_hdd: int):
        """Sets the recommended_hdd of this GuestOSType.


        :param recommended_hdd: The recommended_hdd of this GuestOSType.
        :type recommended_hdd: int
        """

        self._recommended_hdd = recommended_hdd

    @property
    def adapter_type(self) -> NetworkAdapterType:
        """Gets the adapter_type of this GuestOSType.


        :return: The adapter_type of this GuestOSType.
        :rtype: NetworkAdapterType
        """
        return self._adapter_type

    @adapter_type.setter
    def adapter_type(self, adapter_type: NetworkAdapterType):
        """Sets the adapter_type of this GuestOSType.


        :param adapter_type: The adapter_type of this GuestOSType.
        :type adapter_type: NetworkAdapterType
        """

        self._adapter_type = adapter_type

    @property
    def recommended_pae(self) -> bool:
        """Gets the recommended_pae of this GuestOSType.


        :return: The recommended_pae of this GuestOSType.
        :rtype: bool
        """
        return self._recommended_pae

    @recommended_pae.setter
    def recommended_pae(self, recommended_pae: bool):
        """Sets the recommended_pae of this GuestOSType.


        :param recommended_pae: The recommended_pae of this GuestOSType.
        :type recommended_pae: bool
        """

        self._recommended_pae = recommended_pae

    @property
    def recommended_dvd_storage_controller(self) -> StorageControllerType:
        """Gets the recommended_dvd_storage_controller of this GuestOSType.


        :return: The recommended_dvd_storage_controller of this GuestOSType.
        :rtype: StorageControllerType
        """
        return self._recommended_dvd_storage_controller

    @recommended_dvd_storage_controller.setter
    def recommended_dvd_storage_controller(self, recommended_dvd_storage_controller: StorageControllerType):
        """Sets the recommended_dvd_storage_controller of this GuestOSType.


        :param recommended_dvd_storage_controller: The recommended_dvd_storage_controller of this GuestOSType.
        :type recommended_dvd_storage_controller: StorageControllerType
        """

        self._recommended_dvd_storage_controller = recommended_dvd_storage_controller

    @property
    def recommended_dvd_storage_bus(self) -> StorageBus:
        """Gets the recommended_dvd_storage_bus of this GuestOSType.


        :return: The recommended_dvd_storage_bus of this GuestOSType.
        :rtype: StorageBus
        """
        return self._recommended_dvd_storage_bus

    @recommended_dvd_storage_bus.setter
    def recommended_dvd_storage_bus(self, recommended_dvd_storage_bus: StorageBus):
        """Sets the recommended_dvd_storage_bus of this GuestOSType.


        :param recommended_dvd_storage_bus: The recommended_dvd_storage_bus of this GuestOSType.
        :type recommended_dvd_storage_bus: StorageBus
        """

        self._recommended_dvd_storage_bus = recommended_dvd_storage_bus

    @property
    def recommended_hd_storage_controller(self) -> StorageControllerType:
        """Gets the recommended_hd_storage_controller of this GuestOSType.


        :return: The recommended_hd_storage_controller of this GuestOSType.
        :rtype: StorageControllerType
        """
        return self._recommended_hd_storage_controller

    @recommended_hd_storage_controller.setter
    def recommended_hd_storage_controller(self, recommended_hd_storage_controller: StorageControllerType):
        """Sets the recommended_hd_storage_controller of this GuestOSType.


        :param recommended_hd_storage_controller: The recommended_hd_storage_controller of this GuestOSType.
        :type recommended_hd_storage_controller: StorageControllerType
        """

        self._recommended_hd_storage_controller = recommended_hd_storage_controller

    @property
    def recommended_hd_storage_bus(self) -> StorageBus:
        """Gets the recommended_hd_storage_bus of this GuestOSType.


        :return: The recommended_hd_storage_bus of this GuestOSType.
        :rtype: StorageBus
        """
        return self._recommended_hd_storage_bus

    @recommended_hd_storage_bus.setter
    def recommended_hd_storage_bus(self, recommended_hd_storage_bus: StorageBus):
        """Sets the recommended_hd_storage_bus of this GuestOSType.


        :param recommended_hd_storage_bus: The recommended_hd_storage_bus of this GuestOSType.
        :type recommended_hd_storage_bus: StorageBus
        """

        self._recommended_hd_storage_bus = recommended_hd_storage_bus

    @property
    def recommended_firmware(self) -> FirmwareType:
        """Gets the recommended_firmware of this GuestOSType.


        :return: The recommended_firmware of this GuestOSType.
        :rtype: FirmwareType
        """
        return self._recommended_firmware

    @recommended_firmware.setter
    def recommended_firmware(self, recommended_firmware: FirmwareType):
        """Sets the recommended_firmware of this GuestOSType.


        :param recommended_firmware: The recommended_firmware of this GuestOSType.
        :type recommended_firmware: FirmwareType
        """

        self._recommended_firmware = recommended_firmware

    @property
    def recommended_usbhid(self) -> bool:
        """Gets the recommended_usbhid of this GuestOSType.


        :return: The recommended_usbhid of this GuestOSType.
        :rtype: bool
        """
        return self._recommended_usbhid

    @recommended_usbhid.setter
    def recommended_usbhid(self, recommended_usbhid: bool):
        """Sets the recommended_usbhid of this GuestOSType.


        :param recommended_usbhid: The recommended_usbhid of this GuestOSType.
        :type recommended_usbhid: bool
        """

        self._recommended_usbhid = recommended_usbhid

    @property
    def recommended_hpet(self) -> bool:
        """Gets the recommended_hpet of this GuestOSType.


        :return: The recommended_hpet of this GuestOSType.
        :rtype: bool
        """
        return self._recommended_hpet

    @recommended_hpet.setter
    def recommended_hpet(self, recommended_hpet: bool):
        """Sets the recommended_hpet of this GuestOSType.


        :param recommended_hpet: The recommended_hpet of this GuestOSType.
        :type recommended_hpet: bool
        """

        self._recommended_hpet = recommended_hpet

    @property
    def recommended_usb_tablet(self) -> bool:
        """Gets the recommended_usb_tablet of this GuestOSType.


        :return: The recommended_usb_tablet of this GuestOSType.
        :rtype: bool
        """
        return self._recommended_usb_tablet

    @recommended_usb_tablet.setter
    def recommended_usb_tablet(self, recommended_usb_tablet: bool):
        """Sets the recommended_usb_tablet of this GuestOSType.


        :param recommended_usb_tablet: The recommended_usb_tablet of this GuestOSType.
        :type recommended_usb_tablet: bool
        """

        self._recommended_usb_tablet = recommended_usb_tablet

    @property
    def recommended_rtc_use_utc(self) -> bool:
        """Gets the recommended_rtc_use_utc of this GuestOSType.


        :return: The recommended_rtc_use_utc of this GuestOSType.
        :rtype: bool
        """
        return self._recommended_rtc_use_utc

    @recommended_rtc_use_utc.setter
    def recommended_rtc_use_utc(self, recommended_rtc_use_utc: bool):
        """Sets the recommended_rtc_use_utc of this GuestOSType.


        :param recommended_rtc_use_utc: The recommended_rtc_use_utc of this GuestOSType.
        :type recommended_rtc_use_utc: bool
        """

        self._recommended_rtc_use_utc = recommended_rtc_use_utc

    @property
    def recommended_chipset(self) -> ChipsetType:
        """Gets the recommended_chipset of this GuestOSType.


        :return: The recommended_chipset of this GuestOSType.
        :rtype: ChipsetType
        """
        return self._recommended_chipset

    @recommended_chipset.setter
    def recommended_chipset(self, recommended_chipset: ChipsetType):
        """Sets the recommended_chipset of this GuestOSType.


        :param recommended_chipset: The recommended_chipset of this GuestOSType.
        :type recommended_chipset: ChipsetType
        """

        self._recommended_chipset = recommended_chipset

    @property
    def recommended_iommu_type(self) -> IommuType:
        """Gets the recommended_iommu_type of this GuestOSType.


        :return: The recommended_iommu_type of this GuestOSType.
        :rtype: IommuType
        """
        return self._recommended_iommu_type

    @recommended_iommu_type.setter
    def recommended_iommu_type(self, recommended_iommu_type: IommuType):
        """Sets the recommended_iommu_type of this GuestOSType.


        :param recommended_iommu_type: The recommended_iommu_type of this GuestOSType.
        :type recommended_iommu_type: IommuType
        """

        self._recommended_iommu_type = recommended_iommu_type

    @property
    def recommended_audio_controller(self) -> AudioControllerType:
        """Gets the recommended_audio_controller of this GuestOSType.


        :return: The recommended_audio_controller of this GuestOSType.
        :rtype: AudioControllerType
        """
        return self._recommended_audio_controller

    @recommended_audio_controller.setter
    def recommended_audio_controller(self, recommended_audio_controller: AudioControllerType):
        """Sets the recommended_audio_controller of this GuestOSType.


        :param recommended_audio_controller: The recommended_audio_controller of this GuestOSType.
        :type recommended_audio_controller: AudioControllerType
        """

        self._recommended_audio_controller = recommended_audio_controller

    @property
    def recommended_audio_codec(self) -> AudioCodecType:
        """Gets the recommended_audio_codec of this GuestOSType.


        :return: The recommended_audio_codec of this GuestOSType.
        :rtype: AudioCodecType
        """
        return self._recommended_audio_codec

    @recommended_audio_codec.setter
    def recommended_audio_codec(self, recommended_audio_codec: AudioCodecType):
        """Sets the recommended_audio_codec of this GuestOSType.


        :param recommended_audio_codec: The recommended_audio_codec of this GuestOSType.
        :type recommended_audio_codec: AudioCodecType
        """

        self._recommended_audio_codec = recommended_audio_codec

    @property
    def recommended_floppy(self) -> bool:
        """Gets the recommended_floppy of this GuestOSType.


        :return: The recommended_floppy of this GuestOSType.
        :rtype: bool
        """
        return self._recommended_floppy

    @recommended_floppy.setter
    def recommended_floppy(self, recommended_floppy: bool):
        """Sets the recommended_floppy of this GuestOSType.


        :param recommended_floppy: The recommended_floppy of this GuestOSType.
        :type recommended_floppy: bool
        """

        self._recommended_floppy = recommended_floppy

    @property
    def recommended_usb(self) -> bool:
        """Gets the recommended_usb of this GuestOSType.


        :return: The recommended_usb of this GuestOSType.
        :rtype: bool
        """
        return self._recommended_usb

    @recommended_usb.setter
    def recommended_usb(self, recommended_usb: bool):
        """Sets the recommended_usb of this GuestOSType.


        :param recommended_usb: The recommended_usb of this GuestOSType.
        :type recommended_usb: bool
        """

        self._recommended_usb = recommended_usb

    @property
    def recommended_usb3(self) -> bool:
        """Gets the recommended_usb3 of this GuestOSType.


        :return: The recommended_usb3 of this GuestOSType.
        :rtype: bool
        """
        return self._recommended_usb3

    @recommended_usb3.setter
    def recommended_usb3(self, recommended_usb3: bool):
        """Sets the recommended_usb3 of this GuestOSType.


        :param recommended_usb3: The recommended_usb3 of this GuestOSType.
        :type recommended_usb3: bool
        """

        self._recommended_usb3 = recommended_usb3

    @property
    def recommended_tf_reset(self) -> bool:
        """Gets the recommended_tf_reset of this GuestOSType.


        :return: The recommended_tf_reset of this GuestOSType.
        :rtype: bool
        """
        return self._recommended_tf_reset

    @recommended_tf_reset.setter
    def recommended_tf_reset(self, recommended_tf_reset: bool):
        """Sets the recommended_tf_reset of this GuestOSType.


        :param recommended_tf_reset: The recommended_tf_reset of this GuestOSType.
        :type recommended_tf_reset: bool
        """

        self._recommended_tf_reset = recommended_tf_reset

    @property
    def recommended_x2_apic(self) -> bool:
        """Gets the recommended_x2_apic of this GuestOSType.


        :return: The recommended_x2_apic of this GuestOSType.
        :rtype: bool
        """
        return self._recommended_x2_apic

    @recommended_x2_apic.setter
    def recommended_x2_apic(self, recommended_x2_apic: bool):
        """Sets the recommended_x2_apic of this GuestOSType.


        :param recommended_x2_apic: The recommended_x2_apic of this GuestOSType.
        :type recommended_x2_apic: bool
        """

        self._recommended_x2_apic = recommended_x2_apic

    @property
    def recommended_cpu_count(self) -> int:
        """Gets the recommended_cpu_count of this GuestOSType.


        :return: The recommended_cpu_count of this GuestOSType.
        :rtype: int
        """
        return self._recommended_cpu_count

    @recommended_cpu_count.setter
    def recommended_cpu_count(self, recommended_cpu_count: int):
        """Sets the recommended_cpu_count of this GuestOSType.


        :param recommended_cpu_count: The recommended_cpu_count of this GuestOSType.
        :type recommended_cpu_count: int
        """

        self._recommended_cpu_count = recommended_cpu_count

    @property
    def recommended_tpm_type(self) -> TpmType:
        """Gets the recommended_tpm_type of this GuestOSType.


        :return: The recommended_tpm_type of this GuestOSType.
        :rtype: TpmType
        """
        return self._recommended_tpm_type

    @recommended_tpm_type.setter
    def recommended_tpm_type(self, recommended_tpm_type: TpmType):
        """Sets the recommended_tpm_type of this GuestOSType.


        :param recommended_tpm_type: The recommended_tpm_type of this GuestOSType.
        :type recommended_tpm_type: TpmType
        """

        self._recommended_tpm_type = recommended_tpm_type

    @property
    def recommended_secure_boot(self) -> bool:
        """Gets the recommended_secure_boot of this GuestOSType.


        :return: The recommended_secure_boot of this GuestOSType.
        :rtype: bool
        """
        return self._recommended_secure_boot

    @recommended_secure_boot.setter
    def recommended_secure_boot(self, recommended_secure_boot: bool):
        """Sets the recommended_secure_boot of this GuestOSType.


        :param recommended_secure_boot: The recommended_secure_boot of this GuestOSType.
        :type recommended_secure_boot: bool
        """

        self._recommended_secure_boot = recommended_secure_boot

    @property
    def recommended_wddm_graphics(self) -> bool:
        """Gets the recommended_wddm_graphics of this GuestOSType.


        :return: The recommended_wddm_graphics of this GuestOSType.
        :rtype: bool
        """
        return self._recommended_wddm_graphics

    @recommended_wddm_graphics.setter
    def recommended_wddm_graphics(self, recommended_wddm_graphics: bool):
        """Sets the recommended_wddm_graphics of this GuestOSType.


        :param recommended_wddm_graphics: The recommended_wddm_graphics of this GuestOSType.
        :type recommended_wddm_graphics: bool
        """

        self._recommended_wddm_graphics = recommended_wddm_graphics

    @property
    def guest_additions_install_package_name(self) -> str:
        """Gets the guest_additions_install_package_name of this GuestOSType.


        :return: The guest_additions_install_package_name of this GuestOSType.
        :rtype: str
        """
        return self._guest_additions_install_package_name

    @guest_additions_install_package_name.setter
    def guest_additions_install_package_name(self, guest_additions_install_package_name: str):
        """Sets the guest_additions_install_package_name of this GuestOSType.


        :param guest_additions_install_package_name: The guest_additions_install_package_name of this GuestOSType.
        :type guest_additions_install_package_name: str
        """

        self._guest_additions_install_package_name = guest_additions_install_package_name
