# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401


from vbox_server.models.base_model_ import Model
from vbox_server import util


class HostOnlyNetwork(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, network_name: str=None, enabled: bool=None, network_mask: str=None, host_ip: str=None, lower_ip: str=None, upper_ip: str=None, id: str=None):  # noqa: E501
        """HostOnlyNetwork - a model defined in Swagger

        :param network_name: The network_name of this HostOnlyNetwork.  # noqa: E501
        :type network_name: str
        :param enabled: The enabled of this HostOnlyNetwork.  # noqa: E501
        :type enabled: bool
        :param network_mask: The network_mask of this HostOnlyNetwork.  # noqa: E501
        :type network_mask: str
        :param host_ip: The host_ip of this HostOnlyNetwork.  # noqa: E501
        :type host_ip: str
        :param lower_ip: The lower_ip of this HostOnlyNetwork.  # noqa: E501
        :type lower_ip: str
        :param upper_ip: The upper_ip of this HostOnlyNetwork.  # noqa: E501
        :type upper_ip: str
        :param id: The id of this HostOnlyNetwork.  # noqa: E501
        :type id: str
        """
        self.swagger_types = {
            'network_name': str,
            'enabled': bool,
            'network_mask': str,
            'host_ip': str,
            'lower_ip': str,
            'upper_ip': str,
            'id': str
        }

        self.attribute_map = {
            'network_name': 'networkName',
            'enabled': 'enabled',
            'network_mask': 'networkMask',
            'host_ip': 'hostIP',
            'lower_ip': 'lowerIP',
            'upper_ip': 'upperIP',
            'id': 'id'
        }

        self._network_name = network_name
        self._enabled = enabled
        self._network_mask = network_mask
        self._host_ip = host_ip
        self._lower_ip = lower_ip
        self._upper_ip = upper_ip
        self._id = id

    @classmethod
    def from_dict(cls, dikt) -> 'HostOnlyNetwork':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The HostOnlyNetwork of this HostOnlyNetwork.  # noqa: E501
        :rtype: HostOnlyNetwork
        """
        return util.deserialize_model(dikt, cls)

    @property
    def network_name(self) -> str:
        """Gets the network_name of this HostOnlyNetwork.


        :return: The network_name of this HostOnlyNetwork.
        :rtype: str
        """
        return self._network_name

    @network_name.setter
    def network_name(self, network_name: str):
        """Sets the network_name of this HostOnlyNetwork.


        :param network_name: The network_name of this HostOnlyNetwork.
        :type network_name: str
        """

        self._network_name = network_name

    @property
    def enabled(self) -> bool:
        """Gets the enabled of this HostOnlyNetwork.


        :return: The enabled of this HostOnlyNetwork.
        :rtype: bool
        """
        return self._enabled

    @enabled.setter
    def enabled(self, enabled: bool):
        """Sets the enabled of this HostOnlyNetwork.


        :param enabled: The enabled of this HostOnlyNetwork.
        :type enabled: bool
        """

        self._enabled = enabled

    @property
    def network_mask(self) -> str:
        """Gets the network_mask of this HostOnlyNetwork.


        :return: The network_mask of this HostOnlyNetwork.
        :rtype: str
        """
        return self._network_mask

    @network_mask.setter
    def network_mask(self, network_mask: str):
        """Sets the network_mask of this HostOnlyNetwork.


        :param network_mask: The network_mask of this HostOnlyNetwork.
        :type network_mask: str
        """

        self._network_mask = network_mask

    @property
    def host_ip(self) -> str:
        """Gets the host_ip of this HostOnlyNetwork.


        :return: The host_ip of this HostOnlyNetwork.
        :rtype: str
        """
        return self._host_ip

    @host_ip.setter
    def host_ip(self, host_ip: str):
        """Sets the host_ip of this HostOnlyNetwork.


        :param host_ip: The host_ip of this HostOnlyNetwork.
        :type host_ip: str
        """

        self._host_ip = host_ip

    @property
    def lower_ip(self) -> str:
        """Gets the lower_ip of this HostOnlyNetwork.


        :return: The lower_ip of this HostOnlyNetwork.
        :rtype: str
        """
        return self._lower_ip

    @lower_ip.setter
    def lower_ip(self, lower_ip: str):
        """Sets the lower_ip of this HostOnlyNetwork.


        :param lower_ip: The lower_ip of this HostOnlyNetwork.
        :type lower_ip: str
        """

        self._lower_ip = lower_ip

    @property
    def upper_ip(self) -> str:
        """Gets the upper_ip of this HostOnlyNetwork.


        :return: The upper_ip of this HostOnlyNetwork.
        :rtype: str
        """
        return self._upper_ip

    @upper_ip.setter
    def upper_ip(self, upper_ip: str):
        """Sets the upper_ip of this HostOnlyNetwork.


        :param upper_ip: The upper_ip of this HostOnlyNetwork.
        :type upper_ip: str
        """

        self._upper_ip = upper_ip

    @property
    def id(self) -> str:
        """Gets the id of this HostOnlyNetwork.


        :return: The id of this HostOnlyNetwork.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this HostOnlyNetwork.


        :param id: The id of this HostOnlyNetwork.
        :type id: str
        """

        self._id = id
