# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401


from vbox_server.models.base_model_ import Model
from vbox_server.models.host_only_network import HostOnlyNetwork
from vbox_server import util


class HostOnlyNetworkResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, network: HostOnlyNetwork=None):  # noqa: E501
        """HostOnlyNetworkResponse - a model defined in Swagger

        :param network: The network of this HostOnlyNetworkResponse.  # noqa: E501
        :type network: HostOnlyNetwork
        """
        self.swagger_types = {
            'network': HostOnlyNetwork
        }

        self.attribute_map = {
            'network': 'network'
        }

        self._network = network

    @classmethod
    def from_dict(cls, dikt) -> 'HostOnlyNetworkResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The HostOnlyNetwork_response of this HostOnlyNetworkResponse.  # noqa: E501
        :rtype: HostOnlyNetworkResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def network(self) -> HostOnlyNetwork:
        """Gets the network of this HostOnlyNetworkResponse.


        :return: The network of this HostOnlyNetworkResponse.
        :rtype: HostOnlyNetwork
        """
        return self._network

    @network.setter
    def network(self, network: HostOnlyNetwork):
        """Sets the network of this HostOnlyNetworkResponse.


        :param network: The network of this HostOnlyNetworkResponse.
        :type network: HostOnlyNetwork
        """

        self._network = network
