# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401


from vbox_server.models.base_model_ import Model
from vbox_server import util


class MachineGetusbcontrollercountbytypeResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, controllers: int=None):  # noqa: E501
        """MachineGetusbcontrollercountbytypeResponse - a model defined in Swagger

        :param controllers: The controllers of this MachineGetusbcontrollercountbytypeResponse.  # noqa: E501
        :type controllers: int
        """
        self.swagger_types = {
            'controllers': int
        }

        self.attribute_map = {
            'controllers': 'controllers'
        }

        self._controllers = controllers

    @classmethod
    def from_dict(cls, dikt) -> 'MachineGetusbcontrollercountbytypeResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The machine_getusbcontrollercountbytype_response of this MachineGetusbcontrollercountbytypeResponse.  # noqa: E501
        :rtype: MachineGetusbcontrollercountbytypeResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def controllers(self) -> int:
        """Gets the controllers of this MachineGetusbcontrollercountbytypeResponse.


        :return: The controllers of this MachineGetusbcontrollercountbytypeResponse.
        :rtype: int
        """
        return self._controllers

    @controllers.setter
    def controllers(self, controllers: int):
        """Sets the controllers of this MachineGetusbcontrollercountbytypeResponse.


        :param controllers: The controllers of this MachineGetusbcontrollercountbytypeResponse.
        :type controllers: int
        """

        self._controllers = controllers
