# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401


from vbox_server.models.base_model_ import Model
from vbox_server.models.progress import Progress
from vbox_server import util


class MachineTakesnapshotResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, id: str=None, progress: Progress=None):  # noqa: E501
        """MachineTakesnapshotResponse - a model defined in Swagger

        :param id: The id of this MachineTakesnapshotResponse.  # noqa: E501
        :type id: str
        :param progress: The progress of this MachineTakesnapshotResponse.  # noqa: E501
        :type progress: Progress
        """
        self.swagger_types = {
            'id': str,
            'progress': Progress
        }

        self.attribute_map = {
            'id': 'id',
            'progress': 'progress'
        }

        self._id = id
        self._progress = progress

    @classmethod
    def from_dict(cls, dikt) -> 'MachineTakesnapshotResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The machine_takesnapshot_response of this MachineTakesnapshotResponse.  # noqa: E501
        :rtype: MachineTakesnapshotResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this MachineTakesnapshotResponse.


        :return: The id of this MachineTakesnapshotResponse.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this MachineTakesnapshotResponse.


        :param id: The id of this MachineTakesnapshotResponse.
        :type id: str
        """

        self._id = id

    @property
    def progress(self) -> Progress:
        """Gets the progress of this MachineTakesnapshotResponse.


        :return: The progress of this MachineTakesnapshotResponse.
        :rtype: Progress
        """
        return self._progress

    @progress.setter
    def progress(self, progress: Progress):
        """Sets the progress of this MachineTakesnapshotResponse.


        :param progress: The progress of this MachineTakesnapshotResponse.
        :type progress: Progress
        """

        self._progress = progress
