# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401


from vbox_server.models.base_model_ import Model
from vbox_server import util


class MachineDeleteSnapshotRangeRequestBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, start_id: str=None, end_id: str=None):  # noqa: E501
        """MachineDeleteSnapshotRangeRequestBody - a model defined in Swagger

        :param start_id: The start_id of this MachineDeleteSnapshotRangeRequestBody.  # noqa: E501
        :type start_id: str
        :param end_id: The end_id of this MachineDeleteSnapshotRangeRequestBody.  # noqa: E501
        :type end_id: str
        """
        self.swagger_types = {
            'start_id': str,
            'end_id': str
        }

        self.attribute_map = {
            'start_id': 'startId',
            'end_id': 'endId'
        }

        self._start_id = start_id
        self._end_id = end_id

    @classmethod
    def from_dict(cls, dikt) -> 'MachineDeleteSnapshotRangeRequestBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The MachineDeleteSnapshotRangeRequestBody of this MachineDeleteSnapshotRangeRequestBody.  # noqa: E501
        :rtype: MachineDeleteSnapshotRangeRequestBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def start_id(self) -> str:
        """Gets the start_id of this MachineDeleteSnapshotRangeRequestBody.

        UUID of object  # noqa: E501

        :return: The start_id of this MachineDeleteSnapshotRangeRequestBody.
        :rtype: str
        """
        return self._start_id

    @start_id.setter
    def start_id(self, start_id: str):
        """Sets the start_id of this MachineDeleteSnapshotRangeRequestBody.

        UUID of object  # noqa: E501

        :param start_id: The start_id of this MachineDeleteSnapshotRangeRequestBody.
        :type start_id: str
        """

        self._start_id = start_id

    @property
    def end_id(self) -> str:
        """Gets the end_id of this MachineDeleteSnapshotRangeRequestBody.

        UUID of object  # noqa: E501

        :return: The end_id of this MachineDeleteSnapshotRangeRequestBody.
        :rtype: str
        """
        return self._end_id

    @end_id.setter
    def end_id(self, end_id: str):
        """Sets the end_id of this MachineDeleteSnapshotRangeRequestBody.

        UUID of object  # noqa: E501

        :param end_id: The end_id of this MachineDeleteSnapshotRangeRequestBody.
        :type end_id: str
        """

        self._end_id = end_id
