# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401


from vbox_server.models.base_model_ import Model
from vbox_server.models.device_type import DeviceType
from vbox_server import util


class MachineAttachDeviceRequestBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, name: str=None, controller_port: int=None, device: int=None, type: DeviceType=None, medium: str=None):  # noqa: E501
        """MachineAttachDeviceRequestBody - a model defined in Swagger

        :param name: The name of this MachineAttachDeviceRequestBody.  # noqa: E501
        :type name: str
        :param controller_port: The controller_port of this MachineAttachDeviceRequestBody.  # noqa: E501
        :type controller_port: int
        :param device: The device of this MachineAttachDeviceRequestBody.  # noqa: E501
        :type device: int
        :param type: The type of this MachineAttachDeviceRequestBody.  # noqa: E501
        :type type: DeviceType
        :param medium: The medium of this MachineAttachDeviceRequestBody.  # noqa: E501
        :type medium: str
        """
        self.swagger_types = {
            'name': str,
            'controller_port': int,
            'device': int,
            'type': DeviceType,
            'medium': str
        }

        self.attribute_map = {
            'name': 'name',
            'controller_port': 'controllerPort',
            'device': 'device',
            'type': 'type',
            'medium': 'medium'
        }

        self._name = name
        self._controller_port = controller_port
        self._device = device
        self._type = type
        self._medium = medium

    @classmethod
    def from_dict(cls, dikt) -> 'MachineAttachDeviceRequestBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The MachineAttachDeviceRequestBody of this MachineAttachDeviceRequestBody.  # noqa: E501
        :rtype: MachineAttachDeviceRequestBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this MachineAttachDeviceRequestBody.


        :return: The name of this MachineAttachDeviceRequestBody.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this MachineAttachDeviceRequestBody.


        :param name: The name of this MachineAttachDeviceRequestBody.
        :type name: str
        """

        self._name = name

    @property
    def controller_port(self) -> int:
        """Gets the controller_port of this MachineAttachDeviceRequestBody.


        :return: The controller_port of this MachineAttachDeviceRequestBody.
        :rtype: int
        """
        return self._controller_port

    @controller_port.setter
    def controller_port(self, controller_port: int):
        """Sets the controller_port of this MachineAttachDeviceRequestBody.


        :param controller_port: The controller_port of this MachineAttachDeviceRequestBody.
        :type controller_port: int
        """

        self._controller_port = controller_port

    @property
    def device(self) -> int:
        """Gets the device of this MachineAttachDeviceRequestBody.


        :return: The device of this MachineAttachDeviceRequestBody.
        :rtype: int
        """
        return self._device

    @device.setter
    def device(self, device: int):
        """Sets the device of this MachineAttachDeviceRequestBody.


        :param device: The device of this MachineAttachDeviceRequestBody.
        :type device: int
        """

        self._device = device

    @property
    def type(self) -> DeviceType:
        """Gets the type of this MachineAttachDeviceRequestBody.


        :return: The type of this MachineAttachDeviceRequestBody.
        :rtype: DeviceType
        """
        return self._type

    @type.setter
    def type(self, type: DeviceType):
        """Sets the type of this MachineAttachDeviceRequestBody.


        :param type: The type of this MachineAttachDeviceRequestBody.
        :type type: DeviceType
        """

        self._type = type

    @property
    def medium(self) -> str:
        """Gets the medium of this MachineAttachDeviceRequestBody.

        UUID of object  # noqa: E501

        :return: The medium of this MachineAttachDeviceRequestBody.
        :rtype: str
        """
        return self._medium

    @medium.setter
    def medium(self, medium: str):
        """Sets the medium of this MachineAttachDeviceRequestBody.

        UUID of object  # noqa: E501

        :param medium: The medium of this MachineAttachDeviceRequestBody.
        :type medium: str
        """

        self._medium = medium
