# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401


from vbox_server.models.base_model_ import Model
from vbox_server.models.vm_execution_engine import VMExecutionEngine
from vbox_server import util


class MachineDebugger(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, single_step: bool=None, execute_all_in_iem: bool=None, log_enabled: bool=None, log_dbg_flags: str=None, log_dbg_groups: str=None, log_dbg_destinations: str=None, log_rel_flags: str=None, log_rel_groups: str=None, log_rel_destinations: str=None, execution_engine: VMExecutionEngine=None, hw_virt_ex_nested_paging_enabled: bool=None, hw_virt_ex_vpid_enabled: bool=None, hw_virt_ex_ux_enabled: bool=None, os_name: str=None, os_version: str=None, pae_enabled: bool=None, virtual_time_rate: int=None, uptime: int=None):  # noqa: E501
        """MachineDebugger - a model defined in Swagger

        :param single_step: The single_step of this MachineDebugger.  # noqa: E501
        :type single_step: bool
        :param execute_all_in_iem: The execute_all_in_iem of this MachineDebugger.  # noqa: E501
        :type execute_all_in_iem: bool
        :param log_enabled: The log_enabled of this MachineDebugger.  # noqa: E501
        :type log_enabled: bool
        :param log_dbg_flags: The log_dbg_flags of this MachineDebugger.  # noqa: E501
        :type log_dbg_flags: str
        :param log_dbg_groups: The log_dbg_groups of this MachineDebugger.  # noqa: E501
        :type log_dbg_groups: str
        :param log_dbg_destinations: The log_dbg_destinations of this MachineDebugger.  # noqa: E501
        :type log_dbg_destinations: str
        :param log_rel_flags: The log_rel_flags of this MachineDebugger.  # noqa: E501
        :type log_rel_flags: str
        :param log_rel_groups: The log_rel_groups of this MachineDebugger.  # noqa: E501
        :type log_rel_groups: str
        :param log_rel_destinations: The log_rel_destinations of this MachineDebugger.  # noqa: E501
        :type log_rel_destinations: str
        :param execution_engine: The execution_engine of this MachineDebugger.  # noqa: E501
        :type execution_engine: VMExecutionEngine
        :param hw_virt_ex_nested_paging_enabled: The hw_virt_ex_nested_paging_enabled of this MachineDebugger.  # noqa: E501
        :type hw_virt_ex_nested_paging_enabled: bool
        :param hw_virt_ex_vpid_enabled: The hw_virt_ex_vpid_enabled of this MachineDebugger.  # noqa: E501
        :type hw_virt_ex_vpid_enabled: bool
        :param hw_virt_ex_ux_enabled: The hw_virt_ex_ux_enabled of this MachineDebugger.  # noqa: E501
        :type hw_virt_ex_ux_enabled: bool
        :param os_name: The os_name of this MachineDebugger.  # noqa: E501
        :type os_name: str
        :param os_version: The os_version of this MachineDebugger.  # noqa: E501
        :type os_version: str
        :param pae_enabled: The pae_enabled of this MachineDebugger.  # noqa: E501
        :type pae_enabled: bool
        :param virtual_time_rate: The virtual_time_rate of this MachineDebugger.  # noqa: E501
        :type virtual_time_rate: int
        :param uptime: The uptime of this MachineDebugger.  # noqa: E501
        :type uptime: int
        """
        self.swagger_types = {
            'single_step': bool,
            'execute_all_in_iem': bool,
            'log_enabled': bool,
            'log_dbg_flags': str,
            'log_dbg_groups': str,
            'log_dbg_destinations': str,
            'log_rel_flags': str,
            'log_rel_groups': str,
            'log_rel_destinations': str,
            'execution_engine': VMExecutionEngine,
            'hw_virt_ex_nested_paging_enabled': bool,
            'hw_virt_ex_vpid_enabled': bool,
            'hw_virt_ex_ux_enabled': bool,
            'os_name': str,
            'os_version': str,
            'pae_enabled': bool,
            'virtual_time_rate': int,
            'uptime': int
        }

        self.attribute_map = {
            'single_step': 'singleStep',
            'execute_all_in_iem': 'executeAllInIEM',
            'log_enabled': 'logEnabled',
            'log_dbg_flags': 'logDbgFlags',
            'log_dbg_groups': 'logDbgGroups',
            'log_dbg_destinations': 'logDbgDestinations',
            'log_rel_flags': 'logRelFlags',
            'log_rel_groups': 'logRelGroups',
            'log_rel_destinations': 'logRelDestinations',
            'execution_engine': 'executionEngine',
            'hw_virt_ex_nested_paging_enabled': 'HWVirtExNestedPagingEnabled',
            'hw_virt_ex_vpid_enabled': 'HWVirtExVPIDEnabled',
            'hw_virt_ex_ux_enabled': 'HWVirtExUXEnabled',
            'os_name': 'OSName',
            'os_version': 'OSVersion',
            'pae_enabled': 'PAEEnabled',
            'virtual_time_rate': 'virtualTimeRate',
            'uptime': 'uptime'
        }

        self._single_step = single_step
        self._execute_all_in_iem = execute_all_in_iem
        self._log_enabled = log_enabled
        self._log_dbg_flags = log_dbg_flags
        self._log_dbg_groups = log_dbg_groups
        self._log_dbg_destinations = log_dbg_destinations
        self._log_rel_flags = log_rel_flags
        self._log_rel_groups = log_rel_groups
        self._log_rel_destinations = log_rel_destinations
        self._execution_engine = execution_engine
        self._hw_virt_ex_nested_paging_enabled = hw_virt_ex_nested_paging_enabled
        self._hw_virt_ex_vpid_enabled = hw_virt_ex_vpid_enabled
        self._hw_virt_ex_ux_enabled = hw_virt_ex_ux_enabled
        self._os_name = os_name
        self._os_version = os_version
        self._pae_enabled = pae_enabled
        self._virtual_time_rate = virtual_time_rate
        self._uptime = uptime

    @classmethod
    def from_dict(cls, dikt) -> 'MachineDebugger':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The MachineDebugger of this MachineDebugger.  # noqa: E501
        :rtype: MachineDebugger
        """
        return util.deserialize_model(dikt, cls)

    @property
    def single_step(self) -> bool:
        """Gets the single_step of this MachineDebugger.


        :return: The single_step of this MachineDebugger.
        :rtype: bool
        """
        return self._single_step

    @single_step.setter
    def single_step(self, single_step: bool):
        """Sets the single_step of this MachineDebugger.


        :param single_step: The single_step of this MachineDebugger.
        :type single_step: bool
        """

        self._single_step = single_step

    @property
    def execute_all_in_iem(self) -> bool:
        """Gets the execute_all_in_iem of this MachineDebugger.


        :return: The execute_all_in_iem of this MachineDebugger.
        :rtype: bool
        """
        return self._execute_all_in_iem

    @execute_all_in_iem.setter
    def execute_all_in_iem(self, execute_all_in_iem: bool):
        """Sets the execute_all_in_iem of this MachineDebugger.


        :param execute_all_in_iem: The execute_all_in_iem of this MachineDebugger.
        :type execute_all_in_iem: bool
        """

        self._execute_all_in_iem = execute_all_in_iem

    @property
    def log_enabled(self) -> bool:
        """Gets the log_enabled of this MachineDebugger.


        :return: The log_enabled of this MachineDebugger.
        :rtype: bool
        """
        return self._log_enabled

    @log_enabled.setter
    def log_enabled(self, log_enabled: bool):
        """Sets the log_enabled of this MachineDebugger.


        :param log_enabled: The log_enabled of this MachineDebugger.
        :type log_enabled: bool
        """

        self._log_enabled = log_enabled

    @property
    def log_dbg_flags(self) -> str:
        """Gets the log_dbg_flags of this MachineDebugger.


        :return: The log_dbg_flags of this MachineDebugger.
        :rtype: str
        """
        return self._log_dbg_flags

    @log_dbg_flags.setter
    def log_dbg_flags(self, log_dbg_flags: str):
        """Sets the log_dbg_flags of this MachineDebugger.


        :param log_dbg_flags: The log_dbg_flags of this MachineDebugger.
        :type log_dbg_flags: str
        """

        self._log_dbg_flags = log_dbg_flags

    @property
    def log_dbg_groups(self) -> str:
        """Gets the log_dbg_groups of this MachineDebugger.


        :return: The log_dbg_groups of this MachineDebugger.
        :rtype: str
        """
        return self._log_dbg_groups

    @log_dbg_groups.setter
    def log_dbg_groups(self, log_dbg_groups: str):
        """Sets the log_dbg_groups of this MachineDebugger.


        :param log_dbg_groups: The log_dbg_groups of this MachineDebugger.
        :type log_dbg_groups: str
        """

        self._log_dbg_groups = log_dbg_groups

    @property
    def log_dbg_destinations(self) -> str:
        """Gets the log_dbg_destinations of this MachineDebugger.


        :return: The log_dbg_destinations of this MachineDebugger.
        :rtype: str
        """
        return self._log_dbg_destinations

    @log_dbg_destinations.setter
    def log_dbg_destinations(self, log_dbg_destinations: str):
        """Sets the log_dbg_destinations of this MachineDebugger.


        :param log_dbg_destinations: The log_dbg_destinations of this MachineDebugger.
        :type log_dbg_destinations: str
        """

        self._log_dbg_destinations = log_dbg_destinations

    @property
    def log_rel_flags(self) -> str:
        """Gets the log_rel_flags of this MachineDebugger.


        :return: The log_rel_flags of this MachineDebugger.
        :rtype: str
        """
        return self._log_rel_flags

    @log_rel_flags.setter
    def log_rel_flags(self, log_rel_flags: str):
        """Sets the log_rel_flags of this MachineDebugger.


        :param log_rel_flags: The log_rel_flags of this MachineDebugger.
        :type log_rel_flags: str
        """

        self._log_rel_flags = log_rel_flags

    @property
    def log_rel_groups(self) -> str:
        """Gets the log_rel_groups of this MachineDebugger.


        :return: The log_rel_groups of this MachineDebugger.
        :rtype: str
        """
        return self._log_rel_groups

    @log_rel_groups.setter
    def log_rel_groups(self, log_rel_groups: str):
        """Sets the log_rel_groups of this MachineDebugger.


        :param log_rel_groups: The log_rel_groups of this MachineDebugger.
        :type log_rel_groups: str
        """

        self._log_rel_groups = log_rel_groups

    @property
    def log_rel_destinations(self) -> str:
        """Gets the log_rel_destinations of this MachineDebugger.


        :return: The log_rel_destinations of this MachineDebugger.
        :rtype: str
        """
        return self._log_rel_destinations

    @log_rel_destinations.setter
    def log_rel_destinations(self, log_rel_destinations: str):
        """Sets the log_rel_destinations of this MachineDebugger.


        :param log_rel_destinations: The log_rel_destinations of this MachineDebugger.
        :type log_rel_destinations: str
        """

        self._log_rel_destinations = log_rel_destinations

    @property
    def execution_engine(self) -> VMExecutionEngine:
        """Gets the execution_engine of this MachineDebugger.


        :return: The execution_engine of this MachineDebugger.
        :rtype: VMExecutionEngine
        """
        return self._execution_engine

    @execution_engine.setter
    def execution_engine(self, execution_engine: VMExecutionEngine):
        """Sets the execution_engine of this MachineDebugger.


        :param execution_engine: The execution_engine of this MachineDebugger.
        :type execution_engine: VMExecutionEngine
        """

        self._execution_engine = execution_engine

    @property
    def hw_virt_ex_nested_paging_enabled(self) -> bool:
        """Gets the hw_virt_ex_nested_paging_enabled of this MachineDebugger.


        :return: The hw_virt_ex_nested_paging_enabled of this MachineDebugger.
        :rtype: bool
        """
        return self._hw_virt_ex_nested_paging_enabled

    @hw_virt_ex_nested_paging_enabled.setter
    def hw_virt_ex_nested_paging_enabled(self, hw_virt_ex_nested_paging_enabled: bool):
        """Sets the hw_virt_ex_nested_paging_enabled of this MachineDebugger.


        :param hw_virt_ex_nested_paging_enabled: The hw_virt_ex_nested_paging_enabled of this MachineDebugger.
        :type hw_virt_ex_nested_paging_enabled: bool
        """

        self._hw_virt_ex_nested_paging_enabled = hw_virt_ex_nested_paging_enabled

    @property
    def hw_virt_ex_vpid_enabled(self) -> bool:
        """Gets the hw_virt_ex_vpid_enabled of this MachineDebugger.


        :return: The hw_virt_ex_vpid_enabled of this MachineDebugger.
        :rtype: bool
        """
        return self._hw_virt_ex_vpid_enabled

    @hw_virt_ex_vpid_enabled.setter
    def hw_virt_ex_vpid_enabled(self, hw_virt_ex_vpid_enabled: bool):
        """Sets the hw_virt_ex_vpid_enabled of this MachineDebugger.


        :param hw_virt_ex_vpid_enabled: The hw_virt_ex_vpid_enabled of this MachineDebugger.
        :type hw_virt_ex_vpid_enabled: bool
        """

        self._hw_virt_ex_vpid_enabled = hw_virt_ex_vpid_enabled

    @property
    def hw_virt_ex_ux_enabled(self) -> bool:
        """Gets the hw_virt_ex_ux_enabled of this MachineDebugger.


        :return: The hw_virt_ex_ux_enabled of this MachineDebugger.
        :rtype: bool
        """
        return self._hw_virt_ex_ux_enabled

    @hw_virt_ex_ux_enabled.setter
    def hw_virt_ex_ux_enabled(self, hw_virt_ex_ux_enabled: bool):
        """Sets the hw_virt_ex_ux_enabled of this MachineDebugger.


        :param hw_virt_ex_ux_enabled: The hw_virt_ex_ux_enabled of this MachineDebugger.
        :type hw_virt_ex_ux_enabled: bool
        """

        self._hw_virt_ex_ux_enabled = hw_virt_ex_ux_enabled

    @property
    def os_name(self) -> str:
        """Gets the os_name of this MachineDebugger.


        :return: The os_name of this MachineDebugger.
        :rtype: str
        """
        return self._os_name

    @os_name.setter
    def os_name(self, os_name: str):
        """Sets the os_name of this MachineDebugger.


        :param os_name: The os_name of this MachineDebugger.
        :type os_name: str
        """

        self._os_name = os_name

    @property
    def os_version(self) -> str:
        """Gets the os_version of this MachineDebugger.


        :return: The os_version of this MachineDebugger.
        :rtype: str
        """
        return self._os_version

    @os_version.setter
    def os_version(self, os_version: str):
        """Sets the os_version of this MachineDebugger.


        :param os_version: The os_version of this MachineDebugger.
        :type os_version: str
        """

        self._os_version = os_version

    @property
    def pae_enabled(self) -> bool:
        """Gets the pae_enabled of this MachineDebugger.


        :return: The pae_enabled of this MachineDebugger.
        :rtype: bool
        """
        return self._pae_enabled

    @pae_enabled.setter
    def pae_enabled(self, pae_enabled: bool):
        """Sets the pae_enabled of this MachineDebugger.


        :param pae_enabled: The pae_enabled of this MachineDebugger.
        :type pae_enabled: bool
        """

        self._pae_enabled = pae_enabled

    @property
    def virtual_time_rate(self) -> int:
        """Gets the virtual_time_rate of this MachineDebugger.


        :return: The virtual_time_rate of this MachineDebugger.
        :rtype: int
        """
        return self._virtual_time_rate

    @virtual_time_rate.setter
    def virtual_time_rate(self, virtual_time_rate: int):
        """Sets the virtual_time_rate of this MachineDebugger.


        :param virtual_time_rate: The virtual_time_rate of this MachineDebugger.
        :type virtual_time_rate: int
        """

        self._virtual_time_rate = virtual_time_rate

    @property
    def uptime(self) -> int:
        """Gets the uptime of this MachineDebugger.


        :return: The uptime of this MachineDebugger.
        :rtype: int
        """
        return self._uptime

    @uptime.setter
    def uptime(self, uptime: int):
        """Sets the uptime of this MachineDebugger.


        :param uptime: The uptime of this MachineDebugger.
        :type uptime: int
        """

        self._uptime = uptime
