# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401


from vbox_server.models.base_model_ import Model
from vbox_server import util


class MachineReadlogResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, data: str=None):  # noqa: E501
        """MachineReadlogResponse - a model defined in Swagger

        :param data: The data of this MachineReadlogResponse.  # noqa: E501
        :type data: str
        """
        self.swagger_types = {
            'data': str
        }

        self.attribute_map = {
            'data': 'data'
        }

        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'MachineReadlogResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The machine_readlog_response of this MachineReadlogResponse.  # noqa: E501
        :rtype: MachineReadlogResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self) -> str:
        """Gets the data of this MachineReadlogResponse.


        :return: The data of this MachineReadlogResponse.
        :rtype: str
        """
        return self._data

    @data.setter
    def data(self, data: str):
        """Sets the data of this MachineReadlogResponse.


        :param data: The data of this MachineReadlogResponse.
        :type data: str
        """

        self._data = data
