# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401


from vbox_server.models.base_model_ import Model
from vbox_server import util


class MachineCreateSharedFolderRequestBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, name: str=None, host_path: str=None, writable: bool=None, automount: bool=None, auto_mount_point: str=None):  # noqa: E501
        """MachineCreateSharedFolderRequestBody - a model defined in Swagger

        :param name: The name of this MachineCreateSharedFolderRequestBody.  # noqa: E501
        :type name: str
        :param host_path: The host_path of this MachineCreateSharedFolderRequestBody.  # noqa: E501
        :type host_path: str
        :param writable: The writable of this MachineCreateSharedFolderRequestBody.  # noqa: E501
        :type writable: bool
        :param automount: The automount of this MachineCreateSharedFolderRequestBody.  # noqa: E501
        :type automount: bool
        :param auto_mount_point: The auto_mount_point of this MachineCreateSharedFolderRequestBody.  # noqa: E501
        :type auto_mount_point: str
        """
        self.swagger_types = {
            'name': str,
            'host_path': str,
            'writable': bool,
            'automount': bool,
            'auto_mount_point': str
        }

        self.attribute_map = {
            'name': 'name',
            'host_path': 'hostPath',
            'writable': 'writable',
            'automount': 'automount',
            'auto_mount_point': 'autoMountPoint'
        }

        self._name = name
        self._host_path = host_path
        self._writable = writable
        self._automount = automount
        self._auto_mount_point = auto_mount_point

    @classmethod
    def from_dict(cls, dikt) -> 'MachineCreateSharedFolderRequestBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The MachineCreateSharedFolderRequestBody of this MachineCreateSharedFolderRequestBody.  # noqa: E501
        :rtype: MachineCreateSharedFolderRequestBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this MachineCreateSharedFolderRequestBody.


        :return: The name of this MachineCreateSharedFolderRequestBody.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this MachineCreateSharedFolderRequestBody.


        :param name: The name of this MachineCreateSharedFolderRequestBody.
        :type name: str
        """

        self._name = name

    @property
    def host_path(self) -> str:
        """Gets the host_path of this MachineCreateSharedFolderRequestBody.


        :return: The host_path of this MachineCreateSharedFolderRequestBody.
        :rtype: str
        """
        return self._host_path

    @host_path.setter
    def host_path(self, host_path: str):
        """Sets the host_path of this MachineCreateSharedFolderRequestBody.


        :param host_path: The host_path of this MachineCreateSharedFolderRequestBody.
        :type host_path: str
        """

        self._host_path = host_path

    @property
    def writable(self) -> bool:
        """Gets the writable of this MachineCreateSharedFolderRequestBody.


        :return: The writable of this MachineCreateSharedFolderRequestBody.
        :rtype: bool
        """
        return self._writable

    @writable.setter
    def writable(self, writable: bool):
        """Sets the writable of this MachineCreateSharedFolderRequestBody.


        :param writable: The writable of this MachineCreateSharedFolderRequestBody.
        :type writable: bool
        """

        self._writable = writable

    @property
    def automount(self) -> bool:
        """Gets the automount of this MachineCreateSharedFolderRequestBody.


        :return: The automount of this MachineCreateSharedFolderRequestBody.
        :rtype: bool
        """
        return self._automount

    @automount.setter
    def automount(self, automount: bool):
        """Sets the automount of this MachineCreateSharedFolderRequestBody.


        :param automount: The automount of this MachineCreateSharedFolderRequestBody.
        :type automount: bool
        """

        self._automount = automount

    @property
    def auto_mount_point(self) -> str:
        """Gets the auto_mount_point of this MachineCreateSharedFolderRequestBody.


        :return: The auto_mount_point of this MachineCreateSharedFolderRequestBody.
        :rtype: str
        """
        return self._auto_mount_point

    @auto_mount_point.setter
    def auto_mount_point(self, auto_mount_point: str):
        """Sets the auto_mount_point of this MachineCreateSharedFolderRequestBody.


        :param auto_mount_point: The auto_mount_point of this MachineCreateSharedFolderRequestBody.
        :type auto_mount_point: str
        """

        self._auto_mount_point = auto_mount_point
