# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401


from vbox_server.models.base_model_ import Model
from vbox_server import util


class MachineNonRotationalDeviceRequestBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, name: str=None, controller_port: int=None, device: int=None, non_rotational: bool=None):  # noqa: E501
        """MachineNonRotationalDeviceRequestBody - a model defined in Swagger

        :param name: The name of this MachineNonRotationalDeviceRequestBody.  # noqa: E501
        :type name: str
        :param controller_port: The controller_port of this MachineNonRotationalDeviceRequestBody.  # noqa: E501
        :type controller_port: int
        :param device: The device of this MachineNonRotationalDeviceRequestBody.  # noqa: E501
        :type device: int
        :param non_rotational: The non_rotational of this MachineNonRotationalDeviceRequestBody.  # noqa: E501
        :type non_rotational: bool
        """
        self.swagger_types = {
            'name': str,
            'controller_port': int,
            'device': int,
            'non_rotational': bool
        }

        self.attribute_map = {
            'name': 'name',
            'controller_port': 'controllerPort',
            'device': 'device',
            'non_rotational': 'nonRotational'
        }

        self._name = name
        self._controller_port = controller_port
        self._device = device
        self._non_rotational = non_rotational

    @classmethod
    def from_dict(cls, dikt) -> 'MachineNonRotationalDeviceRequestBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The MachineNonRotationalDeviceRequestBody of this MachineNonRotationalDeviceRequestBody.  # noqa: E501
        :rtype: MachineNonRotationalDeviceRequestBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this MachineNonRotationalDeviceRequestBody.


        :return: The name of this MachineNonRotationalDeviceRequestBody.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this MachineNonRotationalDeviceRequestBody.


        :param name: The name of this MachineNonRotationalDeviceRequestBody.
        :type name: str
        """

        self._name = name

    @property
    def controller_port(self) -> int:
        """Gets the controller_port of this MachineNonRotationalDeviceRequestBody.


        :return: The controller_port of this MachineNonRotationalDeviceRequestBody.
        :rtype: int
        """
        return self._controller_port

    @controller_port.setter
    def controller_port(self, controller_port: int):
        """Sets the controller_port of this MachineNonRotationalDeviceRequestBody.


        :param controller_port: The controller_port of this MachineNonRotationalDeviceRequestBody.
        :type controller_port: int
        """

        self._controller_port = controller_port

    @property
    def device(self) -> int:
        """Gets the device of this MachineNonRotationalDeviceRequestBody.


        :return: The device of this MachineNonRotationalDeviceRequestBody.
        :rtype: int
        """
        return self._device

    @device.setter
    def device(self, device: int):
        """Sets the device of this MachineNonRotationalDeviceRequestBody.


        :param device: The device of this MachineNonRotationalDeviceRequestBody.
        :type device: int
        """

        self._device = device

    @property
    def non_rotational(self) -> bool:
        """Gets the non_rotational of this MachineNonRotationalDeviceRequestBody.


        :return: The non_rotational of this MachineNonRotationalDeviceRequestBody.
        :rtype: bool
        """
        return self._non_rotational

    @non_rotational.setter
    def non_rotational(self, non_rotational: bool):
        """Sets the non_rotational of this MachineNonRotationalDeviceRequestBody.


        :param non_rotational: The non_rotational of this MachineNonRotationalDeviceRequestBody.
        :type non_rotational: bool
        """

        self._non_rotational = non_rotational
