# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401


from vbox_server.models.base_model_ import Model
from vbox_server import util


class MachineQuerylogfilenameResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, filename: str=None):  # noqa: E501
        """MachineQuerylogfilenameResponse - a model defined in Swagger

        :param filename: The filename of this MachineQuerylogfilenameResponse.  # noqa: E501
        :type filename: str
        """
        self.swagger_types = {
            'filename': str
        }

        self.attribute_map = {
            'filename': 'filename'
        }

        self._filename = filename

    @classmethod
    def from_dict(cls, dikt) -> 'MachineQuerylogfilenameResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The machine_querylogfilename_response of this MachineQuerylogfilenameResponse.  # noqa: E501
        :rtype: MachineQuerylogfilenameResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def filename(self) -> str:
        """Gets the filename of this MachineQuerylogfilenameResponse.


        :return: The filename of this MachineQuerylogfilenameResponse.
        :rtype: str
        """
        return self._filename

    @filename.setter
    def filename(self, filename: str):
        """Sets the filename of this MachineQuerylogfilenameResponse.


        :param filename: The filename of this MachineQuerylogfilenameResponse.
        :type filename: str
        """

        self._filename = filename
