# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401


from vbox_server.models.base_model_ import Model
from vbox_server import util


class MachineMoveToRequestBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, folder: str=None, type: str=None):  # noqa: E501
        """MachineMoveToRequestBody - a model defined in Swagger

        :param folder: The folder of this MachineMoveToRequestBody.  # noqa: E501
        :type folder: str
        :param type: The type of this MachineMoveToRequestBody.  # noqa: E501
        :type type: str
        """
        self.swagger_types = {
            'folder': str,
            'type': str
        }

        self.attribute_map = {
            'folder': 'folder',
            'type': 'type'
        }

        self._folder = folder
        self._type = type

    @classmethod
    def from_dict(cls, dikt) -> 'MachineMoveToRequestBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The MachineMoveToRequestBody of this MachineMoveToRequestBody.  # noqa: E501
        :rtype: MachineMoveToRequestBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def folder(self) -> str:
        """Gets the folder of this MachineMoveToRequestBody.


        :return: The folder of this MachineMoveToRequestBody.
        :rtype: str
        """
        return self._folder

    @folder.setter
    def folder(self, folder: str):
        """Sets the folder of this MachineMoveToRequestBody.


        :param folder: The folder of this MachineMoveToRequestBody.
        :type folder: str
        """

        self._folder = folder

    @property
    def type(self) -> str:
        """Gets the type of this MachineMoveToRequestBody.


        :return: The type of this MachineMoveToRequestBody.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this MachineMoveToRequestBody.


        :param type: The type of this MachineMoveToRequestBody.
        :type type: str
        """

        self._type = type
