# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401


from vbox_server.models.base_model_ import Model
from vbox_server.models.medium import Medium
from vbox_server import util


class MediumArrayResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, media: List[Medium]=None):  # noqa: E501
        """MediumArrayResponse - a model defined in Swagger

        :param media: The media of this MediumArrayResponse.  # noqa: E501
        :type media: List[Medium]
        """
        self.swagger_types = {
            'media': List[Medium]
        }

        self.attribute_map = {
            'media': 'media'
        }

        self._media = media

    @classmethod
    def from_dict(cls, dikt) -> 'MediumArrayResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Medium_array_response of this MediumArrayResponse.  # noqa: E501
        :rtype: MediumArrayResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def media(self) -> List[Medium]:
        """Gets the media of this MediumArrayResponse.


        :return: The media of this MediumArrayResponse.
        :rtype: List[Medium]
        """
        return self._media

    @media.setter
    def media(self, media: List[Medium]):
        """Sets the media of this MediumArrayResponse.


        :param media: The media of this MediumArrayResponse.
        :type media: List[Medium]
        """

        self._media = media
