# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401


from vbox_server.models.base_model_ import Model
from vbox_server import util


class MediumSetPropertiesRequestBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, names: List[str]=None, values: List[str]=None):  # noqa: E501
        """MediumSetPropertiesRequestBody - a model defined in Swagger

        :param names: The names of this MediumSetPropertiesRequestBody.  # noqa: E501
        :type names: List[str]
        :param values: The values of this MediumSetPropertiesRequestBody.  # noqa: E501
        :type values: List[str]
        """
        self.swagger_types = {
            'names': List[str],
            'values': List[str]
        }

        self.attribute_map = {
            'names': 'names',
            'values': 'values'
        }

        self._names = names
        self._values = values

    @classmethod
    def from_dict(cls, dikt) -> 'MediumSetPropertiesRequestBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The MediumSetPropertiesRequestBody of this MediumSetPropertiesRequestBody.  # noqa: E501
        :rtype: MediumSetPropertiesRequestBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def names(self) -> List[str]:
        """Gets the names of this MediumSetPropertiesRequestBody.


        :return: The names of this MediumSetPropertiesRequestBody.
        :rtype: List[str]
        """
        return self._names

    @names.setter
    def names(self, names: List[str]):
        """Sets the names of this MediumSetPropertiesRequestBody.


        :param names: The names of this MediumSetPropertiesRequestBody.
        :type names: List[str]
        """

        self._names = names

    @property
    def values(self) -> List[str]:
        """Gets the values of this MediumSetPropertiesRequestBody.


        :return: The values of this MediumSetPropertiesRequestBody.
        :rtype: List[str]
        """
        return self._values

    @values.setter
    def values(self, values: List[str]):
        """Sets the values of this MediumSetPropertiesRequestBody.


        :param values: The values of this MediumSetPropertiesRequestBody.
        :type values: List[str]
        """

        self._values = values
