# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401


from vbox_server.models.base_model_ import Model
from vbox_server.models.medium_attachment import MediumAttachment
from vbox_server import util


class MediumAttachmentResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, attachment: MediumAttachment=None):  # noqa: E501
        """MediumAttachmentResponse - a model defined in Swagger

        :param attachment: The attachment of this MediumAttachmentResponse.  # noqa: E501
        :type attachment: MediumAttachment
        """
        self.swagger_types = {
            'attachment': MediumAttachment
        }

        self.attribute_map = {
            'attachment': 'attachment'
        }

        self._attachment = attachment

    @classmethod
    def from_dict(cls, dikt) -> 'MediumAttachmentResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The MediumAttachment_response of this MediumAttachmentResponse.  # noqa: E501
        :rtype: MediumAttachmentResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def attachment(self) -> MediumAttachment:
        """Gets the attachment of this MediumAttachmentResponse.


        :return: The attachment of this MediumAttachmentResponse.
        :rtype: MediumAttachment
        """
        return self._attachment

    @attachment.setter
    def attachment(self, attachment: MediumAttachment):
        """Sets the attachment of this MediumAttachmentResponse.


        :param attachment: The attachment of this MediumAttachmentResponse.
        :type attachment: MediumAttachment
        """

        self._attachment = attachment
