# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401


from vbox_server.models.base_model_ import Model
from vbox_server import util


class MediumGetpropertiesResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, return_names: List[str]=None, return_values: List[str]=None):  # noqa: E501
        """MediumGetpropertiesResponse - a model defined in Swagger

        :param return_names: The return_names of this MediumGetpropertiesResponse.  # noqa: E501
        :type return_names: List[str]
        :param return_values: The return_values of this MediumGetpropertiesResponse.  # noqa: E501
        :type return_values: List[str]
        """
        self.swagger_types = {
            'return_names': List[str],
            'return_values': List[str]
        }

        self.attribute_map = {
            'return_names': 'returnNames',
            'return_values': 'returnValues'
        }

        self._return_names = return_names
        self._return_values = return_values

    @classmethod
    def from_dict(cls, dikt) -> 'MediumGetpropertiesResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The medium_getproperties_response of this MediumGetpropertiesResponse.  # noqa: E501
        :rtype: MediumGetpropertiesResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def return_names(self) -> List[str]:
        """Gets the return_names of this MediumGetpropertiesResponse.


        :return: The return_names of this MediumGetpropertiesResponse.
        :rtype: List[str]
        """
        return self._return_names

    @return_names.setter
    def return_names(self, return_names: List[str]):
        """Sets the return_names of this MediumGetpropertiesResponse.


        :param return_names: The return_names of this MediumGetpropertiesResponse.
        :type return_names: List[str]
        """

        self._return_names = return_names

    @property
    def return_values(self) -> List[str]:
        """Gets the return_values of this MediumGetpropertiesResponse.


        :return: The return_values of this MediumGetpropertiesResponse.
        :rtype: List[str]
        """
        return self._return_values

    @return_values.setter
    def return_values(self, return_values: List[str]):
        """Sets the return_values of this MediumGetpropertiesResponse.


        :param return_values: The return_values of this MediumGetpropertiesResponse.
        :type return_values: List[str]
        """

        self._return_values = return_values
