# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401


from vbox_server.models.base_model_ import Model
from vbox_server.models.nat_network import NATNetwork
from vbox_server import util


class NATNetworkResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, network: NATNetwork=None):  # noqa: E501
        """NATNetworkResponse - a model defined in Swagger

        :param network: The network of this NATNetworkResponse.  # noqa: E501
        :type network: NATNetwork
        """
        self.swagger_types = {
            'network': NATNetwork
        }

        self.attribute_map = {
            'network': 'network'
        }

        self._network = network

    @classmethod
    def from_dict(cls, dikt) -> 'NATNetworkResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The NATNetwork_response of this NATNetworkResponse.  # noqa: E501
        :rtype: NATNetworkResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def network(self) -> NATNetwork:
        """Gets the network of this NATNetworkResponse.


        :return: The network of this NATNetworkResponse.
        :rtype: NATNetwork
        """
        return self._network

    @network.setter
    def network(self, network: NATNetwork):
        """Sets the network of this NATNetworkResponse.


        :param network: The network of this NATNetworkResponse.
        :type network: NATNetwork
        """

        self._network = network
