# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401


from vbox_server.models.base_model_ import Model
from vbox_server import util


class NetworkAdapterType(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    NULL = "null"
    AM79C970A = "AM79C970A"
    AM79C973 = "AM79C973"
    I82540EM = "I82540EM"
    I82543GC = "I82543GC"
    I82545EM = "I82545EM"
    VIRTIO = "VIRTIO"
    AM79C960 = "AM79C960"
    NE2000 = "NE2000"
    NE1000 = "NE1000"
    WD8013 = "WD8013"
    WD8003 = "WD8003"
    ELNK2 = "ELNK2"
    ELNK1 = "ELNK1"

    def __init__(self):  # noqa: E501
        """NetworkAdapterType - a model defined in Swagger

        """
        self.swagger_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'NetworkAdapterType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The NetworkAdapterType of this NetworkAdapterType.  # noqa: E501
        :rtype: NetworkAdapterType
        """
        return util.deserialize_model(dikt, cls)
