# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401


from vbox_server.models.base_model_ import Model
from vbox_server import util


class ParallelPort(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, slot: int=None, enabled: bool=None, io_base: int=None, irq: int=None, path: str=None):  # noqa: E501
        """ParallelPort - a model defined in Swagger

        :param slot: The slot of this ParallelPort.  # noqa: E501
        :type slot: int
        :param enabled: The enabled of this ParallelPort.  # noqa: E501
        :type enabled: bool
        :param io_base: The io_base of this ParallelPort.  # noqa: E501
        :type io_base: int
        :param irq: The irq of this ParallelPort.  # noqa: E501
        :type irq: int
        :param path: The path of this ParallelPort.  # noqa: E501
        :type path: str
        """
        self.swagger_types = {
            'slot': int,
            'enabled': bool,
            'io_base': int,
            'irq': int,
            'path': str
        }

        self.attribute_map = {
            'slot': 'slot',
            'enabled': 'enabled',
            'io_base': 'IOBase',
            'irq': 'IRQ',
            'path': 'path'
        }

        self._slot = slot
        self._enabled = enabled
        self._io_base = io_base
        self._irq = irq
        self._path = path

    @classmethod
    def from_dict(cls, dikt) -> 'ParallelPort':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ParallelPort of this ParallelPort.  # noqa: E501
        :rtype: ParallelPort
        """
        return util.deserialize_model(dikt, cls)

    @property
    def slot(self) -> int:
        """Gets the slot of this ParallelPort.


        :return: The slot of this ParallelPort.
        :rtype: int
        """
        return self._slot

    @slot.setter
    def slot(self, slot: int):
        """Sets the slot of this ParallelPort.


        :param slot: The slot of this ParallelPort.
        :type slot: int
        """

        self._slot = slot

    @property
    def enabled(self) -> bool:
        """Gets the enabled of this ParallelPort.


        :return: The enabled of this ParallelPort.
        :rtype: bool
        """
        return self._enabled

    @enabled.setter
    def enabled(self, enabled: bool):
        """Sets the enabled of this ParallelPort.


        :param enabled: The enabled of this ParallelPort.
        :type enabled: bool
        """

        self._enabled = enabled

    @property
    def io_base(self) -> int:
        """Gets the io_base of this ParallelPort.


        :return: The io_base of this ParallelPort.
        :rtype: int
        """
        return self._io_base

    @io_base.setter
    def io_base(self, io_base: int):
        """Sets the io_base of this ParallelPort.


        :param io_base: The io_base of this ParallelPort.
        :type io_base: int
        """

        self._io_base = io_base

    @property
    def irq(self) -> int:
        """Gets the irq of this ParallelPort.


        :return: The irq of this ParallelPort.
        :rtype: int
        """
        return self._irq

    @irq.setter
    def irq(self, irq: int):
        """Sets the irq of this ParallelPort.


        :param irq: The irq of this ParallelPort.
        :type irq: int
        """

        self._irq = irq

    @property
    def path(self) -> str:
        """Gets the path of this ParallelPort.


        :return: The path of this ParallelPort.
        :rtype: str
        """
        return self._path

    @path.setter
    def path(self, path: str):
        """Sets the path of this ParallelPort.


        :param path: The path of this ParallelPort.
        :type path: str
        """

        self._path = path
