# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401


from vbox_server.models.base_model_ import Model
from vbox_server import util


class RecordingVideoCodec(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    NONE = "NONE"
    MJPEG = "MJPEG"
    H262 = "H262"
    H264 = "H264"
    H265 = "H265"
    H266 = "H266"
    VP8 = "VP8"
    VP9 = "VP9"
    AV1 = "AV1"
    OTHER = "OTHER"

    def __init__(self):  # noqa: E501
        """RecordingVideoCodec - a model defined in Swagger

        """
        self.swagger_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'RecordingVideoCodec':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RecordingVideoCodec of this RecordingVideoCodec.  # noqa: E501
        :rtype: RecordingVideoCodec
        """
        return util.deserialize_model(dikt, cls)
