# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401


from vbox_server.models.base_model_ import Model
from vbox_server.models.console import Console
from vbox_server.models.session_state import SessionState
from vbox_server.models.session_type import SessionType
from vbox_server import util


class Session(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, state: SessionState=None, type: SessionType=None, name: str=None, machine: str=None, console: Console=None):  # noqa: E501
        """Session - a model defined in Swagger

        :param state: The state of this Session.  # noqa: E501
        :type state: SessionState
        :param type: The type of this Session.  # noqa: E501
        :type type: SessionType
        :param name: The name of this Session.  # noqa: E501
        :type name: str
        :param machine: The machine of this Session.  # noqa: E501
        :type machine: str
        :param console: The console of this Session.  # noqa: E501
        :type console: Console
        """
        self.swagger_types = {
            'state': SessionState,
            'type': SessionType,
            'name': str,
            'machine': str,
            'console': Console
        }

        self.attribute_map = {
            'state': 'state',
            'type': 'type',
            'name': 'name',
            'machine': 'machine',
            'console': 'console'
        }

        self._state = state
        self._type = type
        self._name = name
        self._machine = machine
        self._console = console

    @classmethod
    def from_dict(cls, dikt) -> 'Session':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Session of this Session.  # noqa: E501
        :rtype: Session
        """
        return util.deserialize_model(dikt, cls)

    @property
    def state(self) -> SessionState:
        """Gets the state of this Session.


        :return: The state of this Session.
        :rtype: SessionState
        """
        return self._state

    @state.setter
    def state(self, state: SessionState):
        """Sets the state of this Session.


        :param state: The state of this Session.
        :type state: SessionState
        """

        self._state = state

    @property
    def type(self) -> SessionType:
        """Gets the type of this Session.


        :return: The type of this Session.
        :rtype: SessionType
        """
        return self._type

    @type.setter
    def type(self, type: SessionType):
        """Sets the type of this Session.


        :param type: The type of this Session.
        :type type: SessionType
        """

        self._type = type

    @property
    def name(self) -> str:
        """Gets the name of this Session.


        :return: The name of this Session.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Session.


        :param name: The name of this Session.
        :type name: str
        """

        self._name = name

    @property
    def machine(self) -> str:
        """Gets the machine of this Session.


        :return: The machine of this Session.
        :rtype: str
        """
        return self._machine

    @machine.setter
    def machine(self, machine: str):
        """Sets the machine of this Session.


        :param machine: The machine of this Session.
        :type machine: str
        """

        self._machine = machine

    @property
    def console(self) -> Console:
        """Gets the console of this Session.


        :return: The console of this Session.
        :rtype: Console
        """
        return self._console

    @console.setter
    def console(self, console: Console):
        """Sets the console of this Session.


        :param console: The console of this Session.
        :type console: Console
        """

        self._console = console
