# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401


from vbox_server.models.base_model_ import Model
from vbox_server import util


class SyntheticServerAuthenticateRequestBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, user: str=None, password: str=None, jwt: str=None):  # noqa: E501
        """SyntheticServerAuthenticateRequestBody - a model defined in Swagger

        :param user: The user of this SyntheticServerAuthenticateRequestBody.  # noqa: E501
        :type user: str
        :param password: The password of this SyntheticServerAuthenticateRequestBody.  # noqa: E501
        :type password: str
        :param jwt: The jwt of this SyntheticServerAuthenticateRequestBody.  # noqa: E501
        :type jwt: str
        """
        self.swagger_types = {
            'user': str,
            'password': str,
            'jwt': str
        }

        self.attribute_map = {
            'user': 'user',
            'password': 'password',
            'jwt': 'jwt'
        }

        self._user = user
        self._password = password
        self._jwt = jwt

    @classmethod
    def from_dict(cls, dikt) -> 'SyntheticServerAuthenticateRequestBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SyntheticServerAuthenticateRequestBody of this SyntheticServerAuthenticateRequestBody.  # noqa: E501
        :rtype: SyntheticServerAuthenticateRequestBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def user(self) -> str:
        """Gets the user of this SyntheticServerAuthenticateRequestBody.


        :return: The user of this SyntheticServerAuthenticateRequestBody.
        :rtype: str
        """
        return self._user

    @user.setter
    def user(self, user: str):
        """Sets the user of this SyntheticServerAuthenticateRequestBody.


        :param user: The user of this SyntheticServerAuthenticateRequestBody.
        :type user: str
        """

        self._user = user

    @property
    def password(self) -> str:
        """Gets the password of this SyntheticServerAuthenticateRequestBody.


        :return: The password of this SyntheticServerAuthenticateRequestBody.
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password: str):
        """Sets the password of this SyntheticServerAuthenticateRequestBody.


        :param password: The password of this SyntheticServerAuthenticateRequestBody.
        :type password: str
        """

        self._password = password

    @property
    def jwt(self) -> str:
        """Gets the jwt of this SyntheticServerAuthenticateRequestBody.


        :return: The jwt of this SyntheticServerAuthenticateRequestBody.
        :rtype: str
        """
        return self._jwt

    @jwt.setter
    def jwt(self, jwt: str):
        """Sets the jwt of this SyntheticServerAuthenticateRequestBody.


        :param jwt: The jwt of this SyntheticServerAuthenticateRequestBody.
        :type jwt: str
        """

        self._jwt = jwt
