# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401


from vbox_server.models.base_model_ import Model
from vbox_server import util


class UefiVariableAttributes(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    NONE = "NONE"
    NONVOLATILE = "NONVOLATILE"
    BOOTSERVICEACCESS = "BOOTSERVICEACCESS"
    RUNTIMEACCESS = "RUNTIMEACCESS"
    HWERRORRECORD = "HWERRORRECORD"
    AUTHWRITEACCESS = "AUTHWRITEACCESS"
    AUTHTIMEBASEDWRITEACCESS = "AUTHTIMEBASEDWRITEACCESS"
    AUTHAPPENDWRITE = "AUTHAPPENDWRITE"

    def __init__(self):  # noqa: E501
        """UefiVariableAttributes - a model defined in Swagger

        """
        self.swagger_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'UefiVariableAttributes':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UefiVariableAttributes of this UefiVariableAttributes.  # noqa: E501
        :rtype: UefiVariableAttributes
        """
        return util.deserialize_model(dikt, cls)
