# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401


from vbox_server.models.base_model_ import Model
from vbox_server import util


class USBProxyBackend(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, name: str=None, type: str=None):  # noqa: E501
        """USBProxyBackend - a model defined in Swagger

        :param name: The name of this USBProxyBackend.  # noqa: E501
        :type name: str
        :param type: The type of this USBProxyBackend.  # noqa: E501
        :type type: str
        """
        self.swagger_types = {
            'name': str,
            'type': str
        }

        self.attribute_map = {
            'name': 'name',
            'type': 'type'
        }

        self._name = name
        self._type = type

    @classmethod
    def from_dict(cls, dikt) -> 'USBProxyBackend':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The USBProxyBackend of this USBProxyBackend.  # noqa: E501
        :rtype: USBProxyBackend
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this USBProxyBackend.


        :return: The name of this USBProxyBackend.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this USBProxyBackend.


        :param name: The name of this USBProxyBackend.
        :type name: str
        """

        self._name = name

    @property
    def type(self) -> str:
        """Gets the type of this USBProxyBackend.


        :return: The type of this USBProxyBackend.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this USBProxyBackend.


        :param type: The type of this USBProxyBackend.
        :type type: str
        """

        self._type = type
