# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401


from vbox_server.models.base_model_ import Model
from vbox_server.models.usb_device_filter import USBDeviceFilter
from vbox_server import util


class USBDeviceFilters(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, device_filters: List[USBDeviceFilter]=None):  # noqa: E501
        """USBDeviceFilters - a model defined in Swagger

        :param device_filters: The device_filters of this USBDeviceFilters.  # noqa: E501
        :type device_filters: List[USBDeviceFilter]
        """
        self.swagger_types = {
            'device_filters': List[USBDeviceFilter]
        }

        self.attribute_map = {
            'device_filters': 'deviceFilters'
        }

        self._device_filters = device_filters

    @classmethod
    def from_dict(cls, dikt) -> 'USBDeviceFilters':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The USBDeviceFilters of this USBDeviceFilters.  # noqa: E501
        :rtype: USBDeviceFilters
        """
        return util.deserialize_model(dikt, cls)

    @property
    def device_filters(self) -> List[USBDeviceFilter]:
        """Gets the device_filters of this USBDeviceFilters.


        :return: The device_filters of this USBDeviceFilters.
        :rtype: List[USBDeviceFilter]
        """
        return self._device_filters

    @device_filters.setter
    def device_filters(self, device_filters: List[USBDeviceFilter]):
        """Sets the device_filters of this USBDeviceFilters.


        :param device_filters: The device_filters of this USBDeviceFilters.
        :type device_filters: List[USBDeviceFilter]
        """

        self._device_filters = device_filters
