# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401


from vbox_server.models.base_model_ import Model
from vbox_server import util


class VirtualboxCheckfirmwarepresentResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, url: str=None, file: str=None, result: bool=None):  # noqa: E501
        """VirtualboxCheckfirmwarepresentResponse - a model defined in Swagger

        :param url: The url of this VirtualboxCheckfirmwarepresentResponse.  # noqa: E501
        :type url: str
        :param file: The file of this VirtualboxCheckfirmwarepresentResponse.  # noqa: E501
        :type file: str
        :param result: The result of this VirtualboxCheckfirmwarepresentResponse.  # noqa: E501
        :type result: bool
        """
        self.swagger_types = {
            'url': str,
            'file': str,
            'result': bool
        }

        self.attribute_map = {
            'url': 'url',
            'file': 'file',
            'result': 'result'
        }

        self._url = url
        self._file = file
        self._result = result

    @classmethod
    def from_dict(cls, dikt) -> 'VirtualboxCheckfirmwarepresentResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The virtualbox_checkfirmwarepresent_response of this VirtualboxCheckfirmwarepresentResponse.  # noqa: E501
        :rtype: VirtualboxCheckfirmwarepresentResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def url(self) -> str:
        """Gets the url of this VirtualboxCheckfirmwarepresentResponse.


        :return: The url of this VirtualboxCheckfirmwarepresentResponse.
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url: str):
        """Sets the url of this VirtualboxCheckfirmwarepresentResponse.


        :param url: The url of this VirtualboxCheckfirmwarepresentResponse.
        :type url: str
        """

        self._url = url

    @property
    def file(self) -> str:
        """Gets the file of this VirtualboxCheckfirmwarepresentResponse.


        :return: The file of this VirtualboxCheckfirmwarepresentResponse.
        :rtype: str
        """
        return self._file

    @file.setter
    def file(self, file: str):
        """Sets the file of this VirtualboxCheckfirmwarepresentResponse.


        :param file: The file of this VirtualboxCheckfirmwarepresentResponse.
        :type file: str
        """

        self._file = file

    @property
    def result(self) -> bool:
        """Gets the result of this VirtualboxCheckfirmwarepresentResponse.


        :return: The result of this VirtualboxCheckfirmwarepresentResponse.
        :rtype: bool
        """
        return self._result

    @result.setter
    def result(self, result: bool):
        """Sets the result of this VirtualboxCheckfirmwarepresentResponse.


        :param result: The result of this VirtualboxCheckfirmwarepresentResponse.
        :type result: bool
        """

        self._result = result
