# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401


from vbox_server.models.base_model_ import Model
from vbox_server import util


class VirtualboxGetguestossubtypesbyfamilyidResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, o_ssubtypes: List[str]=None):  # noqa: E501
        """VirtualboxGetguestossubtypesbyfamilyidResponse - a model defined in Swagger

        :param o_ssubtypes: The o_ssubtypes of this VirtualboxGetguestossubtypesbyfamilyidResponse.  # noqa: E501
        :type o_ssubtypes: List[str]
        """
        self.swagger_types = {
            'o_ssubtypes': List[str]
        }

        self.attribute_map = {
            'o_ssubtypes': 'OSsubtypes'
        }

        self._o_ssubtypes = o_ssubtypes

    @classmethod
    def from_dict(cls, dikt) -> 'VirtualboxGetguestossubtypesbyfamilyidResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The virtualbox_getguestossubtypesbyfamilyid_response of this VirtualboxGetguestossubtypesbyfamilyidResponse.  # noqa: E501
        :rtype: VirtualboxGetguestossubtypesbyfamilyidResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def o_ssubtypes(self) -> List[str]:
        """Gets the o_ssubtypes of this VirtualboxGetguestossubtypesbyfamilyidResponse.


        :return: The o_ssubtypes of this VirtualboxGetguestossubtypesbyfamilyidResponse.
        :rtype: List[str]
        """
        return self._o_ssubtypes

    @o_ssubtypes.setter
    def o_ssubtypes(self, o_ssubtypes: List[str]):
        """Sets the o_ssubtypes of this VirtualboxGetguestossubtypesbyfamilyidResponse.


        :param o_ssubtypes: The o_ssubtypes of this VirtualboxGetguestossubtypesbyfamilyidResponse.
        :type o_ssubtypes: List[str]
        """

        self._o_ssubtypes = o_ssubtypes
