# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401


from vbox_server.models.base_model_ import Model
from vbox_server.models.cloud_network import CloudNetwork
from vbox_server.models.cloud_provider_manager import CloudProviderManager
from vbox_server.models.dhcp_server import DHCPServer
from vbox_server.models.event_source import EventSource
from vbox_server.models.guest_os_type import GuestOSType
from vbox_server.models.host import Host
from vbox_server.models.host_only_network import HostOnlyNetwork
from vbox_server.models.machine import Machine
from vbox_server.models.medium import Medium
from vbox_server.models.nat_network import NATNetwork
from vbox_server.models.progress import Progress
from vbox_server.models.shared_folder import SharedFolder
from vbox_server.models.system_properties import SystemProperties
from vbox_server import util


class VirtualBox(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, version: str=None, version_normalized: str=None, revision: int=None, package_type: str=None, api_version: str=None, api_revision: int=None, home_folder: str=None, settings_file_path: str=None, host: Host=None, system_properties: SystemProperties=None, machines: List[Machine]=None, machine_groups: List[str]=None, hard_disks: List[Medium]=None, dvd_images: List[Medium]=None, floppy_images: List[Medium]=None, progress_operations: List[Progress]=None, guest_os_types: List[GuestOSType]=None, guest_os_families: List[str]=None, shared_folders: List[SharedFolder]=None, dhcp_servers: List[DHCPServer]=None, nat_networks: List[NATNetwork]=None, event_source: EventSource=None, internal_networks: List[str]=None, host_only_networks: List[HostOnlyNetwork]=None, generic_network_drivers: List[str]=None, cloud_networks: List[CloudNetwork]=None, cloud_provider_manager: CloudProviderManager=None):  # noqa: E501
        """VirtualBox - a model defined in Swagger

        :param version: The version of this VirtualBox.  # noqa: E501
        :type version: str
        :param version_normalized: The version_normalized of this VirtualBox.  # noqa: E501
        :type version_normalized: str
        :param revision: The revision of this VirtualBox.  # noqa: E501
        :type revision: int
        :param package_type: The package_type of this VirtualBox.  # noqa: E501
        :type package_type: str
        :param api_version: The api_version of this VirtualBox.  # noqa: E501
        :type api_version: str
        :param api_revision: The api_revision of this VirtualBox.  # noqa: E501
        :type api_revision: int
        :param home_folder: The home_folder of this VirtualBox.  # noqa: E501
        :type home_folder: str
        :param settings_file_path: The settings_file_path of this VirtualBox.  # noqa: E501
        :type settings_file_path: str
        :param host: The host of this VirtualBox.  # noqa: E501
        :type host: Host
        :param system_properties: The system_properties of this VirtualBox.  # noqa: E501
        :type system_properties: SystemProperties
        :param machines: The machines of this VirtualBox.  # noqa: E501
        :type machines: List[Machine]
        :param machine_groups: The machine_groups of this VirtualBox.  # noqa: E501
        :type machine_groups: List[str]
        :param hard_disks: The hard_disks of this VirtualBox.  # noqa: E501
        :type hard_disks: List[Medium]
        :param dvd_images: The dvd_images of this VirtualBox.  # noqa: E501
        :type dvd_images: List[Medium]
        :param floppy_images: The floppy_images of this VirtualBox.  # noqa: E501
        :type floppy_images: List[Medium]
        :param progress_operations: The progress_operations of this VirtualBox.  # noqa: E501
        :type progress_operations: List[Progress]
        :param guest_os_types: The guest_os_types of this VirtualBox.  # noqa: E501
        :type guest_os_types: List[GuestOSType]
        :param guest_os_families: The guest_os_families of this VirtualBox.  # noqa: E501
        :type guest_os_families: List[str]
        :param shared_folders: The shared_folders of this VirtualBox.  # noqa: E501
        :type shared_folders: List[SharedFolder]
        :param dhcp_servers: The dhcp_servers of this VirtualBox.  # noqa: E501
        :type dhcp_servers: List[DHCPServer]
        :param nat_networks: The nat_networks of this VirtualBox.  # noqa: E501
        :type nat_networks: List[NATNetwork]
        :param event_source: The event_source of this VirtualBox.  # noqa: E501
        :type event_source: EventSource
        :param internal_networks: The internal_networks of this VirtualBox.  # noqa: E501
        :type internal_networks: List[str]
        :param host_only_networks: The host_only_networks of this VirtualBox.  # noqa: E501
        :type host_only_networks: List[HostOnlyNetwork]
        :param generic_network_drivers: The generic_network_drivers of this VirtualBox.  # noqa: E501
        :type generic_network_drivers: List[str]
        :param cloud_networks: The cloud_networks of this VirtualBox.  # noqa: E501
        :type cloud_networks: List[CloudNetwork]
        :param cloud_provider_manager: The cloud_provider_manager of this VirtualBox.  # noqa: E501
        :type cloud_provider_manager: CloudProviderManager
        """
        self.swagger_types = {
            'version': str,
            'version_normalized': str,
            'revision': int,
            'package_type': str,
            'api_version': str,
            'api_revision': int,
            'home_folder': str,
            'settings_file_path': str,
            'host': Host,
            'system_properties': SystemProperties,
            'machines': List[Machine],
            'machine_groups': List[str],
            'hard_disks': List[Medium],
            'dvd_images': List[Medium],
            'floppy_images': List[Medium],
            'progress_operations': List[Progress],
            'guest_os_types': List[GuestOSType],
            'guest_os_families': List[str],
            'shared_folders': List[SharedFolder],
            'dhcp_servers': List[DHCPServer],
            'nat_networks': List[NATNetwork],
            'event_source': EventSource,
            'internal_networks': List[str],
            'host_only_networks': List[HostOnlyNetwork],
            'generic_network_drivers': List[str],
            'cloud_networks': List[CloudNetwork],
            'cloud_provider_manager': CloudProviderManager
        }

        self.attribute_map = {
            'version': 'version',
            'version_normalized': 'versionNormalized',
            'revision': 'revision',
            'package_type': 'packageType',
            'api_version': 'APIVersion',
            'api_revision': 'APIRevision',
            'home_folder': 'homeFolder',
            'settings_file_path': 'settingsFilePath',
            'host': 'host',
            'system_properties': 'systemProperties',
            'machines': 'machines',
            'machine_groups': 'machineGroups',
            'hard_disks': 'hardDisks',
            'dvd_images': 'DVDImages',
            'floppy_images': 'floppyImages',
            'progress_operations': 'progressOperations',
            'guest_os_types': 'guestOSTypes',
            'guest_os_families': 'guestOSFamilies',
            'shared_folders': 'sharedFolders',
            'dhcp_servers': 'DHCPServers',
            'nat_networks': 'NATNetworks',
            'event_source': 'eventSource',
            'internal_networks': 'internalNetworks',
            'host_only_networks': 'hostOnlyNetworks',
            'generic_network_drivers': 'genericNetworkDrivers',
            'cloud_networks': 'cloudNetworks',
            'cloud_provider_manager': 'cloudProviderManager'
        }

        self._version = version
        self._version_normalized = version_normalized
        self._revision = revision
        self._package_type = package_type
        self._api_version = api_version
        self._api_revision = api_revision
        self._home_folder = home_folder
        self._settings_file_path = settings_file_path
        self._host = host
        self._system_properties = system_properties
        self._machines = machines
        self._machine_groups = machine_groups
        self._hard_disks = hard_disks
        self._dvd_images = dvd_images
        self._floppy_images = floppy_images
        self._progress_operations = progress_operations
        self._guest_os_types = guest_os_types
        self._guest_os_families = guest_os_families
        self._shared_folders = shared_folders
        self._dhcp_servers = dhcp_servers
        self._nat_networks = nat_networks
        self._event_source = event_source
        self._internal_networks = internal_networks
        self._host_only_networks = host_only_networks
        self._generic_network_drivers = generic_network_drivers
        self._cloud_networks = cloud_networks
        self._cloud_provider_manager = cloud_provider_manager

    @classmethod
    def from_dict(cls, dikt) -> 'VirtualBox':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The VirtualBox of this VirtualBox.  # noqa: E501
        :rtype: VirtualBox
        """
        return util.deserialize_model(dikt, cls)

    @property
    def version(self) -> str:
        """Gets the version of this VirtualBox.


        :return: The version of this VirtualBox.
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version: str):
        """Sets the version of this VirtualBox.


        :param version: The version of this VirtualBox.
        :type version: str
        """

        self._version = version

    @property
    def version_normalized(self) -> str:
        """Gets the version_normalized of this VirtualBox.


        :return: The version_normalized of this VirtualBox.
        :rtype: str
        """
        return self._version_normalized

    @version_normalized.setter
    def version_normalized(self, version_normalized: str):
        """Sets the version_normalized of this VirtualBox.


        :param version_normalized: The version_normalized of this VirtualBox.
        :type version_normalized: str
        """

        self._version_normalized = version_normalized

    @property
    def revision(self) -> int:
        """Gets the revision of this VirtualBox.


        :return: The revision of this VirtualBox.
        :rtype: int
        """
        return self._revision

    @revision.setter
    def revision(self, revision: int):
        """Sets the revision of this VirtualBox.


        :param revision: The revision of this VirtualBox.
        :type revision: int
        """

        self._revision = revision

    @property
    def package_type(self) -> str:
        """Gets the package_type of this VirtualBox.


        :return: The package_type of this VirtualBox.
        :rtype: str
        """
        return self._package_type

    @package_type.setter
    def package_type(self, package_type: str):
        """Sets the package_type of this VirtualBox.


        :param package_type: The package_type of this VirtualBox.
        :type package_type: str
        """

        self._package_type = package_type

    @property
    def api_version(self) -> str:
        """Gets the api_version of this VirtualBox.


        :return: The api_version of this VirtualBox.
        :rtype: str
        """
        return self._api_version

    @api_version.setter
    def api_version(self, api_version: str):
        """Sets the api_version of this VirtualBox.


        :param api_version: The api_version of this VirtualBox.
        :type api_version: str
        """

        self._api_version = api_version

    @property
    def api_revision(self) -> int:
        """Gets the api_revision of this VirtualBox.


        :return: The api_revision of this VirtualBox.
        :rtype: int
        """
        return self._api_revision

    @api_revision.setter
    def api_revision(self, api_revision: int):
        """Sets the api_revision of this VirtualBox.


        :param api_revision: The api_revision of this VirtualBox.
        :type api_revision: int
        """

        self._api_revision = api_revision

    @property
    def home_folder(self) -> str:
        """Gets the home_folder of this VirtualBox.


        :return: The home_folder of this VirtualBox.
        :rtype: str
        """
        return self._home_folder

    @home_folder.setter
    def home_folder(self, home_folder: str):
        """Sets the home_folder of this VirtualBox.


        :param home_folder: The home_folder of this VirtualBox.
        :type home_folder: str
        """

        self._home_folder = home_folder

    @property
    def settings_file_path(self) -> str:
        """Gets the settings_file_path of this VirtualBox.


        :return: The settings_file_path of this VirtualBox.
        :rtype: str
        """
        return self._settings_file_path

    @settings_file_path.setter
    def settings_file_path(self, settings_file_path: str):
        """Sets the settings_file_path of this VirtualBox.


        :param settings_file_path: The settings_file_path of this VirtualBox.
        :type settings_file_path: str
        """

        self._settings_file_path = settings_file_path

    @property
    def host(self) -> Host:
        """Gets the host of this VirtualBox.


        :return: The host of this VirtualBox.
        :rtype: Host
        """
        return self._host

    @host.setter
    def host(self, host: Host):
        """Sets the host of this VirtualBox.


        :param host: The host of this VirtualBox.
        :type host: Host
        """

        self._host = host

    @property
    def system_properties(self) -> SystemProperties:
        """Gets the system_properties of this VirtualBox.


        :return: The system_properties of this VirtualBox.
        :rtype: SystemProperties
        """
        return self._system_properties

    @system_properties.setter
    def system_properties(self, system_properties: SystemProperties):
        """Sets the system_properties of this VirtualBox.


        :param system_properties: The system_properties of this VirtualBox.
        :type system_properties: SystemProperties
        """

        self._system_properties = system_properties

    @property
    def machines(self) -> List[Machine]:
        """Gets the machines of this VirtualBox.


        :return: The machines of this VirtualBox.
        :rtype: List[Machine]
        """
        return self._machines

    @machines.setter
    def machines(self, machines: List[Machine]):
        """Sets the machines of this VirtualBox.


        :param machines: The machines of this VirtualBox.
        :type machines: List[Machine]
        """

        self._machines = machines

    @property
    def machine_groups(self) -> List[str]:
        """Gets the machine_groups of this VirtualBox.


        :return: The machine_groups of this VirtualBox.
        :rtype: List[str]
        """
        return self._machine_groups

    @machine_groups.setter
    def machine_groups(self, machine_groups: List[str]):
        """Sets the machine_groups of this VirtualBox.


        :param machine_groups: The machine_groups of this VirtualBox.
        :type machine_groups: List[str]
        """

        self._machine_groups = machine_groups

    @property
    def hard_disks(self) -> List[Medium]:
        """Gets the hard_disks of this VirtualBox.


        :return: The hard_disks of this VirtualBox.
        :rtype: List[Medium]
        """
        return self._hard_disks

    @hard_disks.setter
    def hard_disks(self, hard_disks: List[Medium]):
        """Sets the hard_disks of this VirtualBox.


        :param hard_disks: The hard_disks of this VirtualBox.
        :type hard_disks: List[Medium]
        """

        self._hard_disks = hard_disks

    @property
    def dvd_images(self) -> List[Medium]:
        """Gets the dvd_images of this VirtualBox.


        :return: The dvd_images of this VirtualBox.
        :rtype: List[Medium]
        """
        return self._dvd_images

    @dvd_images.setter
    def dvd_images(self, dvd_images: List[Medium]):
        """Sets the dvd_images of this VirtualBox.


        :param dvd_images: The dvd_images of this VirtualBox.
        :type dvd_images: List[Medium]
        """

        self._dvd_images = dvd_images

    @property
    def floppy_images(self) -> List[Medium]:
        """Gets the floppy_images of this VirtualBox.


        :return: The floppy_images of this VirtualBox.
        :rtype: List[Medium]
        """
        return self._floppy_images

    @floppy_images.setter
    def floppy_images(self, floppy_images: List[Medium]):
        """Sets the floppy_images of this VirtualBox.


        :param floppy_images: The floppy_images of this VirtualBox.
        :type floppy_images: List[Medium]
        """

        self._floppy_images = floppy_images

    @property
    def progress_operations(self) -> List[Progress]:
        """Gets the progress_operations of this VirtualBox.


        :return: The progress_operations of this VirtualBox.
        :rtype: List[Progress]
        """
        return self._progress_operations

    @progress_operations.setter
    def progress_operations(self, progress_operations: List[Progress]):
        """Sets the progress_operations of this VirtualBox.


        :param progress_operations: The progress_operations of this VirtualBox.
        :type progress_operations: List[Progress]
        """

        self._progress_operations = progress_operations

    @property
    def guest_os_types(self) -> List[GuestOSType]:
        """Gets the guest_os_types of this VirtualBox.


        :return: The guest_os_types of this VirtualBox.
        :rtype: List[GuestOSType]
        """
        return self._guest_os_types

    @guest_os_types.setter
    def guest_os_types(self, guest_os_types: List[GuestOSType]):
        """Sets the guest_os_types of this VirtualBox.


        :param guest_os_types: The guest_os_types of this VirtualBox.
        :type guest_os_types: List[GuestOSType]
        """

        self._guest_os_types = guest_os_types

    @property
    def guest_os_families(self) -> List[str]:
        """Gets the guest_os_families of this VirtualBox.


        :return: The guest_os_families of this VirtualBox.
        :rtype: List[str]
        """
        return self._guest_os_families

    @guest_os_families.setter
    def guest_os_families(self, guest_os_families: List[str]):
        """Sets the guest_os_families of this VirtualBox.


        :param guest_os_families: The guest_os_families of this VirtualBox.
        :type guest_os_families: List[str]
        """

        self._guest_os_families = guest_os_families

    @property
    def shared_folders(self) -> List[SharedFolder]:
        """Gets the shared_folders of this VirtualBox.


        :return: The shared_folders of this VirtualBox.
        :rtype: List[SharedFolder]
        """
        return self._shared_folders

    @shared_folders.setter
    def shared_folders(self, shared_folders: List[SharedFolder]):
        """Sets the shared_folders of this VirtualBox.


        :param shared_folders: The shared_folders of this VirtualBox.
        :type shared_folders: List[SharedFolder]
        """

        self._shared_folders = shared_folders

    @property
    def dhcp_servers(self) -> List[DHCPServer]:
        """Gets the dhcp_servers of this VirtualBox.


        :return: The dhcp_servers of this VirtualBox.
        :rtype: List[DHCPServer]
        """
        return self._dhcp_servers

    @dhcp_servers.setter
    def dhcp_servers(self, dhcp_servers: List[DHCPServer]):
        """Sets the dhcp_servers of this VirtualBox.


        :param dhcp_servers: The dhcp_servers of this VirtualBox.
        :type dhcp_servers: List[DHCPServer]
        """

        self._dhcp_servers = dhcp_servers

    @property
    def nat_networks(self) -> List[NATNetwork]:
        """Gets the nat_networks of this VirtualBox.


        :return: The nat_networks of this VirtualBox.
        :rtype: List[NATNetwork]
        """
        return self._nat_networks

    @nat_networks.setter
    def nat_networks(self, nat_networks: List[NATNetwork]):
        """Sets the nat_networks of this VirtualBox.


        :param nat_networks: The nat_networks of this VirtualBox.
        :type nat_networks: List[NATNetwork]
        """

        self._nat_networks = nat_networks

    @property
    def event_source(self) -> EventSource:
        """Gets the event_source of this VirtualBox.


        :return: The event_source of this VirtualBox.
        :rtype: EventSource
        """
        return self._event_source

    @event_source.setter
    def event_source(self, event_source: EventSource):
        """Sets the event_source of this VirtualBox.


        :param event_source: The event_source of this VirtualBox.
        :type event_source: EventSource
        """

        self._event_source = event_source

    @property
    def internal_networks(self) -> List[str]:
        """Gets the internal_networks of this VirtualBox.


        :return: The internal_networks of this VirtualBox.
        :rtype: List[str]
        """
        return self._internal_networks

    @internal_networks.setter
    def internal_networks(self, internal_networks: List[str]):
        """Sets the internal_networks of this VirtualBox.


        :param internal_networks: The internal_networks of this VirtualBox.
        :type internal_networks: List[str]
        """

        self._internal_networks = internal_networks

    @property
    def host_only_networks(self) -> List[HostOnlyNetwork]:
        """Gets the host_only_networks of this VirtualBox.


        :return: The host_only_networks of this VirtualBox.
        :rtype: List[HostOnlyNetwork]
        """
        return self._host_only_networks

    @host_only_networks.setter
    def host_only_networks(self, host_only_networks: List[HostOnlyNetwork]):
        """Sets the host_only_networks of this VirtualBox.


        :param host_only_networks: The host_only_networks of this VirtualBox.
        :type host_only_networks: List[HostOnlyNetwork]
        """

        self._host_only_networks = host_only_networks

    @property
    def generic_network_drivers(self) -> List[str]:
        """Gets the generic_network_drivers of this VirtualBox.


        :return: The generic_network_drivers of this VirtualBox.
        :rtype: List[str]
        """
        return self._generic_network_drivers

    @generic_network_drivers.setter
    def generic_network_drivers(self, generic_network_drivers: List[str]):
        """Sets the generic_network_drivers of this VirtualBox.


        :param generic_network_drivers: The generic_network_drivers of this VirtualBox.
        :type generic_network_drivers: List[str]
        """

        self._generic_network_drivers = generic_network_drivers

    @property
    def cloud_networks(self) -> List[CloudNetwork]:
        """Gets the cloud_networks of this VirtualBox.


        :return: The cloud_networks of this VirtualBox.
        :rtype: List[CloudNetwork]
        """
        return self._cloud_networks

    @cloud_networks.setter
    def cloud_networks(self, cloud_networks: List[CloudNetwork]):
        """Sets the cloud_networks of this VirtualBox.


        :param cloud_networks: The cloud_networks of this VirtualBox.
        :type cloud_networks: List[CloudNetwork]
        """

        self._cloud_networks = cloud_networks

    @property
    def cloud_provider_manager(self) -> CloudProviderManager:
        """Gets the cloud_provider_manager of this VirtualBox.


        :return: The cloud_provider_manager of this VirtualBox.
        :rtype: CloudProviderManager
        """
        return self._cloud_provider_manager

    @cloud_provider_manager.setter
    def cloud_provider_manager(self, cloud_provider_manager: CloudProviderManager):
        """Sets the cloud_provider_manager of this VirtualBox.


        :param cloud_provider_manager: The cloud_provider_manager of this VirtualBox.
        :type cloud_provider_manager: CloudProviderManager
        """

        self._cloud_provider_manager = cloud_provider_manager
