# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401


from vbox_server.models.base_model_ import Model
from vbox_server.models.access_mode import AccessMode
from vbox_server.models.device_type import DeviceType
from vbox_server import util


class VirtualBoxOpenMediumRequestBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, location: str=None, device_type: DeviceType=None, access_mode: AccessMode=None, force_new_uuid: bool=None):  # noqa: E501
        """VirtualBoxOpenMediumRequestBody - a model defined in Swagger

        :param location: The location of this VirtualBoxOpenMediumRequestBody.  # noqa: E501
        :type location: str
        :param device_type: The device_type of this VirtualBoxOpenMediumRequestBody.  # noqa: E501
        :type device_type: DeviceType
        :param access_mode: The access_mode of this VirtualBoxOpenMediumRequestBody.  # noqa: E501
        :type access_mode: AccessMode
        :param force_new_uuid: The force_new_uuid of this VirtualBoxOpenMediumRequestBody.  # noqa: E501
        :type force_new_uuid: bool
        """
        self.swagger_types = {
            'location': str,
            'device_type': DeviceType,
            'access_mode': AccessMode,
            'force_new_uuid': bool
        }

        self.attribute_map = {
            'location': 'location',
            'device_type': 'deviceType',
            'access_mode': 'accessMode',
            'force_new_uuid': 'forceNewUuid'
        }

        self._location = location
        self._device_type = device_type
        self._access_mode = access_mode
        self._force_new_uuid = force_new_uuid

    @classmethod
    def from_dict(cls, dikt) -> 'VirtualBoxOpenMediumRequestBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The VirtualBoxOpenMediumRequestBody of this VirtualBoxOpenMediumRequestBody.  # noqa: E501
        :rtype: VirtualBoxOpenMediumRequestBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def location(self) -> str:
        """Gets the location of this VirtualBoxOpenMediumRequestBody.


        :return: The location of this VirtualBoxOpenMediumRequestBody.
        :rtype: str
        """
        return self._location

    @location.setter
    def location(self, location: str):
        """Sets the location of this VirtualBoxOpenMediumRequestBody.


        :param location: The location of this VirtualBoxOpenMediumRequestBody.
        :type location: str
        """

        self._location = location

    @property
    def device_type(self) -> DeviceType:
        """Gets the device_type of this VirtualBoxOpenMediumRequestBody.


        :return: The device_type of this VirtualBoxOpenMediumRequestBody.
        :rtype: DeviceType
        """
        return self._device_type

    @device_type.setter
    def device_type(self, device_type: DeviceType):
        """Sets the device_type of this VirtualBoxOpenMediumRequestBody.


        :param device_type: The device_type of this VirtualBoxOpenMediumRequestBody.
        :type device_type: DeviceType
        """

        self._device_type = device_type

    @property
    def access_mode(self) -> AccessMode:
        """Gets the access_mode of this VirtualBoxOpenMediumRequestBody.


        :return: The access_mode of this VirtualBoxOpenMediumRequestBody.
        :rtype: AccessMode
        """
        return self._access_mode

    @access_mode.setter
    def access_mode(self, access_mode: AccessMode):
        """Sets the access_mode of this VirtualBoxOpenMediumRequestBody.


        :param access_mode: The access_mode of this VirtualBoxOpenMediumRequestBody.
        :type access_mode: AccessMode
        """

        self._access_mode = access_mode

    @property
    def force_new_uuid(self) -> bool:
        """Gets the force_new_uuid of this VirtualBoxOpenMediumRequestBody.


        :return: The force_new_uuid of this VirtualBoxOpenMediumRequestBody.
        :rtype: bool
        """
        return self._force_new_uuid

    @force_new_uuid.setter
    def force_new_uuid(self, force_new_uuid: bool):
        """Sets the force_new_uuid of this VirtualBoxOpenMediumRequestBody.


        :param force_new_uuid: The force_new_uuid of this VirtualBoxOpenMediumRequestBody.
        :type force_new_uuid: bool
        """

        self._force_new_uuid = force_new_uuid
