# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401


from vbox_server.models.base_model_ import Model
from vbox_server.models.auth_type import AuthType
from vbox_server import util


class VRDEServer(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, enabled: bool=None, auth_type: AuthType=None, auth_timeout: int=None, allow_multi_connection: bool=None, reuse_single_connection: bool=None, vrde_ext_pack: str=None, auth_library: str=None, vrde_properties: List[str]=None):  # noqa: E501
        """VRDEServer - a model defined in Swagger

        :param enabled: The enabled of this VRDEServer.  # noqa: E501
        :type enabled: bool
        :param auth_type: The auth_type of this VRDEServer.  # noqa: E501
        :type auth_type: AuthType
        :param auth_timeout: The auth_timeout of this VRDEServer.  # noqa: E501
        :type auth_timeout: int
        :param allow_multi_connection: The allow_multi_connection of this VRDEServer.  # noqa: E501
        :type allow_multi_connection: bool
        :param reuse_single_connection: The reuse_single_connection of this VRDEServer.  # noqa: E501
        :type reuse_single_connection: bool
        :param vrde_ext_pack: The vrde_ext_pack of this VRDEServer.  # noqa: E501
        :type vrde_ext_pack: str
        :param auth_library: The auth_library of this VRDEServer.  # noqa: E501
        :type auth_library: str
        :param vrde_properties: The vrde_properties of this VRDEServer.  # noqa: E501
        :type vrde_properties: List[str]
        """
        self.swagger_types = {
            'enabled': bool,
            'auth_type': AuthType,
            'auth_timeout': int,
            'allow_multi_connection': bool,
            'reuse_single_connection': bool,
            'vrde_ext_pack': str,
            'auth_library': str,
            'vrde_properties': List[str]
        }

        self.attribute_map = {
            'enabled': 'enabled',
            'auth_type': 'authType',
            'auth_timeout': 'authTimeout',
            'allow_multi_connection': 'allowMultiConnection',
            'reuse_single_connection': 'reuseSingleConnection',
            'vrde_ext_pack': 'VRDEExtPack',
            'auth_library': 'authLibrary',
            'vrde_properties': 'VRDEProperties'
        }

        self._enabled = enabled
        self._auth_type = auth_type
        self._auth_timeout = auth_timeout
        self._allow_multi_connection = allow_multi_connection
        self._reuse_single_connection = reuse_single_connection
        self._vrde_ext_pack = vrde_ext_pack
        self._auth_library = auth_library
        self._vrde_properties = vrde_properties

    @classmethod
    def from_dict(cls, dikt) -> 'VRDEServer':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The VRDEServer of this VRDEServer.  # noqa: E501
        :rtype: VRDEServer
        """
        return util.deserialize_model(dikt, cls)

    @property
    def enabled(self) -> bool:
        """Gets the enabled of this VRDEServer.


        :return: The enabled of this VRDEServer.
        :rtype: bool
        """
        return self._enabled

    @enabled.setter
    def enabled(self, enabled: bool):
        """Sets the enabled of this VRDEServer.


        :param enabled: The enabled of this VRDEServer.
        :type enabled: bool
        """

        self._enabled = enabled

    @property
    def auth_type(self) -> AuthType:
        """Gets the auth_type of this VRDEServer.


        :return: The auth_type of this VRDEServer.
        :rtype: AuthType
        """
        return self._auth_type

    @auth_type.setter
    def auth_type(self, auth_type: AuthType):
        """Sets the auth_type of this VRDEServer.


        :param auth_type: The auth_type of this VRDEServer.
        :type auth_type: AuthType
        """

        self._auth_type = auth_type

    @property
    def auth_timeout(self) -> int:
        """Gets the auth_timeout of this VRDEServer.


        :return: The auth_timeout of this VRDEServer.
        :rtype: int
        """
        return self._auth_timeout

    @auth_timeout.setter
    def auth_timeout(self, auth_timeout: int):
        """Sets the auth_timeout of this VRDEServer.


        :param auth_timeout: The auth_timeout of this VRDEServer.
        :type auth_timeout: int
        """

        self._auth_timeout = auth_timeout

    @property
    def allow_multi_connection(self) -> bool:
        """Gets the allow_multi_connection of this VRDEServer.


        :return: The allow_multi_connection of this VRDEServer.
        :rtype: bool
        """
        return self._allow_multi_connection

    @allow_multi_connection.setter
    def allow_multi_connection(self, allow_multi_connection: bool):
        """Sets the allow_multi_connection of this VRDEServer.


        :param allow_multi_connection: The allow_multi_connection of this VRDEServer.
        :type allow_multi_connection: bool
        """

        self._allow_multi_connection = allow_multi_connection

    @property
    def reuse_single_connection(self) -> bool:
        """Gets the reuse_single_connection of this VRDEServer.


        :return: The reuse_single_connection of this VRDEServer.
        :rtype: bool
        """
        return self._reuse_single_connection

    @reuse_single_connection.setter
    def reuse_single_connection(self, reuse_single_connection: bool):
        """Sets the reuse_single_connection of this VRDEServer.


        :param reuse_single_connection: The reuse_single_connection of this VRDEServer.
        :type reuse_single_connection: bool
        """

        self._reuse_single_connection = reuse_single_connection

    @property
    def vrde_ext_pack(self) -> str:
        """Gets the vrde_ext_pack of this VRDEServer.


        :return: The vrde_ext_pack of this VRDEServer.
        :rtype: str
        """
        return self._vrde_ext_pack

    @vrde_ext_pack.setter
    def vrde_ext_pack(self, vrde_ext_pack: str):
        """Sets the vrde_ext_pack of this VRDEServer.


        :param vrde_ext_pack: The vrde_ext_pack of this VRDEServer.
        :type vrde_ext_pack: str
        """

        self._vrde_ext_pack = vrde_ext_pack

    @property
    def auth_library(self) -> str:
        """Gets the auth_library of this VRDEServer.


        :return: The auth_library of this VRDEServer.
        :rtype: str
        """
        return self._auth_library

    @auth_library.setter
    def auth_library(self, auth_library: str):
        """Sets the auth_library of this VRDEServer.


        :param auth_library: The auth_library of this VRDEServer.
        :type auth_library: str
        """

        self._auth_library = auth_library

    @property
    def vrde_properties(self) -> List[str]:
        """Gets the vrde_properties of this VRDEServer.


        :return: The vrde_properties of this VRDEServer.
        :rtype: List[str]
        """
        return self._vrde_properties

    @vrde_properties.setter
    def vrde_properties(self, vrde_properties: List[str]):
        """Sets the vrde_properties of this VRDEServer.


        :param vrde_properties: The vrde_properties of this VRDEServer.
        :type vrde_properties: List[str]
        """

        self._vrde_properties = vrde_properties
