# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401


from vbox_server.models.base_model_ import Model
from vbox_server.models.cpu_architecture import CPUArchitecture
from vbox_server import util


class CPUProfile(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, name: str=None, full_name: str=None, architecture: CPUArchitecture=None):  # noqa: E501
        """CPUProfile - a model defined in Swagger

        :param name: The name of this CPUProfile.  # noqa: E501
        :type name: str
        :param full_name: The full_name of this CPUProfile.  # noqa: E501
        :type full_name: str
        :param architecture: The architecture of this CPUProfile.  # noqa: E501
        :type architecture: CPUArchitecture
        """
        self.swagger_types = {
            'name': str,
            'full_name': str,
            'architecture': CPUArchitecture
        }

        self.attribute_map = {
            'name': 'name',
            'full_name': 'fullName',
            'architecture': 'architecture'
        }

        self._name = name
        self._full_name = full_name
        self._architecture = architecture

    @classmethod
    def from_dict(cls, dikt) -> 'CPUProfile':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CPUProfile of this CPUProfile.  # noqa: E501
        :rtype: CPUProfile
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this CPUProfile.


        :return: The name of this CPUProfile.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this CPUProfile.


        :param name: The name of this CPUProfile.
        :type name: str
        """

        self._name = name

    @property
    def full_name(self) -> str:
        """Gets the full_name of this CPUProfile.


        :return: The full_name of this CPUProfile.
        :rtype: str
        """
        return self._full_name

    @full_name.setter
    def full_name(self, full_name: str):
        """Sets the full_name of this CPUProfile.


        :param full_name: The full_name of this CPUProfile.
        :type full_name: str
        """

        self._full_name = full_name

    @property
    def architecture(self) -> CPUArchitecture:
        """Gets the architecture of this CPUProfile.


        :return: The architecture of this CPUProfile.
        :rtype: CPUArchitecture
        """
        return self._architecture

    @architecture.setter
    def architecture(self, architecture: CPUArchitecture):
        """Sets the architecture of this CPUProfile.


        :param architecture: The architecture of this CPUProfile.
        :type architecture: CPUArchitecture
        """

        self._architecture = architecture
