# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401


from vbox_server.models.base_model_ import Model
from vbox_server import util


class DisplaySourceBitmap(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, screen_id: int=None):  # noqa: E501
        """DisplaySourceBitmap - a model defined in Swagger

        :param screen_id: The screen_id of this DisplaySourceBitmap.  # noqa: E501
        :type screen_id: int
        """
        self.swagger_types = {
            'screen_id': int
        }

        self.attribute_map = {
            'screen_id': 'screenId'
        }

        self._screen_id = screen_id

    @classmethod
    def from_dict(cls, dikt) -> 'DisplaySourceBitmap':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DisplaySourceBitmap of this DisplaySourceBitmap.  # noqa: E501
        :rtype: DisplaySourceBitmap
        """
        return util.deserialize_model(dikt, cls)

    @property
    def screen_id(self) -> int:
        """Gets the screen_id of this DisplaySourceBitmap.


        :return: The screen_id of this DisplaySourceBitmap.
        :rtype: int
        """
        return self._screen_id

    @screen_id.setter
    def screen_id(self, screen_id: int):
        """Sets the screen_id of this DisplaySourceBitmap.


        :param screen_id: The screen_id of this DisplaySourceBitmap.
        :type screen_id: int
        """

        self._screen_id = screen_id
