# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401


from vbox_server.models.base_model_ import Model
from vbox_server import util


class EventSource(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self):  # noqa: E501
        """EventSource - a model defined in Swagger

        """
        self.swagger_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'EventSource':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The EventSource of this EventSource.  # noqa: E501
        :rtype: EventSource
        """
        return util.deserialize_model(dikt, cls)
