# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401


from vbox_server.models.base_model_ import Model
from vbox_server.models.audio_device_state import AudioDeviceState
from vbox_server.models.audio_device_type import AudioDeviceType
from vbox_server.models.audio_direction import AudioDirection
from vbox_server import util


class HostAudioDevice(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, id: str=None, name: str=None, type: AudioDeviceType=None, usage: AudioDirection=None, default_in: bool=None, default_out: bool=None, is_hot_plug: bool=None, state: AudioDeviceState=None):  # noqa: E501
        """HostAudioDevice - a model defined in Swagger

        :param id: The id of this HostAudioDevice.  # noqa: E501
        :type id: str
        :param name: The name of this HostAudioDevice.  # noqa: E501
        :type name: str
        :param type: The type of this HostAudioDevice.  # noqa: E501
        :type type: AudioDeviceType
        :param usage: The usage of this HostAudioDevice.  # noqa: E501
        :type usage: AudioDirection
        :param default_in: The default_in of this HostAudioDevice.  # noqa: E501
        :type default_in: bool
        :param default_out: The default_out of this HostAudioDevice.  # noqa: E501
        :type default_out: bool
        :param is_hot_plug: The is_hot_plug of this HostAudioDevice.  # noqa: E501
        :type is_hot_plug: bool
        :param state: The state of this HostAudioDevice.  # noqa: E501
        :type state: AudioDeviceState
        """
        self.swagger_types = {
            'id': str,
            'name': str,
            'type': AudioDeviceType,
            'usage': AudioDirection,
            'default_in': bool,
            'default_out': bool,
            'is_hot_plug': bool,
            'state': AudioDeviceState
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'type': 'type',
            'usage': 'usage',
            'default_in': 'defaultIn',
            'default_out': 'defaultOut',
            'is_hot_plug': 'isHotPlug',
            'state': 'state'
        }

        self._id = id
        self._name = name
        self._type = type
        self._usage = usage
        self._default_in = default_in
        self._default_out = default_out
        self._is_hot_plug = is_hot_plug
        self._state = state

    @classmethod
    def from_dict(cls, dikt) -> 'HostAudioDevice':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The HostAudioDevice of this HostAudioDevice.  # noqa: E501
        :rtype: HostAudioDevice
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this HostAudioDevice.


        :return: The id of this HostAudioDevice.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this HostAudioDevice.


        :param id: The id of this HostAudioDevice.
        :type id: str
        """

        self._id = id

    @property
    def name(self) -> str:
        """Gets the name of this HostAudioDevice.


        :return: The name of this HostAudioDevice.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this HostAudioDevice.


        :param name: The name of this HostAudioDevice.
        :type name: str
        """

        self._name = name

    @property
    def type(self) -> AudioDeviceType:
        """Gets the type of this HostAudioDevice.


        :return: The type of this HostAudioDevice.
        :rtype: AudioDeviceType
        """
        return self._type

    @type.setter
    def type(self, type: AudioDeviceType):
        """Sets the type of this HostAudioDevice.


        :param type: The type of this HostAudioDevice.
        :type type: AudioDeviceType
        """

        self._type = type

    @property
    def usage(self) -> AudioDirection:
        """Gets the usage of this HostAudioDevice.


        :return: The usage of this HostAudioDevice.
        :rtype: AudioDirection
        """
        return self._usage

    @usage.setter
    def usage(self, usage: AudioDirection):
        """Sets the usage of this HostAudioDevice.


        :param usage: The usage of this HostAudioDevice.
        :type usage: AudioDirection
        """

        self._usage = usage

    @property
    def default_in(self) -> bool:
        """Gets the default_in of this HostAudioDevice.


        :return: The default_in of this HostAudioDevice.
        :rtype: bool
        """
        return self._default_in

    @default_in.setter
    def default_in(self, default_in: bool):
        """Sets the default_in of this HostAudioDevice.


        :param default_in: The default_in of this HostAudioDevice.
        :type default_in: bool
        """

        self._default_in = default_in

    @property
    def default_out(self) -> bool:
        """Gets the default_out of this HostAudioDevice.


        :return: The default_out of this HostAudioDevice.
        :rtype: bool
        """
        return self._default_out

    @default_out.setter
    def default_out(self, default_out: bool):
        """Sets the default_out of this HostAudioDevice.


        :param default_out: The default_out of this HostAudioDevice.
        :type default_out: bool
        """

        self._default_out = default_out

    @property
    def is_hot_plug(self) -> bool:
        """Gets the is_hot_plug of this HostAudioDevice.


        :return: The is_hot_plug of this HostAudioDevice.
        :rtype: bool
        """
        return self._is_hot_plug

    @is_hot_plug.setter
    def is_hot_plug(self, is_hot_plug: bool):
        """Sets the is_hot_plug of this HostAudioDevice.


        :param is_hot_plug: The is_hot_plug of this HostAudioDevice.
        :type is_hot_plug: bool
        """

        self._is_hot_plug = is_hot_plug

    @property
    def state(self) -> AudioDeviceState:
        """Gets the state of this HostAudioDevice.


        :return: The state of this HostAudioDevice.
        :rtype: AudioDeviceState
        """
        return self._state

    @state.setter
    def state(self, state: AudioDeviceState):
        """Sets the state of this HostAudioDevice.


        :param state: The state of this HostAudioDevice.
        :type state: AudioDeviceState
        """

        self._state = state
