# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401


from vbox_server.models.base_model_ import Model
from vbox_server.models.host_network_interface_medium_type import HostNetworkInterfaceMediumType
from vbox_server.models.host_network_interface_status import HostNetworkInterfaceStatus
from vbox_server.models.host_network_interface_type import HostNetworkInterfaceType
from vbox_server import util


class HostNetworkInterface(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, name: str=None, short_name: str=None, id: str=None, network_name: str=None, dhcp_enabled: bool=None, ip_address: str=None, network_mask: str=None, ipv6_supported: bool=None, ipv6_address: str=None, ipv6_network_mask_prefix_length: int=None, hardware_address: str=None, medium_type: HostNetworkInterfaceMediumType=None, status: HostNetworkInterfaceStatus=None, interface_type: HostNetworkInterfaceType=None, wireless: bool=None):  # noqa: E501
        """HostNetworkInterface - a model defined in Swagger

        :param name: The name of this HostNetworkInterface.  # noqa: E501
        :type name: str
        :param short_name: The short_name of this HostNetworkInterface.  # noqa: E501
        :type short_name: str
        :param id: The id of this HostNetworkInterface.  # noqa: E501
        :type id: str
        :param network_name: The network_name of this HostNetworkInterface.  # noqa: E501
        :type network_name: str
        :param dhcp_enabled: The dhcp_enabled of this HostNetworkInterface.  # noqa: E501
        :type dhcp_enabled: bool
        :param ip_address: The ip_address of this HostNetworkInterface.  # noqa: E501
        :type ip_address: str
        :param network_mask: The network_mask of this HostNetworkInterface.  # noqa: E501
        :type network_mask: str
        :param ipv6_supported: The ipv6_supported of this HostNetworkInterface.  # noqa: E501
        :type ipv6_supported: bool
        :param ipv6_address: The ipv6_address of this HostNetworkInterface.  # noqa: E501
        :type ipv6_address: str
        :param ipv6_network_mask_prefix_length: The ipv6_network_mask_prefix_length of this HostNetworkInterface.  # noqa: E501
        :type ipv6_network_mask_prefix_length: int
        :param hardware_address: The hardware_address of this HostNetworkInterface.  # noqa: E501
        :type hardware_address: str
        :param medium_type: The medium_type of this HostNetworkInterface.  # noqa: E501
        :type medium_type: HostNetworkInterfaceMediumType
        :param status: The status of this HostNetworkInterface.  # noqa: E501
        :type status: HostNetworkInterfaceStatus
        :param interface_type: The interface_type of this HostNetworkInterface.  # noqa: E501
        :type interface_type: HostNetworkInterfaceType
        :param wireless: The wireless of this HostNetworkInterface.  # noqa: E501
        :type wireless: bool
        """
        self.swagger_types = {
            'name': str,
            'short_name': str,
            'id': str,
            'network_name': str,
            'dhcp_enabled': bool,
            'ip_address': str,
            'network_mask': str,
            'ipv6_supported': bool,
            'ipv6_address': str,
            'ipv6_network_mask_prefix_length': int,
            'hardware_address': str,
            'medium_type': HostNetworkInterfaceMediumType,
            'status': HostNetworkInterfaceStatus,
            'interface_type': HostNetworkInterfaceType,
            'wireless': bool
        }

        self.attribute_map = {
            'name': 'name',
            'short_name': 'shortName',
            'id': 'id',
            'network_name': 'networkName',
            'dhcp_enabled': 'DHCPEnabled',
            'ip_address': 'IPAddress',
            'network_mask': 'networkMask',
            'ipv6_supported': 'IPV6Supported',
            'ipv6_address': 'IPV6Address',
            'ipv6_network_mask_prefix_length': 'IPV6NetworkMaskPrefixLength',
            'hardware_address': 'hardwareAddress',
            'medium_type': 'mediumType',
            'status': 'status',
            'interface_type': 'interfaceType',
            'wireless': 'wireless'
        }

        self._name = name
        self._short_name = short_name
        self._id = id
        self._network_name = network_name
        self._dhcp_enabled = dhcp_enabled
        self._ip_address = ip_address
        self._network_mask = network_mask
        self._ipv6_supported = ipv6_supported
        self._ipv6_address = ipv6_address
        self._ipv6_network_mask_prefix_length = ipv6_network_mask_prefix_length
        self._hardware_address = hardware_address
        self._medium_type = medium_type
        self._status = status
        self._interface_type = interface_type
        self._wireless = wireless

    @classmethod
    def from_dict(cls, dikt) -> 'HostNetworkInterface':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The HostNetworkInterface of this HostNetworkInterface.  # noqa: E501
        :rtype: HostNetworkInterface
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this HostNetworkInterface.


        :return: The name of this HostNetworkInterface.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this HostNetworkInterface.


        :param name: The name of this HostNetworkInterface.
        :type name: str
        """

        self._name = name

    @property
    def short_name(self) -> str:
        """Gets the short_name of this HostNetworkInterface.


        :return: The short_name of this HostNetworkInterface.
        :rtype: str
        """
        return self._short_name

    @short_name.setter
    def short_name(self, short_name: str):
        """Sets the short_name of this HostNetworkInterface.


        :param short_name: The short_name of this HostNetworkInterface.
        :type short_name: str
        """

        self._short_name = short_name

    @property
    def id(self) -> str:
        """Gets the id of this HostNetworkInterface.


        :return: The id of this HostNetworkInterface.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this HostNetworkInterface.


        :param id: The id of this HostNetworkInterface.
        :type id: str
        """

        self._id = id

    @property
    def network_name(self) -> str:
        """Gets the network_name of this HostNetworkInterface.


        :return: The network_name of this HostNetworkInterface.
        :rtype: str
        """
        return self._network_name

    @network_name.setter
    def network_name(self, network_name: str):
        """Sets the network_name of this HostNetworkInterface.


        :param network_name: The network_name of this HostNetworkInterface.
        :type network_name: str
        """

        self._network_name = network_name

    @property
    def dhcp_enabled(self) -> bool:
        """Gets the dhcp_enabled of this HostNetworkInterface.


        :return: The dhcp_enabled of this HostNetworkInterface.
        :rtype: bool
        """
        return self._dhcp_enabled

    @dhcp_enabled.setter
    def dhcp_enabled(self, dhcp_enabled: bool):
        """Sets the dhcp_enabled of this HostNetworkInterface.


        :param dhcp_enabled: The dhcp_enabled of this HostNetworkInterface.
        :type dhcp_enabled: bool
        """

        self._dhcp_enabled = dhcp_enabled

    @property
    def ip_address(self) -> str:
        """Gets the ip_address of this HostNetworkInterface.


        :return: The ip_address of this HostNetworkInterface.
        :rtype: str
        """
        return self._ip_address

    @ip_address.setter
    def ip_address(self, ip_address: str):
        """Sets the ip_address of this HostNetworkInterface.


        :param ip_address: The ip_address of this HostNetworkInterface.
        :type ip_address: str
        """

        self._ip_address = ip_address

    @property
    def network_mask(self) -> str:
        """Gets the network_mask of this HostNetworkInterface.


        :return: The network_mask of this HostNetworkInterface.
        :rtype: str
        """
        return self._network_mask

    @network_mask.setter
    def network_mask(self, network_mask: str):
        """Sets the network_mask of this HostNetworkInterface.


        :param network_mask: The network_mask of this HostNetworkInterface.
        :type network_mask: str
        """

        self._network_mask = network_mask

    @property
    def ipv6_supported(self) -> bool:
        """Gets the ipv6_supported of this HostNetworkInterface.


        :return: The ipv6_supported of this HostNetworkInterface.
        :rtype: bool
        """
        return self._ipv6_supported

    @ipv6_supported.setter
    def ipv6_supported(self, ipv6_supported: bool):
        """Sets the ipv6_supported of this HostNetworkInterface.


        :param ipv6_supported: The ipv6_supported of this HostNetworkInterface.
        :type ipv6_supported: bool
        """

        self._ipv6_supported = ipv6_supported

    @property
    def ipv6_address(self) -> str:
        """Gets the ipv6_address of this HostNetworkInterface.


        :return: The ipv6_address of this HostNetworkInterface.
        :rtype: str
        """
        return self._ipv6_address

    @ipv6_address.setter
    def ipv6_address(self, ipv6_address: str):
        """Sets the ipv6_address of this HostNetworkInterface.


        :param ipv6_address: The ipv6_address of this HostNetworkInterface.
        :type ipv6_address: str
        """

        self._ipv6_address = ipv6_address

    @property
    def ipv6_network_mask_prefix_length(self) -> int:
        """Gets the ipv6_network_mask_prefix_length of this HostNetworkInterface.


        :return: The ipv6_network_mask_prefix_length of this HostNetworkInterface.
        :rtype: int
        """
        return self._ipv6_network_mask_prefix_length

    @ipv6_network_mask_prefix_length.setter
    def ipv6_network_mask_prefix_length(self, ipv6_network_mask_prefix_length: int):
        """Sets the ipv6_network_mask_prefix_length of this HostNetworkInterface.


        :param ipv6_network_mask_prefix_length: The ipv6_network_mask_prefix_length of this HostNetworkInterface.
        :type ipv6_network_mask_prefix_length: int
        """

        self._ipv6_network_mask_prefix_length = ipv6_network_mask_prefix_length

    @property
    def hardware_address(self) -> str:
        """Gets the hardware_address of this HostNetworkInterface.


        :return: The hardware_address of this HostNetworkInterface.
        :rtype: str
        """
        return self._hardware_address

    @hardware_address.setter
    def hardware_address(self, hardware_address: str):
        """Sets the hardware_address of this HostNetworkInterface.


        :param hardware_address: The hardware_address of this HostNetworkInterface.
        :type hardware_address: str
        """

        self._hardware_address = hardware_address

    @property
    def medium_type(self) -> HostNetworkInterfaceMediumType:
        """Gets the medium_type of this HostNetworkInterface.


        :return: The medium_type of this HostNetworkInterface.
        :rtype: HostNetworkInterfaceMediumType
        """
        return self._medium_type

    @medium_type.setter
    def medium_type(self, medium_type: HostNetworkInterfaceMediumType):
        """Sets the medium_type of this HostNetworkInterface.


        :param medium_type: The medium_type of this HostNetworkInterface.
        :type medium_type: HostNetworkInterfaceMediumType
        """

        self._medium_type = medium_type

    @property
    def status(self) -> HostNetworkInterfaceStatus:
        """Gets the status of this HostNetworkInterface.


        :return: The status of this HostNetworkInterface.
        :rtype: HostNetworkInterfaceStatus
        """
        return self._status

    @status.setter
    def status(self, status: HostNetworkInterfaceStatus):
        """Sets the status of this HostNetworkInterface.


        :param status: The status of this HostNetworkInterface.
        :type status: HostNetworkInterfaceStatus
        """

        self._status = status

    @property
    def interface_type(self) -> HostNetworkInterfaceType:
        """Gets the interface_type of this HostNetworkInterface.


        :return: The interface_type of this HostNetworkInterface.
        :rtype: HostNetworkInterfaceType
        """
        return self._interface_type

    @interface_type.setter
    def interface_type(self, interface_type: HostNetworkInterfaceType):
        """Sets the interface_type of this HostNetworkInterface.


        :param interface_type: The interface_type of this HostNetworkInterface.
        :type interface_type: HostNetworkInterfaceType
        """

        self._interface_type = interface_type

    @property
    def wireless(self) -> bool:
        """Gets the wireless of this HostNetworkInterface.


        :return: The wireless of this HostNetworkInterface.
        :rtype: bool
        """
        return self._wireless

    @wireless.setter
    def wireless(self, wireless: bool):
        """Sets the wireless of this HostNetworkInterface.


        :param wireless: The wireless of this HostNetworkInterface.
        :type wireless: bool
        """

        self._wireless = wireless
