# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401


from vbox_server.models.base_model_ import Model
from vbox_server.models.host_audio_device import HostAudioDevice
from vbox_server.models.host_drive import HostDrive
from vbox_server.models.host_network_interface import HostNetworkInterface
from vbox_server.models.host_usb_device import HostUSBDevice
from vbox_server.models.host_usb_device_filter import HostUSBDeviceFilter
from vbox_server.models.host_video_input_device import HostVideoInputDevice
from vbox_server.models.host_x86 import HostX86
from vbox_server.models.medium import Medium
from vbox_server.models.platform_architecture import PlatformArchitecture
from vbox_server import util


class Host(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, architecture: PlatformArchitecture=None, x86: HostX86=None, dvd_drives: List[Medium]=None, floppy_drives: List[Medium]=None, audio_devices: List[HostAudioDevice]=None, usb_devices: List[HostUSBDevice]=None, usb_device_filters: List[HostUSBDeviceFilter]=None, network_interfaces: List[HostNetworkInterface]=None, name_servers: List[str]=None, domain_name: str=None, search_strings: List[str]=None, processor_count: int=None, processor_online_count: int=None, processor_core_count: int=None, processor_online_core_count: int=None, host_drives: List[HostDrive]=None, memory_size: int=None, memory_available: int=None, operating_system: str=None, os_version: str=None, utc_time: int=None, acceleration3_d_available: bool=None, video_input_devices: List[HostVideoInputDevice]=None):  # noqa: E501
        """Host - a model defined in Swagger

        :param architecture: The architecture of this Host.  # noqa: E501
        :type architecture: PlatformArchitecture
        :param x86: The x86 of this Host.  # noqa: E501
        :type x86: HostX86
        :param dvd_drives: The dvd_drives of this Host.  # noqa: E501
        :type dvd_drives: List[Medium]
        :param floppy_drives: The floppy_drives of this Host.  # noqa: E501
        :type floppy_drives: List[Medium]
        :param audio_devices: The audio_devices of this Host.  # noqa: E501
        :type audio_devices: List[HostAudioDevice]
        :param usb_devices: The usb_devices of this Host.  # noqa: E501
        :type usb_devices: List[HostUSBDevice]
        :param usb_device_filters: The usb_device_filters of this Host.  # noqa: E501
        :type usb_device_filters: List[HostUSBDeviceFilter]
        :param network_interfaces: The network_interfaces of this Host.  # noqa: E501
        :type network_interfaces: List[HostNetworkInterface]
        :param name_servers: The name_servers of this Host.  # noqa: E501
        :type name_servers: List[str]
        :param domain_name: The domain_name of this Host.  # noqa: E501
        :type domain_name: str
        :param search_strings: The search_strings of this Host.  # noqa: E501
        :type search_strings: List[str]
        :param processor_count: The processor_count of this Host.  # noqa: E501
        :type processor_count: int
        :param processor_online_count: The processor_online_count of this Host.  # noqa: E501
        :type processor_online_count: int
        :param processor_core_count: The processor_core_count of this Host.  # noqa: E501
        :type processor_core_count: int
        :param processor_online_core_count: The processor_online_core_count of this Host.  # noqa: E501
        :type processor_online_core_count: int
        :param host_drives: The host_drives of this Host.  # noqa: E501
        :type host_drives: List[HostDrive]
        :param memory_size: The memory_size of this Host.  # noqa: E501
        :type memory_size: int
        :param memory_available: The memory_available of this Host.  # noqa: E501
        :type memory_available: int
        :param operating_system: The operating_system of this Host.  # noqa: E501
        :type operating_system: str
        :param os_version: The os_version of this Host.  # noqa: E501
        :type os_version: str
        :param utc_time: The utc_time of this Host.  # noqa: E501
        :type utc_time: int
        :param acceleration3_d_available: The acceleration3_d_available of this Host.  # noqa: E501
        :type acceleration3_d_available: bool
        :param video_input_devices: The video_input_devices of this Host.  # noqa: E501
        :type video_input_devices: List[HostVideoInputDevice]
        """
        self.swagger_types = {
            'architecture': PlatformArchitecture,
            'x86': HostX86,
            'dvd_drives': List[Medium],
            'floppy_drives': List[Medium],
            'audio_devices': List[HostAudioDevice],
            'usb_devices': List[HostUSBDevice],
            'usb_device_filters': List[HostUSBDeviceFilter],
            'network_interfaces': List[HostNetworkInterface],
            'name_servers': List[str],
            'domain_name': str,
            'search_strings': List[str],
            'processor_count': int,
            'processor_online_count': int,
            'processor_core_count': int,
            'processor_online_core_count': int,
            'host_drives': List[HostDrive],
            'memory_size': int,
            'memory_available': int,
            'operating_system': str,
            'os_version': str,
            'utc_time': int,
            'acceleration3_d_available': bool,
            'video_input_devices': List[HostVideoInputDevice]
        }

        self.attribute_map = {
            'architecture': 'architecture',
            'x86': 'x86',
            'dvd_drives': 'DVDDrives',
            'floppy_drives': 'floppyDrives',
            'audio_devices': 'audioDevices',
            'usb_devices': 'USBDevices',
            'usb_device_filters': 'USBDeviceFilters',
            'network_interfaces': 'networkInterfaces',
            'name_servers': 'nameServers',
            'domain_name': 'domainName',
            'search_strings': 'searchStrings',
            'processor_count': 'processorCount',
            'processor_online_count': 'processorOnlineCount',
            'processor_core_count': 'processorCoreCount',
            'processor_online_core_count': 'processorOnlineCoreCount',
            'host_drives': 'hostDrives',
            'memory_size': 'memorySize',
            'memory_available': 'memoryAvailable',
            'operating_system': 'operatingSystem',
            'os_version': 'OSVersion',
            'utc_time': 'UTCTime',
            'acceleration3_d_available': 'acceleration3DAvailable',
            'video_input_devices': 'videoInputDevices'
        }

        self._architecture = architecture
        self._x86 = x86
        self._dvd_drives = dvd_drives
        self._floppy_drives = floppy_drives
        self._audio_devices = audio_devices
        self._usb_devices = usb_devices
        self._usb_device_filters = usb_device_filters
        self._network_interfaces = network_interfaces
        self._name_servers = name_servers
        self._domain_name = domain_name
        self._search_strings = search_strings
        self._processor_count = processor_count
        self._processor_online_count = processor_online_count
        self._processor_core_count = processor_core_count
        self._processor_online_core_count = processor_online_core_count
        self._host_drives = host_drives
        self._memory_size = memory_size
        self._memory_available = memory_available
        self._operating_system = operating_system
        self._os_version = os_version
        self._utc_time = utc_time
        self._acceleration3_d_available = acceleration3_d_available
        self._video_input_devices = video_input_devices

    @classmethod
    def from_dict(cls, dikt) -> 'Host':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Host of this Host.  # noqa: E501
        :rtype: Host
        """
        return util.deserialize_model(dikt, cls)

    @property
    def architecture(self) -> PlatformArchitecture:
        """Gets the architecture of this Host.


        :return: The architecture of this Host.
        :rtype: PlatformArchitecture
        """
        return self._architecture

    @architecture.setter
    def architecture(self, architecture: PlatformArchitecture):
        """Sets the architecture of this Host.


        :param architecture: The architecture of this Host.
        :type architecture: PlatformArchitecture
        """

        self._architecture = architecture

    @property
    def x86(self) -> HostX86:
        """Gets the x86 of this Host.


        :return: The x86 of this Host.
        :rtype: HostX86
        """
        return self._x86

    @x86.setter
    def x86(self, x86: HostX86):
        """Sets the x86 of this Host.


        :param x86: The x86 of this Host.
        :type x86: HostX86
        """

        self._x86 = x86

    @property
    def dvd_drives(self) -> List[Medium]:
        """Gets the dvd_drives of this Host.


        :return: The dvd_drives of this Host.
        :rtype: List[Medium]
        """
        return self._dvd_drives

    @dvd_drives.setter
    def dvd_drives(self, dvd_drives: List[Medium]):
        """Sets the dvd_drives of this Host.


        :param dvd_drives: The dvd_drives of this Host.
        :type dvd_drives: List[Medium]
        """

        self._dvd_drives = dvd_drives

    @property
    def floppy_drives(self) -> List[Medium]:
        """Gets the floppy_drives of this Host.


        :return: The floppy_drives of this Host.
        :rtype: List[Medium]
        """
        return self._floppy_drives

    @floppy_drives.setter
    def floppy_drives(self, floppy_drives: List[Medium]):
        """Sets the floppy_drives of this Host.


        :param floppy_drives: The floppy_drives of this Host.
        :type floppy_drives: List[Medium]
        """

        self._floppy_drives = floppy_drives

    @property
    def audio_devices(self) -> List[HostAudioDevice]:
        """Gets the audio_devices of this Host.


        :return: The audio_devices of this Host.
        :rtype: List[HostAudioDevice]
        """
        return self._audio_devices

    @audio_devices.setter
    def audio_devices(self, audio_devices: List[HostAudioDevice]):
        """Sets the audio_devices of this Host.


        :param audio_devices: The audio_devices of this Host.
        :type audio_devices: List[HostAudioDevice]
        """

        self._audio_devices = audio_devices

    @property
    def usb_devices(self) -> List[HostUSBDevice]:
        """Gets the usb_devices of this Host.


        :return: The usb_devices of this Host.
        :rtype: List[HostUSBDevice]
        """
        return self._usb_devices

    @usb_devices.setter
    def usb_devices(self, usb_devices: List[HostUSBDevice]):
        """Sets the usb_devices of this Host.


        :param usb_devices: The usb_devices of this Host.
        :type usb_devices: List[HostUSBDevice]
        """

        self._usb_devices = usb_devices

    @property
    def usb_device_filters(self) -> List[HostUSBDeviceFilter]:
        """Gets the usb_device_filters of this Host.


        :return: The usb_device_filters of this Host.
        :rtype: List[HostUSBDeviceFilter]
        """
        return self._usb_device_filters

    @usb_device_filters.setter
    def usb_device_filters(self, usb_device_filters: List[HostUSBDeviceFilter]):
        """Sets the usb_device_filters of this Host.


        :param usb_device_filters: The usb_device_filters of this Host.
        :type usb_device_filters: List[HostUSBDeviceFilter]
        """

        self._usb_device_filters = usb_device_filters

    @property
    def network_interfaces(self) -> List[HostNetworkInterface]:
        """Gets the network_interfaces of this Host.


        :return: The network_interfaces of this Host.
        :rtype: List[HostNetworkInterface]
        """
        return self._network_interfaces

    @network_interfaces.setter
    def network_interfaces(self, network_interfaces: List[HostNetworkInterface]):
        """Sets the network_interfaces of this Host.


        :param network_interfaces: The network_interfaces of this Host.
        :type network_interfaces: List[HostNetworkInterface]
        """

        self._network_interfaces = network_interfaces

    @property
    def name_servers(self) -> List[str]:
        """Gets the name_servers of this Host.


        :return: The name_servers of this Host.
        :rtype: List[str]
        """
        return self._name_servers

    @name_servers.setter
    def name_servers(self, name_servers: List[str]):
        """Sets the name_servers of this Host.


        :param name_servers: The name_servers of this Host.
        :type name_servers: List[str]
        """

        self._name_servers = name_servers

    @property
    def domain_name(self) -> str:
        """Gets the domain_name of this Host.


        :return: The domain_name of this Host.
        :rtype: str
        """
        return self._domain_name

    @domain_name.setter
    def domain_name(self, domain_name: str):
        """Sets the domain_name of this Host.


        :param domain_name: The domain_name of this Host.
        :type domain_name: str
        """

        self._domain_name = domain_name

    @property
    def search_strings(self) -> List[str]:
        """Gets the search_strings of this Host.


        :return: The search_strings of this Host.
        :rtype: List[str]
        """
        return self._search_strings

    @search_strings.setter
    def search_strings(self, search_strings: List[str]):
        """Sets the search_strings of this Host.


        :param search_strings: The search_strings of this Host.
        :type search_strings: List[str]
        """

        self._search_strings = search_strings

    @property
    def processor_count(self) -> int:
        """Gets the processor_count of this Host.


        :return: The processor_count of this Host.
        :rtype: int
        """
        return self._processor_count

    @processor_count.setter
    def processor_count(self, processor_count: int):
        """Sets the processor_count of this Host.


        :param processor_count: The processor_count of this Host.
        :type processor_count: int
        """

        self._processor_count = processor_count

    @property
    def processor_online_count(self) -> int:
        """Gets the processor_online_count of this Host.


        :return: The processor_online_count of this Host.
        :rtype: int
        """
        return self._processor_online_count

    @processor_online_count.setter
    def processor_online_count(self, processor_online_count: int):
        """Sets the processor_online_count of this Host.


        :param processor_online_count: The processor_online_count of this Host.
        :type processor_online_count: int
        """

        self._processor_online_count = processor_online_count

    @property
    def processor_core_count(self) -> int:
        """Gets the processor_core_count of this Host.


        :return: The processor_core_count of this Host.
        :rtype: int
        """
        return self._processor_core_count

    @processor_core_count.setter
    def processor_core_count(self, processor_core_count: int):
        """Sets the processor_core_count of this Host.


        :param processor_core_count: The processor_core_count of this Host.
        :type processor_core_count: int
        """

        self._processor_core_count = processor_core_count

    @property
    def processor_online_core_count(self) -> int:
        """Gets the processor_online_core_count of this Host.


        :return: The processor_online_core_count of this Host.
        :rtype: int
        """
        return self._processor_online_core_count

    @processor_online_core_count.setter
    def processor_online_core_count(self, processor_online_core_count: int):
        """Sets the processor_online_core_count of this Host.


        :param processor_online_core_count: The processor_online_core_count of this Host.
        :type processor_online_core_count: int
        """

        self._processor_online_core_count = processor_online_core_count

    @property
    def host_drives(self) -> List[HostDrive]:
        """Gets the host_drives of this Host.


        :return: The host_drives of this Host.
        :rtype: List[HostDrive]
        """
        return self._host_drives

    @host_drives.setter
    def host_drives(self, host_drives: List[HostDrive]):
        """Sets the host_drives of this Host.


        :param host_drives: The host_drives of this Host.
        :type host_drives: List[HostDrive]
        """

        self._host_drives = host_drives

    @property
    def memory_size(self) -> int:
        """Gets the memory_size of this Host.


        :return: The memory_size of this Host.
        :rtype: int
        """
        return self._memory_size

    @memory_size.setter
    def memory_size(self, memory_size: int):
        """Sets the memory_size of this Host.


        :param memory_size: The memory_size of this Host.
        :type memory_size: int
        """

        self._memory_size = memory_size

    @property
    def memory_available(self) -> int:
        """Gets the memory_available of this Host.


        :return: The memory_available of this Host.
        :rtype: int
        """
        return self._memory_available

    @memory_available.setter
    def memory_available(self, memory_available: int):
        """Sets the memory_available of this Host.


        :param memory_available: The memory_available of this Host.
        :type memory_available: int
        """

        self._memory_available = memory_available

    @property
    def operating_system(self) -> str:
        """Gets the operating_system of this Host.


        :return: The operating_system of this Host.
        :rtype: str
        """
        return self._operating_system

    @operating_system.setter
    def operating_system(self, operating_system: str):
        """Sets the operating_system of this Host.


        :param operating_system: The operating_system of this Host.
        :type operating_system: str
        """

        self._operating_system = operating_system

    @property
    def os_version(self) -> str:
        """Gets the os_version of this Host.


        :return: The os_version of this Host.
        :rtype: str
        """
        return self._os_version

    @os_version.setter
    def os_version(self, os_version: str):
        """Sets the os_version of this Host.


        :param os_version: The os_version of this Host.
        :type os_version: str
        """

        self._os_version = os_version

    @property
    def utc_time(self) -> int:
        """Gets the utc_time of this Host.


        :return: The utc_time of this Host.
        :rtype: int
        """
        return self._utc_time

    @utc_time.setter
    def utc_time(self, utc_time: int):
        """Sets the utc_time of this Host.


        :param utc_time: The utc_time of this Host.
        :type utc_time: int
        """

        self._utc_time = utc_time

    @property
    def acceleration3_d_available(self) -> bool:
        """Gets the acceleration3_d_available of this Host.


        :return: The acceleration3_d_available of this Host.
        :rtype: bool
        """
        return self._acceleration3_d_available

    @acceleration3_d_available.setter
    def acceleration3_d_available(self, acceleration3_d_available: bool):
        """Sets the acceleration3_d_available of this Host.


        :param acceleration3_d_available: The acceleration3_d_available of this Host.
        :type acceleration3_d_available: bool
        """

        self._acceleration3_d_available = acceleration3_d_available

    @property
    def video_input_devices(self) -> List[HostVideoInputDevice]:
        """Gets the video_input_devices of this Host.


        :return: The video_input_devices of this Host.
        :rtype: List[HostVideoInputDevice]
        """
        return self._video_input_devices

    @video_input_devices.setter
    def video_input_devices(self, video_input_devices: List[HostVideoInputDevice]):
        """Sets the video_input_devices of this Host.


        :param video_input_devices: The video_input_devices of this Host.
        :type video_input_devices: List[HostVideoInputDevice]
        """

        self._video_input_devices = video_input_devices
