# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401


from vbox_server.models.base_model_ import Model
from vbox_server.models.device_type import DeviceType
from vbox_server import util


class MachineAttachDeviceWithoutMediumRequestBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, name: str=None, controller_port: int=None, device: int=None, type: DeviceType=None):  # noqa: E501
        """MachineAttachDeviceWithoutMediumRequestBody - a model defined in Swagger

        :param name: The name of this MachineAttachDeviceWithoutMediumRequestBody.  # noqa: E501
        :type name: str
        :param controller_port: The controller_port of this MachineAttachDeviceWithoutMediumRequestBody.  # noqa: E501
        :type controller_port: int
        :param device: The device of this MachineAttachDeviceWithoutMediumRequestBody.  # noqa: E501
        :type device: int
        :param type: The type of this MachineAttachDeviceWithoutMediumRequestBody.  # noqa: E501
        :type type: DeviceType
        """
        self.swagger_types = {
            'name': str,
            'controller_port': int,
            'device': int,
            'type': DeviceType
        }

        self.attribute_map = {
            'name': 'name',
            'controller_port': 'controllerPort',
            'device': 'device',
            'type': 'type'
        }

        self._name = name
        self._controller_port = controller_port
        self._device = device
        self._type = type

    @classmethod
    def from_dict(cls, dikt) -> 'MachineAttachDeviceWithoutMediumRequestBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The MachineAttachDeviceWithoutMediumRequestBody of this MachineAttachDeviceWithoutMediumRequestBody.  # noqa: E501
        :rtype: MachineAttachDeviceWithoutMediumRequestBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this MachineAttachDeviceWithoutMediumRequestBody.


        :return: The name of this MachineAttachDeviceWithoutMediumRequestBody.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this MachineAttachDeviceWithoutMediumRequestBody.


        :param name: The name of this MachineAttachDeviceWithoutMediumRequestBody.
        :type name: str
        """

        self._name = name

    @property
    def controller_port(self) -> int:
        """Gets the controller_port of this MachineAttachDeviceWithoutMediumRequestBody.


        :return: The controller_port of this MachineAttachDeviceWithoutMediumRequestBody.
        :rtype: int
        """
        return self._controller_port

    @controller_port.setter
    def controller_port(self, controller_port: int):
        """Sets the controller_port of this MachineAttachDeviceWithoutMediumRequestBody.


        :param controller_port: The controller_port of this MachineAttachDeviceWithoutMediumRequestBody.
        :type controller_port: int
        """

        self._controller_port = controller_port

    @property
    def device(self) -> int:
        """Gets the device of this MachineAttachDeviceWithoutMediumRequestBody.


        :return: The device of this MachineAttachDeviceWithoutMediumRequestBody.
        :rtype: int
        """
        return self._device

    @device.setter
    def device(self, device: int):
        """Sets the device of this MachineAttachDeviceWithoutMediumRequestBody.


        :param device: The device of this MachineAttachDeviceWithoutMediumRequestBody.
        :type device: int
        """

        self._device = device

    @property
    def type(self) -> DeviceType:
        """Gets the type of this MachineAttachDeviceWithoutMediumRequestBody.


        :return: The type of this MachineAttachDeviceWithoutMediumRequestBody.
        :rtype: DeviceType
        """
        return self._type

    @type.setter
    def type(self, type: DeviceType):
        """Sets the type of this MachineAttachDeviceWithoutMediumRequestBody.


        :param type: The type of this MachineAttachDeviceWithoutMediumRequestBody.
        :type type: DeviceType
        """

        self._type = type
