# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401


from vbox_server.models.base_model_ import Model
from vbox_server import util


class MachineGetcpustatusResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, attached: bool=None):  # noqa: E501
        """MachineGetcpustatusResponse - a model defined in Swagger

        :param attached: The attached of this MachineGetcpustatusResponse.  # noqa: E501
        :type attached: bool
        """
        self.swagger_types = {
            'attached': bool
        }

        self.attribute_map = {
            'attached': 'attached'
        }

        self._attached = attached

    @classmethod
    def from_dict(cls, dikt) -> 'MachineGetcpustatusResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The machine_getcpustatus_response of this MachineGetcpustatusResponse.  # noqa: E501
        :rtype: MachineGetcpustatusResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def attached(self) -> bool:
        """Gets the attached of this MachineGetcpustatusResponse.


        :return: The attached of this MachineGetcpustatusResponse.
        :rtype: bool
        """
        return self._attached

    @attached.setter
    def attached(self, attached: bool):
        """Sets the attached of this MachineGetcpustatusResponse.


        :param attached: The attached of this MachineGetcpustatusResponse.
        :type attached: bool
        """

        self._attached = attached
