# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401


from vbox_server.models.base_model_ import Model
from vbox_server import util


class MachineSetAutoDiscardForDeviceRequestBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, name: str=None, controller_port: int=None, device: int=None, discard: bool=None):  # noqa: E501
        """MachineSetAutoDiscardForDeviceRequestBody - a model defined in Swagger

        :param name: The name of this MachineSetAutoDiscardForDeviceRequestBody.  # noqa: E501
        :type name: str
        :param controller_port: The controller_port of this MachineSetAutoDiscardForDeviceRequestBody.  # noqa: E501
        :type controller_port: int
        :param device: The device of this MachineSetAutoDiscardForDeviceRequestBody.  # noqa: E501
        :type device: int
        :param discard: The discard of this MachineSetAutoDiscardForDeviceRequestBody.  # noqa: E501
        :type discard: bool
        """
        self.swagger_types = {
            'name': str,
            'controller_port': int,
            'device': int,
            'discard': bool
        }

        self.attribute_map = {
            'name': 'name',
            'controller_port': 'controllerPort',
            'device': 'device',
            'discard': 'discard'
        }

        self._name = name
        self._controller_port = controller_port
        self._device = device
        self._discard = discard

    @classmethod
    def from_dict(cls, dikt) -> 'MachineSetAutoDiscardForDeviceRequestBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The MachineSetAutoDiscardForDeviceRequestBody of this MachineSetAutoDiscardForDeviceRequestBody.  # noqa: E501
        :rtype: MachineSetAutoDiscardForDeviceRequestBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this MachineSetAutoDiscardForDeviceRequestBody.


        :return: The name of this MachineSetAutoDiscardForDeviceRequestBody.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this MachineSetAutoDiscardForDeviceRequestBody.


        :param name: The name of this MachineSetAutoDiscardForDeviceRequestBody.
        :type name: str
        """

        self._name = name

    @property
    def controller_port(self) -> int:
        """Gets the controller_port of this MachineSetAutoDiscardForDeviceRequestBody.


        :return: The controller_port of this MachineSetAutoDiscardForDeviceRequestBody.
        :rtype: int
        """
        return self._controller_port

    @controller_port.setter
    def controller_port(self, controller_port: int):
        """Sets the controller_port of this MachineSetAutoDiscardForDeviceRequestBody.


        :param controller_port: The controller_port of this MachineSetAutoDiscardForDeviceRequestBody.
        :type controller_port: int
        """

        self._controller_port = controller_port

    @property
    def device(self) -> int:
        """Gets the device of this MachineSetAutoDiscardForDeviceRequestBody.


        :return: The device of this MachineSetAutoDiscardForDeviceRequestBody.
        :rtype: int
        """
        return self._device

    @device.setter
    def device(self, device: int):
        """Sets the device of this MachineSetAutoDiscardForDeviceRequestBody.


        :param device: The device of this MachineSetAutoDiscardForDeviceRequestBody.
        :type device: int
        """

        self._device = device

    @property
    def discard(self) -> bool:
        """Gets the discard of this MachineSetAutoDiscardForDeviceRequestBody.


        :return: The discard of this MachineSetAutoDiscardForDeviceRequestBody.
        :rtype: bool
        """
        return self._discard

    @discard.setter
    def discard(self, discard: bool):
        """Sets the discard of this MachineSetAutoDiscardForDeviceRequestBody.


        :param discard: The discard of this MachineSetAutoDiscardForDeviceRequestBody.
        :type discard: bool
        """

        self._discard = discard
