# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401


from vbox_server.models.base_model_ import Model
from vbox_server import util


class MachineLaunchVMProcessRequestBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, session: str=None, name: str=None, environment_changes: List[str]=None):  # noqa: E501
        """MachineLaunchVMProcessRequestBody - a model defined in Swagger

        :param session: The session of this MachineLaunchVMProcessRequestBody.  # noqa: E501
        :type session: str
        :param name: The name of this MachineLaunchVMProcessRequestBody.  # noqa: E501
        :type name: str
        :param environment_changes: The environment_changes of this MachineLaunchVMProcessRequestBody.  # noqa: E501
        :type environment_changes: List[str]
        """
        self.swagger_types = {
            'session': str,
            'name': str,
            'environment_changes': List[str]
        }

        self.attribute_map = {
            'session': 'session',
            'name': 'name',
            'environment_changes': 'environmentChanges'
        }

        self._session = session
        self._name = name
        self._environment_changes = environment_changes

    @classmethod
    def from_dict(cls, dikt) -> 'MachineLaunchVMProcessRequestBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The MachineLaunchVMProcessRequestBody of this MachineLaunchVMProcessRequestBody.  # noqa: E501
        :rtype: MachineLaunchVMProcessRequestBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def session(self) -> str:
        """Gets the session of this MachineLaunchVMProcessRequestBody.

        UUID of object  # noqa: E501

        :return: The session of this MachineLaunchVMProcessRequestBody.
        :rtype: str
        """
        return self._session

    @session.setter
    def session(self, session: str):
        """Sets the session of this MachineLaunchVMProcessRequestBody.

        UUID of object  # noqa: E501

        :param session: The session of this MachineLaunchVMProcessRequestBody.
        :type session: str
        """

        self._session = session

    @property
    def name(self) -> str:
        """Gets the name of this MachineLaunchVMProcessRequestBody.


        :return: The name of this MachineLaunchVMProcessRequestBody.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this MachineLaunchVMProcessRequestBody.


        :param name: The name of this MachineLaunchVMProcessRequestBody.
        :type name: str
        """

        self._name = name

    @property
    def environment_changes(self) -> List[str]:
        """Gets the environment_changes of this MachineLaunchVMProcessRequestBody.


        :return: The environment_changes of this MachineLaunchVMProcessRequestBody.
        :rtype: List[str]
        """
        return self._environment_changes

    @environment_changes.setter
    def environment_changes(self, environment_changes: List[str]):
        """Sets the environment_changes of this MachineLaunchVMProcessRequestBody.


        :param environment_changes: The environment_changes of this MachineLaunchVMProcessRequestBody.
        :type environment_changes: List[str]
        """

        self._environment_changes = environment_changes
