# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401


from vbox_server.models.base_model_ import Model
from vbox_server import util


class MachinePassthroughDeviceRequestBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, name: str=None, controller_port: int=None, device: int=None, passthrough: bool=None):  # noqa: E501
        """MachinePassthroughDeviceRequestBody - a model defined in Swagger

        :param name: The name of this MachinePassthroughDeviceRequestBody.  # noqa: E501
        :type name: str
        :param controller_port: The controller_port of this MachinePassthroughDeviceRequestBody.  # noqa: E501
        :type controller_port: int
        :param device: The device of this MachinePassthroughDeviceRequestBody.  # noqa: E501
        :type device: int
        :param passthrough: The passthrough of this MachinePassthroughDeviceRequestBody.  # noqa: E501
        :type passthrough: bool
        """
        self.swagger_types = {
            'name': str,
            'controller_port': int,
            'device': int,
            'passthrough': bool
        }

        self.attribute_map = {
            'name': 'name',
            'controller_port': 'controllerPort',
            'device': 'device',
            'passthrough': 'passthrough'
        }

        self._name = name
        self._controller_port = controller_port
        self._device = device
        self._passthrough = passthrough

    @classmethod
    def from_dict(cls, dikt) -> 'MachinePassthroughDeviceRequestBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The MachinePassthroughDeviceRequestBody of this MachinePassthroughDeviceRequestBody.  # noqa: E501
        :rtype: MachinePassthroughDeviceRequestBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this MachinePassthroughDeviceRequestBody.


        :return: The name of this MachinePassthroughDeviceRequestBody.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this MachinePassthroughDeviceRequestBody.


        :param name: The name of this MachinePassthroughDeviceRequestBody.
        :type name: str
        """

        self._name = name

    @property
    def controller_port(self) -> int:
        """Gets the controller_port of this MachinePassthroughDeviceRequestBody.


        :return: The controller_port of this MachinePassthroughDeviceRequestBody.
        :rtype: int
        """
        return self._controller_port

    @controller_port.setter
    def controller_port(self, controller_port: int):
        """Sets the controller_port of this MachinePassthroughDeviceRequestBody.


        :param controller_port: The controller_port of this MachinePassthroughDeviceRequestBody.
        :type controller_port: int
        """

        self._controller_port = controller_port

    @property
    def device(self) -> int:
        """Gets the device of this MachinePassthroughDeviceRequestBody.


        :return: The device of this MachinePassthroughDeviceRequestBody.
        :rtype: int
        """
        return self._device

    @device.setter
    def device(self, device: int):
        """Sets the device of this MachinePassthroughDeviceRequestBody.


        :param device: The device of this MachinePassthroughDeviceRequestBody.
        :type device: int
        """

        self._device = device

    @property
    def passthrough(self) -> bool:
        """Gets the passthrough of this MachinePassthroughDeviceRequestBody.


        :return: The passthrough of this MachinePassthroughDeviceRequestBody.
        :rtype: bool
        """
        return self._passthrough

    @passthrough.setter
    def passthrough(self, passthrough: bool):
        """Sets the passthrough of this MachinePassthroughDeviceRequestBody.


        :param passthrough: The passthrough of this MachinePassthroughDeviceRequestBody.
        :type passthrough: bool
        """

        self._passthrough = passthrough
