# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401


from vbox_server.models.base_model_ import Model
from vbox_server.models.audio_settings import AudioSettings
from vbox_server.models.autostop_type import AutostopType
from vbox_server.models.bandwidth_control import BandwidthControl
from vbox_server.models.clipboard_mode import ClipboardMode
from vbox_server.models.dn_d_mode import DnDMode
from vbox_server.models.firmware_settings import FirmwareSettings
from vbox_server.models.graphics_adapter import GraphicsAdapter
from vbox_server.models.guest_debug_control import GuestDebugControl
from vbox_server.models.keyboard_hid_type import KeyboardHIDType
from vbox_server.models.machine_state import MachineState
from vbox_server.models.medium_attachment import MediumAttachment
from vbox_server.models.paravirt_provider import ParavirtProvider
from vbox_server.models.pci_device_attachment import PCIDeviceAttachment
from vbox_server.models.platform import Platform
from vbox_server.models.pointing_hid_type import PointingHIDType
from vbox_server.models.recording_settings import RecordingSettings
from vbox_server.models.session_state import SessionState
from vbox_server.models.shared_folder import SharedFolder
from vbox_server.models.snapshot import Snapshot
from vbox_server.models.storage_controller import StorageController
from vbox_server.models.usb_controller import USBController
from vbox_server.models.usb_device_filters import USBDeviceFilters
from vbox_server.models.virtual_box_error_info import VirtualBoxErrorInfo
from vbox_server.models.vm_proc_priority import VMProcPriority
from vbox_server.models.vrde_server import VRDEServer
from vbox_server import util


class Machine(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, icon: str=None, accessible: bool=None, access_error: VirtualBoxErrorInfo=None, name: str=None, description: str=None, id: str=None, groups: List[str]=None, os_type_id: str=None, hardware_version: str=None, hardware_uuid: str=None, cpu_count: int=None, cpu_hot_plug_enabled: bool=None, cpu_execution_cap: int=None, cpuid_portability_level: int=None, memory_size: int=None, memory_balloon_size: int=None, page_fusion_enabled: bool=None, graphics_adapter: GraphicsAdapter=None, platform: Platform=None, firmware_settings: FirmwareSettings=None, recording_settings: RecordingSettings=None, pointing_hid_type: PointingHIDType=None, keyboard_hid_type: KeyboardHIDType=None, snapshot_folder: str=None, vrde_server: VRDEServer=None, emulated_usb_card_reader_enabled: bool=None, medium_attachments: List[MediumAttachment]=None, usb_controllers: List[USBController]=None, usb_device_filters: USBDeviceFilters=None, audio_settings: AudioSettings=None, storage_controllers: List[StorageController]=None, settings_file_path: str=None, session_state: SessionState=None, session_name: str=None, session_pid: int=None, state: MachineState=None, last_state_change: int=None, state_file_path: str=None, log_folder: str=None, current_snapshot: Snapshot=None, snapshot_count: int=None, current_state_modified: bool=None, shared_folders: List[SharedFolder]=None, clipboard_mode: ClipboardMode=None, clipboard_file_transfers_enabled: bool=None, dn_d_mode: DnDMode=None, teleporter_enabled: bool=None, teleporter_port: int=None, teleporter_address: str=None, teleporter_password: str=None, paravirt_provider: ParavirtProvider=None, io_cache_enabled: bool=None, io_cache_size: int=None, pci_device_assignments: List[PCIDeviceAttachment]=None, bandwidth_control: BandwidthControl=None, tracing_enabled: bool=None, tracing_config: str=None, allow_tracing_to_access_vm: bool=None, autostart_enabled: bool=None, autostart_delay: int=None, autostop_type: AutostopType=None, default_frontend: str=None, usb_proxy_available: bool=None, vm_process_priority: VMProcPriority=None, paravirt_debug: str=None, cpu_profile: str=None, state_key_id: str=None, state_key_store: str=None, log_key_id: str=None, log_key_store: str=None, guest_debug_control: GuestDebugControl=None):  # noqa: E501
        """Machine - a model defined in Swagger

        :param icon: The icon of this Machine.  # noqa: E501
        :type icon: str
        :param accessible: The accessible of this Machine.  # noqa: E501
        :type accessible: bool
        :param access_error: The access_error of this Machine.  # noqa: E501
        :type access_error: VirtualBoxErrorInfo
        :param name: The name of this Machine.  # noqa: E501
        :type name: str
        :param description: The description of this Machine.  # noqa: E501
        :type description: str
        :param id: The id of this Machine.  # noqa: E501
        :type id: str
        :param groups: The groups of this Machine.  # noqa: E501
        :type groups: List[str]
        :param os_type_id: The os_type_id of this Machine.  # noqa: E501
        :type os_type_id: str
        :param hardware_version: The hardware_version of this Machine.  # noqa: E501
        :type hardware_version: str
        :param hardware_uuid: The hardware_uuid of this Machine.  # noqa: E501
        :type hardware_uuid: str
        :param cpu_count: The cpu_count of this Machine.  # noqa: E501
        :type cpu_count: int
        :param cpu_hot_plug_enabled: The cpu_hot_plug_enabled of this Machine.  # noqa: E501
        :type cpu_hot_plug_enabled: bool
        :param cpu_execution_cap: The cpu_execution_cap of this Machine.  # noqa: E501
        :type cpu_execution_cap: int
        :param cpuid_portability_level: The cpuid_portability_level of this Machine.  # noqa: E501
        :type cpuid_portability_level: int
        :param memory_size: The memory_size of this Machine.  # noqa: E501
        :type memory_size: int
        :param memory_balloon_size: The memory_balloon_size of this Machine.  # noqa: E501
        :type memory_balloon_size: int
        :param page_fusion_enabled: The page_fusion_enabled of this Machine.  # noqa: E501
        :type page_fusion_enabled: bool
        :param graphics_adapter: The graphics_adapter of this Machine.  # noqa: E501
        :type graphics_adapter: GraphicsAdapter
        :param platform: The platform of this Machine.  # noqa: E501
        :type platform: Platform
        :param firmware_settings: The firmware_settings of this Machine.  # noqa: E501
        :type firmware_settings: FirmwareSettings
        :param recording_settings: The recording_settings of this Machine.  # noqa: E501
        :type recording_settings: RecordingSettings
        :param pointing_hid_type: The pointing_hid_type of this Machine.  # noqa: E501
        :type pointing_hid_type: PointingHIDType
        :param keyboard_hid_type: The keyboard_hid_type of this Machine.  # noqa: E501
        :type keyboard_hid_type: KeyboardHIDType
        :param snapshot_folder: The snapshot_folder of this Machine.  # noqa: E501
        :type snapshot_folder: str
        :param vrde_server: The vrde_server of this Machine.  # noqa: E501
        :type vrde_server: VRDEServer
        :param emulated_usb_card_reader_enabled: The emulated_usb_card_reader_enabled of this Machine.  # noqa: E501
        :type emulated_usb_card_reader_enabled: bool
        :param medium_attachments: The medium_attachments of this Machine.  # noqa: E501
        :type medium_attachments: List[MediumAttachment]
        :param usb_controllers: The usb_controllers of this Machine.  # noqa: E501
        :type usb_controllers: List[USBController]
        :param usb_device_filters: The usb_device_filters of this Machine.  # noqa: E501
        :type usb_device_filters: USBDeviceFilters
        :param audio_settings: The audio_settings of this Machine.  # noqa: E501
        :type audio_settings: AudioSettings
        :param storage_controllers: The storage_controllers of this Machine.  # noqa: E501
        :type storage_controllers: List[StorageController]
        :param settings_file_path: The settings_file_path of this Machine.  # noqa: E501
        :type settings_file_path: str
        :param session_state: The session_state of this Machine.  # noqa: E501
        :type session_state: SessionState
        :param session_name: The session_name of this Machine.  # noqa: E501
        :type session_name: str
        :param session_pid: The session_pid of this Machine.  # noqa: E501
        :type session_pid: int
        :param state: The state of this Machine.  # noqa: E501
        :type state: MachineState
        :param last_state_change: The last_state_change of this Machine.  # noqa: E501
        :type last_state_change: int
        :param state_file_path: The state_file_path of this Machine.  # noqa: E501
        :type state_file_path: str
        :param log_folder: The log_folder of this Machine.  # noqa: E501
        :type log_folder: str
        :param current_snapshot: The current_snapshot of this Machine.  # noqa: E501
        :type current_snapshot: Snapshot
        :param snapshot_count: The snapshot_count of this Machine.  # noqa: E501
        :type snapshot_count: int
        :param current_state_modified: The current_state_modified of this Machine.  # noqa: E501
        :type current_state_modified: bool
        :param shared_folders: The shared_folders of this Machine.  # noqa: E501
        :type shared_folders: List[SharedFolder]
        :param clipboard_mode: The clipboard_mode of this Machine.  # noqa: E501
        :type clipboard_mode: ClipboardMode
        :param clipboard_file_transfers_enabled: The clipboard_file_transfers_enabled of this Machine.  # noqa: E501
        :type clipboard_file_transfers_enabled: bool
        :param dn_d_mode: The dn_d_mode of this Machine.  # noqa: E501
        :type dn_d_mode: DnDMode
        :param teleporter_enabled: The teleporter_enabled of this Machine.  # noqa: E501
        :type teleporter_enabled: bool
        :param teleporter_port: The teleporter_port of this Machine.  # noqa: E501
        :type teleporter_port: int
        :param teleporter_address: The teleporter_address of this Machine.  # noqa: E501
        :type teleporter_address: str
        :param teleporter_password: The teleporter_password of this Machine.  # noqa: E501
        :type teleporter_password: str
        :param paravirt_provider: The paravirt_provider of this Machine.  # noqa: E501
        :type paravirt_provider: ParavirtProvider
        :param io_cache_enabled: The io_cache_enabled of this Machine.  # noqa: E501
        :type io_cache_enabled: bool
        :param io_cache_size: The io_cache_size of this Machine.  # noqa: E501
        :type io_cache_size: int
        :param pci_device_assignments: The pci_device_assignments of this Machine.  # noqa: E501
        :type pci_device_assignments: List[PCIDeviceAttachment]
        :param bandwidth_control: The bandwidth_control of this Machine.  # noqa: E501
        :type bandwidth_control: BandwidthControl
        :param tracing_enabled: The tracing_enabled of this Machine.  # noqa: E501
        :type tracing_enabled: bool
        :param tracing_config: The tracing_config of this Machine.  # noqa: E501
        :type tracing_config: str
        :param allow_tracing_to_access_vm: The allow_tracing_to_access_vm of this Machine.  # noqa: E501
        :type allow_tracing_to_access_vm: bool
        :param autostart_enabled: The autostart_enabled of this Machine.  # noqa: E501
        :type autostart_enabled: bool
        :param autostart_delay: The autostart_delay of this Machine.  # noqa: E501
        :type autostart_delay: int
        :param autostop_type: The autostop_type of this Machine.  # noqa: E501
        :type autostop_type: AutostopType
        :param default_frontend: The default_frontend of this Machine.  # noqa: E501
        :type default_frontend: str
        :param usb_proxy_available: The usb_proxy_available of this Machine.  # noqa: E501
        :type usb_proxy_available: bool
        :param vm_process_priority: The vm_process_priority of this Machine.  # noqa: E501
        :type vm_process_priority: VMProcPriority
        :param paravirt_debug: The paravirt_debug of this Machine.  # noqa: E501
        :type paravirt_debug: str
        :param cpu_profile: The cpu_profile of this Machine.  # noqa: E501
        :type cpu_profile: str
        :param state_key_id: The state_key_id of this Machine.  # noqa: E501
        :type state_key_id: str
        :param state_key_store: The state_key_store of this Machine.  # noqa: E501
        :type state_key_store: str
        :param log_key_id: The log_key_id of this Machine.  # noqa: E501
        :type log_key_id: str
        :param log_key_store: The log_key_store of this Machine.  # noqa: E501
        :type log_key_store: str
        :param guest_debug_control: The guest_debug_control of this Machine.  # noqa: E501
        :type guest_debug_control: GuestDebugControl
        """
        self.swagger_types = {
            'icon': str,
            'accessible': bool,
            'access_error': VirtualBoxErrorInfo,
            'name': str,
            'description': str,
            'id': str,
            'groups': List[str],
            'os_type_id': str,
            'hardware_version': str,
            'hardware_uuid': str,
            'cpu_count': int,
            'cpu_hot_plug_enabled': bool,
            'cpu_execution_cap': int,
            'cpuid_portability_level': int,
            'memory_size': int,
            'memory_balloon_size': int,
            'page_fusion_enabled': bool,
            'graphics_adapter': GraphicsAdapter,
            'platform': Platform,
            'firmware_settings': FirmwareSettings,
            'recording_settings': RecordingSettings,
            'pointing_hid_type': PointingHIDType,
            'keyboard_hid_type': KeyboardHIDType,
            'snapshot_folder': str,
            'vrde_server': VRDEServer,
            'emulated_usb_card_reader_enabled': bool,
            'medium_attachments': List[MediumAttachment],
            'usb_controllers': List[USBController],
            'usb_device_filters': USBDeviceFilters,
            'audio_settings': AudioSettings,
            'storage_controllers': List[StorageController],
            'settings_file_path': str,
            'session_state': SessionState,
            'session_name': str,
            'session_pid': int,
            'state': MachineState,
            'last_state_change': int,
            'state_file_path': str,
            'log_folder': str,
            'current_snapshot': Snapshot,
            'snapshot_count': int,
            'current_state_modified': bool,
            'shared_folders': List[SharedFolder],
            'clipboard_mode': ClipboardMode,
            'clipboard_file_transfers_enabled': bool,
            'dn_d_mode': DnDMode,
            'teleporter_enabled': bool,
            'teleporter_port': int,
            'teleporter_address': str,
            'teleporter_password': str,
            'paravirt_provider': ParavirtProvider,
            'io_cache_enabled': bool,
            'io_cache_size': int,
            'pci_device_assignments': List[PCIDeviceAttachment],
            'bandwidth_control': BandwidthControl,
            'tracing_enabled': bool,
            'tracing_config': str,
            'allow_tracing_to_access_vm': bool,
            'autostart_enabled': bool,
            'autostart_delay': int,
            'autostop_type': AutostopType,
            'default_frontend': str,
            'usb_proxy_available': bool,
            'vm_process_priority': VMProcPriority,
            'paravirt_debug': str,
            'cpu_profile': str,
            'state_key_id': str,
            'state_key_store': str,
            'log_key_id': str,
            'log_key_store': str,
            'guest_debug_control': GuestDebugControl
        }

        self.attribute_map = {
            'icon': 'icon',
            'accessible': 'accessible',
            'access_error': 'accessError',
            'name': 'name',
            'description': 'description',
            'id': 'id',
            'groups': 'groups',
            'os_type_id': 'OSTypeId',
            'hardware_version': 'hardwareVersion',
            'hardware_uuid': 'hardwareUUID',
            'cpu_count': 'CPUCount',
            'cpu_hot_plug_enabled': 'CPUHotPlugEnabled',
            'cpu_execution_cap': 'CPUExecutionCap',
            'cpuid_portability_level': 'CPUIDPortabilityLevel',
            'memory_size': 'memorySize',
            'memory_balloon_size': 'memoryBalloonSize',
            'page_fusion_enabled': 'pageFusionEnabled',
            'graphics_adapter': 'graphicsAdapter',
            'platform': 'platform',
            'firmware_settings': 'firmwareSettings',
            'recording_settings': 'recordingSettings',
            'pointing_hid_type': 'pointingHIDType',
            'keyboard_hid_type': 'keyboardHIDType',
            'snapshot_folder': 'snapshotFolder',
            'vrde_server': 'VRDEServer',
            'emulated_usb_card_reader_enabled': 'emulatedUSBCardReaderEnabled',
            'medium_attachments': 'mediumAttachments',
            'usb_controllers': 'USBControllers',
            'usb_device_filters': 'USBDeviceFilters',
            'audio_settings': 'audioSettings',
            'storage_controllers': 'storageControllers',
            'settings_file_path': 'settingsFilePath',
            'session_state': 'sessionState',
            'session_name': 'sessionName',
            'session_pid': 'sessionPID',
            'state': 'state',
            'last_state_change': 'lastStateChange',
            'state_file_path': 'stateFilePath',
            'log_folder': 'logFolder',
            'current_snapshot': 'currentSnapshot',
            'snapshot_count': 'snapshotCount',
            'current_state_modified': 'currentStateModified',
            'shared_folders': 'sharedFolders',
            'clipboard_mode': 'clipboardMode',
            'clipboard_file_transfers_enabled': 'clipboardFileTransfersEnabled',
            'dn_d_mode': 'dnDMode',
            'teleporter_enabled': 'teleporterEnabled',
            'teleporter_port': 'teleporterPort',
            'teleporter_address': 'teleporterAddress',
            'teleporter_password': 'teleporterPassword',
            'paravirt_provider': 'paravirtProvider',
            'io_cache_enabled': 'IOCacheEnabled',
            'io_cache_size': 'IOCacheSize',
            'pci_device_assignments': 'PCIDeviceAssignments',
            'bandwidth_control': 'bandwidthControl',
            'tracing_enabled': 'tracingEnabled',
            'tracing_config': 'tracingConfig',
            'allow_tracing_to_access_vm': 'allowTracingToAccessVM',
            'autostart_enabled': 'autostartEnabled',
            'autostart_delay': 'autostartDelay',
            'autostop_type': 'autostopType',
            'default_frontend': 'defaultFrontend',
            'usb_proxy_available': 'USBProxyAvailable',
            'vm_process_priority': 'VMProcessPriority',
            'paravirt_debug': 'paravirtDebug',
            'cpu_profile': 'CPUProfile',
            'state_key_id': 'stateKeyId',
            'state_key_store': 'stateKeyStore',
            'log_key_id': 'logKeyId',
            'log_key_store': 'logKeyStore',
            'guest_debug_control': 'guestDebugControl'
        }

        self._icon = icon
        self._accessible = accessible
        self._access_error = access_error
        self._name = name
        self._description = description
        self._id = id
        self._groups = groups
        self._os_type_id = os_type_id
        self._hardware_version = hardware_version
        self._hardware_uuid = hardware_uuid
        self._cpu_count = cpu_count
        self._cpu_hot_plug_enabled = cpu_hot_plug_enabled
        self._cpu_execution_cap = cpu_execution_cap
        self._cpuid_portability_level = cpuid_portability_level
        self._memory_size = memory_size
        self._memory_balloon_size = memory_balloon_size
        self._page_fusion_enabled = page_fusion_enabled
        self._graphics_adapter = graphics_adapter
        self._platform = platform
        self._firmware_settings = firmware_settings
        self._recording_settings = recording_settings
        self._pointing_hid_type = pointing_hid_type
        self._keyboard_hid_type = keyboard_hid_type
        self._snapshot_folder = snapshot_folder
        self._vrde_server = vrde_server
        self._emulated_usb_card_reader_enabled = emulated_usb_card_reader_enabled
        self._medium_attachments = medium_attachments
        self._usb_controllers = usb_controllers
        self._usb_device_filters = usb_device_filters
        self._audio_settings = audio_settings
        self._storage_controllers = storage_controllers
        self._settings_file_path = settings_file_path
        self._session_state = session_state
        self._session_name = session_name
        self._session_pid = session_pid
        self._state = state
        self._last_state_change = last_state_change
        self._state_file_path = state_file_path
        self._log_folder = log_folder
        self._current_snapshot = current_snapshot
        self._snapshot_count = snapshot_count
        self._current_state_modified = current_state_modified
        self._shared_folders = shared_folders
        self._clipboard_mode = clipboard_mode
        self._clipboard_file_transfers_enabled = clipboard_file_transfers_enabled
        self._dn_d_mode = dn_d_mode
        self._teleporter_enabled = teleporter_enabled
        self._teleporter_port = teleporter_port
        self._teleporter_address = teleporter_address
        self._teleporter_password = teleporter_password
        self._paravirt_provider = paravirt_provider
        self._io_cache_enabled = io_cache_enabled
        self._io_cache_size = io_cache_size
        self._pci_device_assignments = pci_device_assignments
        self._bandwidth_control = bandwidth_control
        self._tracing_enabled = tracing_enabled
        self._tracing_config = tracing_config
        self._allow_tracing_to_access_vm = allow_tracing_to_access_vm
        self._autostart_enabled = autostart_enabled
        self._autostart_delay = autostart_delay
        self._autostop_type = autostop_type
        self._default_frontend = default_frontend
        self._usb_proxy_available = usb_proxy_available
        self._vm_process_priority = vm_process_priority
        self._paravirt_debug = paravirt_debug
        self._cpu_profile = cpu_profile
        self._state_key_id = state_key_id
        self._state_key_store = state_key_store
        self._log_key_id = log_key_id
        self._log_key_store = log_key_store
        self._guest_debug_control = guest_debug_control

    @classmethod
    def from_dict(cls, dikt) -> 'Machine':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Machine of this Machine.  # noqa: E501
        :rtype: Machine
        """
        return util.deserialize_model(dikt, cls)

    @property
    def icon(self) -> str:
        """Gets the icon of this Machine.


        :return: The icon of this Machine.
        :rtype: str
        """
        return self._icon

    @icon.setter
    def icon(self, icon: str):
        """Sets the icon of this Machine.


        :param icon: The icon of this Machine.
        :type icon: str
        """

        self._icon = icon

    @property
    def accessible(self) -> bool:
        """Gets the accessible of this Machine.


        :return: The accessible of this Machine.
        :rtype: bool
        """
        return self._accessible

    @accessible.setter
    def accessible(self, accessible: bool):
        """Sets the accessible of this Machine.


        :param accessible: The accessible of this Machine.
        :type accessible: bool
        """

        self._accessible = accessible

    @property
    def access_error(self) -> VirtualBoxErrorInfo:
        """Gets the access_error of this Machine.


        :return: The access_error of this Machine.
        :rtype: VirtualBoxErrorInfo
        """
        return self._access_error

    @access_error.setter
    def access_error(self, access_error: VirtualBoxErrorInfo):
        """Sets the access_error of this Machine.


        :param access_error: The access_error of this Machine.
        :type access_error: VirtualBoxErrorInfo
        """

        self._access_error = access_error

    @property
    def name(self) -> str:
        """Gets the name of this Machine.


        :return: The name of this Machine.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Machine.


        :param name: The name of this Machine.
        :type name: str
        """

        self._name = name

    @property
    def description(self) -> str:
        """Gets the description of this Machine.


        :return: The description of this Machine.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this Machine.


        :param description: The description of this Machine.
        :type description: str
        """

        self._description = description

    @property
    def id(self) -> str:
        """Gets the id of this Machine.


        :return: The id of this Machine.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this Machine.


        :param id: The id of this Machine.
        :type id: str
        """

        self._id = id

    @property
    def groups(self) -> List[str]:
        """Gets the groups of this Machine.


        :return: The groups of this Machine.
        :rtype: List[str]
        """
        return self._groups

    @groups.setter
    def groups(self, groups: List[str]):
        """Sets the groups of this Machine.


        :param groups: The groups of this Machine.
        :type groups: List[str]
        """

        self._groups = groups

    @property
    def os_type_id(self) -> str:
        """Gets the os_type_id of this Machine.


        :return: The os_type_id of this Machine.
        :rtype: str
        """
        return self._os_type_id

    @os_type_id.setter
    def os_type_id(self, os_type_id: str):
        """Sets the os_type_id of this Machine.


        :param os_type_id: The os_type_id of this Machine.
        :type os_type_id: str
        """

        self._os_type_id = os_type_id

    @property
    def hardware_version(self) -> str:
        """Gets the hardware_version of this Machine.


        :return: The hardware_version of this Machine.
        :rtype: str
        """
        return self._hardware_version

    @hardware_version.setter
    def hardware_version(self, hardware_version: str):
        """Sets the hardware_version of this Machine.


        :param hardware_version: The hardware_version of this Machine.
        :type hardware_version: str
        """

        self._hardware_version = hardware_version

    @property
    def hardware_uuid(self) -> str:
        """Gets the hardware_uuid of this Machine.


        :return: The hardware_uuid of this Machine.
        :rtype: str
        """
        return self._hardware_uuid

    @hardware_uuid.setter
    def hardware_uuid(self, hardware_uuid: str):
        """Sets the hardware_uuid of this Machine.


        :param hardware_uuid: The hardware_uuid of this Machine.
        :type hardware_uuid: str
        """

        self._hardware_uuid = hardware_uuid

    @property
    def cpu_count(self) -> int:
        """Gets the cpu_count of this Machine.


        :return: The cpu_count of this Machine.
        :rtype: int
        """
        return self._cpu_count

    @cpu_count.setter
    def cpu_count(self, cpu_count: int):
        """Sets the cpu_count of this Machine.


        :param cpu_count: The cpu_count of this Machine.
        :type cpu_count: int
        """

        self._cpu_count = cpu_count

    @property
    def cpu_hot_plug_enabled(self) -> bool:
        """Gets the cpu_hot_plug_enabled of this Machine.


        :return: The cpu_hot_plug_enabled of this Machine.
        :rtype: bool
        """
        return self._cpu_hot_plug_enabled

    @cpu_hot_plug_enabled.setter
    def cpu_hot_plug_enabled(self, cpu_hot_plug_enabled: bool):
        """Sets the cpu_hot_plug_enabled of this Machine.


        :param cpu_hot_plug_enabled: The cpu_hot_plug_enabled of this Machine.
        :type cpu_hot_plug_enabled: bool
        """

        self._cpu_hot_plug_enabled = cpu_hot_plug_enabled

    @property
    def cpu_execution_cap(self) -> int:
        """Gets the cpu_execution_cap of this Machine.


        :return: The cpu_execution_cap of this Machine.
        :rtype: int
        """
        return self._cpu_execution_cap

    @cpu_execution_cap.setter
    def cpu_execution_cap(self, cpu_execution_cap: int):
        """Sets the cpu_execution_cap of this Machine.


        :param cpu_execution_cap: The cpu_execution_cap of this Machine.
        :type cpu_execution_cap: int
        """

        self._cpu_execution_cap = cpu_execution_cap

    @property
    def cpuid_portability_level(self) -> int:
        """Gets the cpuid_portability_level of this Machine.


        :return: The cpuid_portability_level of this Machine.
        :rtype: int
        """
        return self._cpuid_portability_level

    @cpuid_portability_level.setter
    def cpuid_portability_level(self, cpuid_portability_level: int):
        """Sets the cpuid_portability_level of this Machine.


        :param cpuid_portability_level: The cpuid_portability_level of this Machine.
        :type cpuid_portability_level: int
        """

        self._cpuid_portability_level = cpuid_portability_level

    @property
    def memory_size(self) -> int:
        """Gets the memory_size of this Machine.


        :return: The memory_size of this Machine.
        :rtype: int
        """
        return self._memory_size

    @memory_size.setter
    def memory_size(self, memory_size: int):
        """Sets the memory_size of this Machine.


        :param memory_size: The memory_size of this Machine.
        :type memory_size: int
        """

        self._memory_size = memory_size

    @property
    def memory_balloon_size(self) -> int:
        """Gets the memory_balloon_size of this Machine.


        :return: The memory_balloon_size of this Machine.
        :rtype: int
        """
        return self._memory_balloon_size

    @memory_balloon_size.setter
    def memory_balloon_size(self, memory_balloon_size: int):
        """Sets the memory_balloon_size of this Machine.


        :param memory_balloon_size: The memory_balloon_size of this Machine.
        :type memory_balloon_size: int
        """

        self._memory_balloon_size = memory_balloon_size

    @property
    def page_fusion_enabled(self) -> bool:
        """Gets the page_fusion_enabled of this Machine.


        :return: The page_fusion_enabled of this Machine.
        :rtype: bool
        """
        return self._page_fusion_enabled

    @page_fusion_enabled.setter
    def page_fusion_enabled(self, page_fusion_enabled: bool):
        """Sets the page_fusion_enabled of this Machine.


        :param page_fusion_enabled: The page_fusion_enabled of this Machine.
        :type page_fusion_enabled: bool
        """

        self._page_fusion_enabled = page_fusion_enabled

    @property
    def graphics_adapter(self) -> GraphicsAdapter:
        """Gets the graphics_adapter of this Machine.


        :return: The graphics_adapter of this Machine.
        :rtype: GraphicsAdapter
        """
        return self._graphics_adapter

    @graphics_adapter.setter
    def graphics_adapter(self, graphics_adapter: GraphicsAdapter):
        """Sets the graphics_adapter of this Machine.


        :param graphics_adapter: The graphics_adapter of this Machine.
        :type graphics_adapter: GraphicsAdapter
        """

        self._graphics_adapter = graphics_adapter

    @property
    def platform(self) -> Platform:
        """Gets the platform of this Machine.


        :return: The platform of this Machine.
        :rtype: Platform
        """
        return self._platform

    @platform.setter
    def platform(self, platform: Platform):
        """Sets the platform of this Machine.


        :param platform: The platform of this Machine.
        :type platform: Platform
        """

        self._platform = platform

    @property
    def firmware_settings(self) -> FirmwareSettings:
        """Gets the firmware_settings of this Machine.


        :return: The firmware_settings of this Machine.
        :rtype: FirmwareSettings
        """
        return self._firmware_settings

    @firmware_settings.setter
    def firmware_settings(self, firmware_settings: FirmwareSettings):
        """Sets the firmware_settings of this Machine.


        :param firmware_settings: The firmware_settings of this Machine.
        :type firmware_settings: FirmwareSettings
        """

        self._firmware_settings = firmware_settings

    @property
    def recording_settings(self) -> RecordingSettings:
        """Gets the recording_settings of this Machine.


        :return: The recording_settings of this Machine.
        :rtype: RecordingSettings
        """
        return self._recording_settings

    @recording_settings.setter
    def recording_settings(self, recording_settings: RecordingSettings):
        """Sets the recording_settings of this Machine.


        :param recording_settings: The recording_settings of this Machine.
        :type recording_settings: RecordingSettings
        """

        self._recording_settings = recording_settings

    @property
    def pointing_hid_type(self) -> PointingHIDType:
        """Gets the pointing_hid_type of this Machine.


        :return: The pointing_hid_type of this Machine.
        :rtype: PointingHIDType
        """
        return self._pointing_hid_type

    @pointing_hid_type.setter
    def pointing_hid_type(self, pointing_hid_type: PointingHIDType):
        """Sets the pointing_hid_type of this Machine.


        :param pointing_hid_type: The pointing_hid_type of this Machine.
        :type pointing_hid_type: PointingHIDType
        """

        self._pointing_hid_type = pointing_hid_type

    @property
    def keyboard_hid_type(self) -> KeyboardHIDType:
        """Gets the keyboard_hid_type of this Machine.


        :return: The keyboard_hid_type of this Machine.
        :rtype: KeyboardHIDType
        """
        return self._keyboard_hid_type

    @keyboard_hid_type.setter
    def keyboard_hid_type(self, keyboard_hid_type: KeyboardHIDType):
        """Sets the keyboard_hid_type of this Machine.


        :param keyboard_hid_type: The keyboard_hid_type of this Machine.
        :type keyboard_hid_type: KeyboardHIDType
        """

        self._keyboard_hid_type = keyboard_hid_type

    @property
    def snapshot_folder(self) -> str:
        """Gets the snapshot_folder of this Machine.


        :return: The snapshot_folder of this Machine.
        :rtype: str
        """
        return self._snapshot_folder

    @snapshot_folder.setter
    def snapshot_folder(self, snapshot_folder: str):
        """Sets the snapshot_folder of this Machine.


        :param snapshot_folder: The snapshot_folder of this Machine.
        :type snapshot_folder: str
        """

        self._snapshot_folder = snapshot_folder

    @property
    def vrde_server(self) -> VRDEServer:
        """Gets the vrde_server of this Machine.


        :return: The vrde_server of this Machine.
        :rtype: VRDEServer
        """
        return self._vrde_server

    @vrde_server.setter
    def vrde_server(self, vrde_server: VRDEServer):
        """Sets the vrde_server of this Machine.


        :param vrde_server: The vrde_server of this Machine.
        :type vrde_server: VRDEServer
        """

        self._vrde_server = vrde_server

    @property
    def emulated_usb_card_reader_enabled(self) -> bool:
        """Gets the emulated_usb_card_reader_enabled of this Machine.


        :return: The emulated_usb_card_reader_enabled of this Machine.
        :rtype: bool
        """
        return self._emulated_usb_card_reader_enabled

    @emulated_usb_card_reader_enabled.setter
    def emulated_usb_card_reader_enabled(self, emulated_usb_card_reader_enabled: bool):
        """Sets the emulated_usb_card_reader_enabled of this Machine.


        :param emulated_usb_card_reader_enabled: The emulated_usb_card_reader_enabled of this Machine.
        :type emulated_usb_card_reader_enabled: bool
        """

        self._emulated_usb_card_reader_enabled = emulated_usb_card_reader_enabled

    @property
    def medium_attachments(self) -> List[MediumAttachment]:
        """Gets the medium_attachments of this Machine.


        :return: The medium_attachments of this Machine.
        :rtype: List[MediumAttachment]
        """
        return self._medium_attachments

    @medium_attachments.setter
    def medium_attachments(self, medium_attachments: List[MediumAttachment]):
        """Sets the medium_attachments of this Machine.


        :param medium_attachments: The medium_attachments of this Machine.
        :type medium_attachments: List[MediumAttachment]
        """

        self._medium_attachments = medium_attachments

    @property
    def usb_controllers(self) -> List[USBController]:
        """Gets the usb_controllers of this Machine.


        :return: The usb_controllers of this Machine.
        :rtype: List[USBController]
        """
        return self._usb_controllers

    @usb_controllers.setter
    def usb_controllers(self, usb_controllers: List[USBController]):
        """Sets the usb_controllers of this Machine.


        :param usb_controllers: The usb_controllers of this Machine.
        :type usb_controllers: List[USBController]
        """

        self._usb_controllers = usb_controllers

    @property
    def usb_device_filters(self) -> USBDeviceFilters:
        """Gets the usb_device_filters of this Machine.


        :return: The usb_device_filters of this Machine.
        :rtype: USBDeviceFilters
        """
        return self._usb_device_filters

    @usb_device_filters.setter
    def usb_device_filters(self, usb_device_filters: USBDeviceFilters):
        """Sets the usb_device_filters of this Machine.


        :param usb_device_filters: The usb_device_filters of this Machine.
        :type usb_device_filters: USBDeviceFilters
        """

        self._usb_device_filters = usb_device_filters

    @property
    def audio_settings(self) -> AudioSettings:
        """Gets the audio_settings of this Machine.


        :return: The audio_settings of this Machine.
        :rtype: AudioSettings
        """
        return self._audio_settings

    @audio_settings.setter
    def audio_settings(self, audio_settings: AudioSettings):
        """Sets the audio_settings of this Machine.


        :param audio_settings: The audio_settings of this Machine.
        :type audio_settings: AudioSettings
        """

        self._audio_settings = audio_settings

    @property
    def storage_controllers(self) -> List[StorageController]:
        """Gets the storage_controllers of this Machine.


        :return: The storage_controllers of this Machine.
        :rtype: List[StorageController]
        """
        return self._storage_controllers

    @storage_controllers.setter
    def storage_controllers(self, storage_controllers: List[StorageController]):
        """Sets the storage_controllers of this Machine.


        :param storage_controllers: The storage_controllers of this Machine.
        :type storage_controllers: List[StorageController]
        """

        self._storage_controllers = storage_controllers

    @property
    def settings_file_path(self) -> str:
        """Gets the settings_file_path of this Machine.


        :return: The settings_file_path of this Machine.
        :rtype: str
        """
        return self._settings_file_path

    @settings_file_path.setter
    def settings_file_path(self, settings_file_path: str):
        """Sets the settings_file_path of this Machine.


        :param settings_file_path: The settings_file_path of this Machine.
        :type settings_file_path: str
        """

        self._settings_file_path = settings_file_path

    @property
    def session_state(self) -> SessionState:
        """Gets the session_state of this Machine.


        :return: The session_state of this Machine.
        :rtype: SessionState
        """
        return self._session_state

    @session_state.setter
    def session_state(self, session_state: SessionState):
        """Sets the session_state of this Machine.


        :param session_state: The session_state of this Machine.
        :type session_state: SessionState
        """

        self._session_state = session_state

    @property
    def session_name(self) -> str:
        """Gets the session_name of this Machine.


        :return: The session_name of this Machine.
        :rtype: str
        """
        return self._session_name

    @session_name.setter
    def session_name(self, session_name: str):
        """Sets the session_name of this Machine.


        :param session_name: The session_name of this Machine.
        :type session_name: str
        """

        self._session_name = session_name

    @property
    def session_pid(self) -> int:
        """Gets the session_pid of this Machine.


        :return: The session_pid of this Machine.
        :rtype: int
        """
        return self._session_pid

    @session_pid.setter
    def session_pid(self, session_pid: int):
        """Sets the session_pid of this Machine.


        :param session_pid: The session_pid of this Machine.
        :type session_pid: int
        """

        self._session_pid = session_pid

    @property
    def state(self) -> MachineState:
        """Gets the state of this Machine.


        :return: The state of this Machine.
        :rtype: MachineState
        """
        return self._state

    @state.setter
    def state(self, state: MachineState):
        """Sets the state of this Machine.


        :param state: The state of this Machine.
        :type state: MachineState
        """

        self._state = state

    @property
    def last_state_change(self) -> int:
        """Gets the last_state_change of this Machine.


        :return: The last_state_change of this Machine.
        :rtype: int
        """
        return self._last_state_change

    @last_state_change.setter
    def last_state_change(self, last_state_change: int):
        """Sets the last_state_change of this Machine.


        :param last_state_change: The last_state_change of this Machine.
        :type last_state_change: int
        """

        self._last_state_change = last_state_change

    @property
    def state_file_path(self) -> str:
        """Gets the state_file_path of this Machine.


        :return: The state_file_path of this Machine.
        :rtype: str
        """
        return self._state_file_path

    @state_file_path.setter
    def state_file_path(self, state_file_path: str):
        """Sets the state_file_path of this Machine.


        :param state_file_path: The state_file_path of this Machine.
        :type state_file_path: str
        """

        self._state_file_path = state_file_path

    @property
    def log_folder(self) -> str:
        """Gets the log_folder of this Machine.


        :return: The log_folder of this Machine.
        :rtype: str
        """
        return self._log_folder

    @log_folder.setter
    def log_folder(self, log_folder: str):
        """Sets the log_folder of this Machine.


        :param log_folder: The log_folder of this Machine.
        :type log_folder: str
        """

        self._log_folder = log_folder

    @property
    def current_snapshot(self) -> Snapshot:
        """Gets the current_snapshot of this Machine.


        :return: The current_snapshot of this Machine.
        :rtype: Snapshot
        """
        return self._current_snapshot

    @current_snapshot.setter
    def current_snapshot(self, current_snapshot: Snapshot):
        """Sets the current_snapshot of this Machine.


        :param current_snapshot: The current_snapshot of this Machine.
        :type current_snapshot: Snapshot
        """

        self._current_snapshot = current_snapshot

    @property
    def snapshot_count(self) -> int:
        """Gets the snapshot_count of this Machine.


        :return: The snapshot_count of this Machine.
        :rtype: int
        """
        return self._snapshot_count

    @snapshot_count.setter
    def snapshot_count(self, snapshot_count: int):
        """Sets the snapshot_count of this Machine.


        :param snapshot_count: The snapshot_count of this Machine.
        :type snapshot_count: int
        """

        self._snapshot_count = snapshot_count

    @property
    def current_state_modified(self) -> bool:
        """Gets the current_state_modified of this Machine.


        :return: The current_state_modified of this Machine.
        :rtype: bool
        """
        return self._current_state_modified

    @current_state_modified.setter
    def current_state_modified(self, current_state_modified: bool):
        """Sets the current_state_modified of this Machine.


        :param current_state_modified: The current_state_modified of this Machine.
        :type current_state_modified: bool
        """

        self._current_state_modified = current_state_modified

    @property
    def shared_folders(self) -> List[SharedFolder]:
        """Gets the shared_folders of this Machine.


        :return: The shared_folders of this Machine.
        :rtype: List[SharedFolder]
        """
        return self._shared_folders

    @shared_folders.setter
    def shared_folders(self, shared_folders: List[SharedFolder]):
        """Sets the shared_folders of this Machine.


        :param shared_folders: The shared_folders of this Machine.
        :type shared_folders: List[SharedFolder]
        """

        self._shared_folders = shared_folders

    @property
    def clipboard_mode(self) -> ClipboardMode:
        """Gets the clipboard_mode of this Machine.


        :return: The clipboard_mode of this Machine.
        :rtype: ClipboardMode
        """
        return self._clipboard_mode

    @clipboard_mode.setter
    def clipboard_mode(self, clipboard_mode: ClipboardMode):
        """Sets the clipboard_mode of this Machine.


        :param clipboard_mode: The clipboard_mode of this Machine.
        :type clipboard_mode: ClipboardMode
        """

        self._clipboard_mode = clipboard_mode

    @property
    def clipboard_file_transfers_enabled(self) -> bool:
        """Gets the clipboard_file_transfers_enabled of this Machine.


        :return: The clipboard_file_transfers_enabled of this Machine.
        :rtype: bool
        """
        return self._clipboard_file_transfers_enabled

    @clipboard_file_transfers_enabled.setter
    def clipboard_file_transfers_enabled(self, clipboard_file_transfers_enabled: bool):
        """Sets the clipboard_file_transfers_enabled of this Machine.


        :param clipboard_file_transfers_enabled: The clipboard_file_transfers_enabled of this Machine.
        :type clipboard_file_transfers_enabled: bool
        """

        self._clipboard_file_transfers_enabled = clipboard_file_transfers_enabled

    @property
    def dn_d_mode(self) -> DnDMode:
        """Gets the dn_d_mode of this Machine.


        :return: The dn_d_mode of this Machine.
        :rtype: DnDMode
        """
        return self._dn_d_mode

    @dn_d_mode.setter
    def dn_d_mode(self, dn_d_mode: DnDMode):
        """Sets the dn_d_mode of this Machine.


        :param dn_d_mode: The dn_d_mode of this Machine.
        :type dn_d_mode: DnDMode
        """

        self._dn_d_mode = dn_d_mode

    @property
    def teleporter_enabled(self) -> bool:
        """Gets the teleporter_enabled of this Machine.


        :return: The teleporter_enabled of this Machine.
        :rtype: bool
        """
        return self._teleporter_enabled

    @teleporter_enabled.setter
    def teleporter_enabled(self, teleporter_enabled: bool):
        """Sets the teleporter_enabled of this Machine.


        :param teleporter_enabled: The teleporter_enabled of this Machine.
        :type teleporter_enabled: bool
        """

        self._teleporter_enabled = teleporter_enabled

    @property
    def teleporter_port(self) -> int:
        """Gets the teleporter_port of this Machine.


        :return: The teleporter_port of this Machine.
        :rtype: int
        """
        return self._teleporter_port

    @teleporter_port.setter
    def teleporter_port(self, teleporter_port: int):
        """Sets the teleporter_port of this Machine.


        :param teleporter_port: The teleporter_port of this Machine.
        :type teleporter_port: int
        """

        self._teleporter_port = teleporter_port

    @property
    def teleporter_address(self) -> str:
        """Gets the teleporter_address of this Machine.


        :return: The teleporter_address of this Machine.
        :rtype: str
        """
        return self._teleporter_address

    @teleporter_address.setter
    def teleporter_address(self, teleporter_address: str):
        """Sets the teleporter_address of this Machine.


        :param teleporter_address: The teleporter_address of this Machine.
        :type teleporter_address: str
        """

        self._teleporter_address = teleporter_address

    @property
    def teleporter_password(self) -> str:
        """Gets the teleporter_password of this Machine.


        :return: The teleporter_password of this Machine.
        :rtype: str
        """
        return self._teleporter_password

    @teleporter_password.setter
    def teleporter_password(self, teleporter_password: str):
        """Sets the teleporter_password of this Machine.


        :param teleporter_password: The teleporter_password of this Machine.
        :type teleporter_password: str
        """

        self._teleporter_password = teleporter_password

    @property
    def paravirt_provider(self) -> ParavirtProvider:
        """Gets the paravirt_provider of this Machine.


        :return: The paravirt_provider of this Machine.
        :rtype: ParavirtProvider
        """
        return self._paravirt_provider

    @paravirt_provider.setter
    def paravirt_provider(self, paravirt_provider: ParavirtProvider):
        """Sets the paravirt_provider of this Machine.


        :param paravirt_provider: The paravirt_provider of this Machine.
        :type paravirt_provider: ParavirtProvider
        """

        self._paravirt_provider = paravirt_provider

    @property
    def io_cache_enabled(self) -> bool:
        """Gets the io_cache_enabled of this Machine.


        :return: The io_cache_enabled of this Machine.
        :rtype: bool
        """
        return self._io_cache_enabled

    @io_cache_enabled.setter
    def io_cache_enabled(self, io_cache_enabled: bool):
        """Sets the io_cache_enabled of this Machine.


        :param io_cache_enabled: The io_cache_enabled of this Machine.
        :type io_cache_enabled: bool
        """

        self._io_cache_enabled = io_cache_enabled

    @property
    def io_cache_size(self) -> int:
        """Gets the io_cache_size of this Machine.


        :return: The io_cache_size of this Machine.
        :rtype: int
        """
        return self._io_cache_size

    @io_cache_size.setter
    def io_cache_size(self, io_cache_size: int):
        """Sets the io_cache_size of this Machine.


        :param io_cache_size: The io_cache_size of this Machine.
        :type io_cache_size: int
        """

        self._io_cache_size = io_cache_size

    @property
    def pci_device_assignments(self) -> List[PCIDeviceAttachment]:
        """Gets the pci_device_assignments of this Machine.


        :return: The pci_device_assignments of this Machine.
        :rtype: List[PCIDeviceAttachment]
        """
        return self._pci_device_assignments

    @pci_device_assignments.setter
    def pci_device_assignments(self, pci_device_assignments: List[PCIDeviceAttachment]):
        """Sets the pci_device_assignments of this Machine.


        :param pci_device_assignments: The pci_device_assignments of this Machine.
        :type pci_device_assignments: List[PCIDeviceAttachment]
        """

        self._pci_device_assignments = pci_device_assignments

    @property
    def bandwidth_control(self) -> BandwidthControl:
        """Gets the bandwidth_control of this Machine.


        :return: The bandwidth_control of this Machine.
        :rtype: BandwidthControl
        """
        return self._bandwidth_control

    @bandwidth_control.setter
    def bandwidth_control(self, bandwidth_control: BandwidthControl):
        """Sets the bandwidth_control of this Machine.


        :param bandwidth_control: The bandwidth_control of this Machine.
        :type bandwidth_control: BandwidthControl
        """

        self._bandwidth_control = bandwidth_control

    @property
    def tracing_enabled(self) -> bool:
        """Gets the tracing_enabled of this Machine.


        :return: The tracing_enabled of this Machine.
        :rtype: bool
        """
        return self._tracing_enabled

    @tracing_enabled.setter
    def tracing_enabled(self, tracing_enabled: bool):
        """Sets the tracing_enabled of this Machine.


        :param tracing_enabled: The tracing_enabled of this Machine.
        :type tracing_enabled: bool
        """

        self._tracing_enabled = tracing_enabled

    @property
    def tracing_config(self) -> str:
        """Gets the tracing_config of this Machine.


        :return: The tracing_config of this Machine.
        :rtype: str
        """
        return self._tracing_config

    @tracing_config.setter
    def tracing_config(self, tracing_config: str):
        """Sets the tracing_config of this Machine.


        :param tracing_config: The tracing_config of this Machine.
        :type tracing_config: str
        """

        self._tracing_config = tracing_config

    @property
    def allow_tracing_to_access_vm(self) -> bool:
        """Gets the allow_tracing_to_access_vm of this Machine.


        :return: The allow_tracing_to_access_vm of this Machine.
        :rtype: bool
        """
        return self._allow_tracing_to_access_vm

    @allow_tracing_to_access_vm.setter
    def allow_tracing_to_access_vm(self, allow_tracing_to_access_vm: bool):
        """Sets the allow_tracing_to_access_vm of this Machine.


        :param allow_tracing_to_access_vm: The allow_tracing_to_access_vm of this Machine.
        :type allow_tracing_to_access_vm: bool
        """

        self._allow_tracing_to_access_vm = allow_tracing_to_access_vm

    @property
    def autostart_enabled(self) -> bool:
        """Gets the autostart_enabled of this Machine.


        :return: The autostart_enabled of this Machine.
        :rtype: bool
        """
        return self._autostart_enabled

    @autostart_enabled.setter
    def autostart_enabled(self, autostart_enabled: bool):
        """Sets the autostart_enabled of this Machine.


        :param autostart_enabled: The autostart_enabled of this Machine.
        :type autostart_enabled: bool
        """

        self._autostart_enabled = autostart_enabled

    @property
    def autostart_delay(self) -> int:
        """Gets the autostart_delay of this Machine.


        :return: The autostart_delay of this Machine.
        :rtype: int
        """
        return self._autostart_delay

    @autostart_delay.setter
    def autostart_delay(self, autostart_delay: int):
        """Sets the autostart_delay of this Machine.


        :param autostart_delay: The autostart_delay of this Machine.
        :type autostart_delay: int
        """

        self._autostart_delay = autostart_delay

    @property
    def autostop_type(self) -> AutostopType:
        """Gets the autostop_type of this Machine.


        :return: The autostop_type of this Machine.
        :rtype: AutostopType
        """
        return self._autostop_type

    @autostop_type.setter
    def autostop_type(self, autostop_type: AutostopType):
        """Sets the autostop_type of this Machine.


        :param autostop_type: The autostop_type of this Machine.
        :type autostop_type: AutostopType
        """

        self._autostop_type = autostop_type

    @property
    def default_frontend(self) -> str:
        """Gets the default_frontend of this Machine.


        :return: The default_frontend of this Machine.
        :rtype: str
        """
        return self._default_frontend

    @default_frontend.setter
    def default_frontend(self, default_frontend: str):
        """Sets the default_frontend of this Machine.


        :param default_frontend: The default_frontend of this Machine.
        :type default_frontend: str
        """

        self._default_frontend = default_frontend

    @property
    def usb_proxy_available(self) -> bool:
        """Gets the usb_proxy_available of this Machine.


        :return: The usb_proxy_available of this Machine.
        :rtype: bool
        """
        return self._usb_proxy_available

    @usb_proxy_available.setter
    def usb_proxy_available(self, usb_proxy_available: bool):
        """Sets the usb_proxy_available of this Machine.


        :param usb_proxy_available: The usb_proxy_available of this Machine.
        :type usb_proxy_available: bool
        """

        self._usb_proxy_available = usb_proxy_available

    @property
    def vm_process_priority(self) -> VMProcPriority:
        """Gets the vm_process_priority of this Machine.


        :return: The vm_process_priority of this Machine.
        :rtype: VMProcPriority
        """
        return self._vm_process_priority

    @vm_process_priority.setter
    def vm_process_priority(self, vm_process_priority: VMProcPriority):
        """Sets the vm_process_priority of this Machine.


        :param vm_process_priority: The vm_process_priority of this Machine.
        :type vm_process_priority: VMProcPriority
        """

        self._vm_process_priority = vm_process_priority

    @property
    def paravirt_debug(self) -> str:
        """Gets the paravirt_debug of this Machine.


        :return: The paravirt_debug of this Machine.
        :rtype: str
        """
        return self._paravirt_debug

    @paravirt_debug.setter
    def paravirt_debug(self, paravirt_debug: str):
        """Sets the paravirt_debug of this Machine.


        :param paravirt_debug: The paravirt_debug of this Machine.
        :type paravirt_debug: str
        """

        self._paravirt_debug = paravirt_debug

    @property
    def cpu_profile(self) -> str:
        """Gets the cpu_profile of this Machine.


        :return: The cpu_profile of this Machine.
        :rtype: str
        """
        return self._cpu_profile

    @cpu_profile.setter
    def cpu_profile(self, cpu_profile: str):
        """Sets the cpu_profile of this Machine.


        :param cpu_profile: The cpu_profile of this Machine.
        :type cpu_profile: str
        """

        self._cpu_profile = cpu_profile

    @property
    def state_key_id(self) -> str:
        """Gets the state_key_id of this Machine.


        :return: The state_key_id of this Machine.
        :rtype: str
        """
        return self._state_key_id

    @state_key_id.setter
    def state_key_id(self, state_key_id: str):
        """Sets the state_key_id of this Machine.


        :param state_key_id: The state_key_id of this Machine.
        :type state_key_id: str
        """

        self._state_key_id = state_key_id

    @property
    def state_key_store(self) -> str:
        """Gets the state_key_store of this Machine.


        :return: The state_key_store of this Machine.
        :rtype: str
        """
        return self._state_key_store

    @state_key_store.setter
    def state_key_store(self, state_key_store: str):
        """Sets the state_key_store of this Machine.


        :param state_key_store: The state_key_store of this Machine.
        :type state_key_store: str
        """

        self._state_key_store = state_key_store

    @property
    def log_key_id(self) -> str:
        """Gets the log_key_id of this Machine.


        :return: The log_key_id of this Machine.
        :rtype: str
        """
        return self._log_key_id

    @log_key_id.setter
    def log_key_id(self, log_key_id: str):
        """Sets the log_key_id of this Machine.


        :param log_key_id: The log_key_id of this Machine.
        :type log_key_id: str
        """

        self._log_key_id = log_key_id

    @property
    def log_key_store(self) -> str:
        """Gets the log_key_store of this Machine.


        :return: The log_key_store of this Machine.
        :rtype: str
        """
        return self._log_key_store

    @log_key_store.setter
    def log_key_store(self, log_key_store: str):
        """Sets the log_key_store of this Machine.


        :param log_key_store: The log_key_store of this Machine.
        :type log_key_store: str
        """

        self._log_key_store = log_key_store

    @property
    def guest_debug_control(self) -> GuestDebugControl:
        """Gets the guest_debug_control of this Machine.


        :return: The guest_debug_control of this Machine.
        :rtype: GuestDebugControl
        """
        return self._guest_debug_control

    @guest_debug_control.setter
    def guest_debug_control(self, guest_debug_control: GuestDebugControl):
        """Sets the guest_debug_control of this Machine.


        :param guest_debug_control: The guest_debug_control of this Machine.
        :type guest_debug_control: GuestDebugControl
        """

        self._guest_debug_control = guest_debug_control
