# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401


from vbox_server.models.base_model_ import Model
from vbox_server.models.medium_state import MediumState
from vbox_server import util


class MediumStateResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, state: MediumState=None):  # noqa: E501
        """MediumStateResponse - a model defined in Swagger

        :param state: The state of this MediumStateResponse.  # noqa: E501
        :type state: MediumState
        """
        self.swagger_types = {
            'state': MediumState
        }

        self.attribute_map = {
            'state': 'state'
        }

        self._state = state

    @classmethod
    def from_dict(cls, dikt) -> 'MediumStateResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The MediumState_response of this MediumStateResponse.  # noqa: E501
        :rtype: MediumStateResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def state(self) -> MediumState:
        """Gets the state of this MediumStateResponse.


        :return: The state of this MediumStateResponse.
        :rtype: MediumState
        """
        return self._state

    @state.setter
    def state(self, state: MediumState):
        """Sets the state of this MediumStateResponse.


        :param state: The state of this MediumStateResponse.
        :type state: MediumState
        """

        self._state = state
