# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401


from vbox_server.models.base_model_ import Model
from vbox_server import util


class NATNetworkRemovePortForwardRuleRequestBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, is_ipv6: bool=None, rule_name: str=None):  # noqa: E501
        """NATNetworkRemovePortForwardRuleRequestBody - a model defined in Swagger

        :param is_ipv6: The is_ipv6 of this NATNetworkRemovePortForwardRuleRequestBody.  # noqa: E501
        :type is_ipv6: bool
        :param rule_name: The rule_name of this NATNetworkRemovePortForwardRuleRequestBody.  # noqa: E501
        :type rule_name: str
        """
        self.swagger_types = {
            'is_ipv6': bool,
            'rule_name': str
        }

        self.attribute_map = {
            'is_ipv6': 'isIpv6',
            'rule_name': 'ruleName'
        }

        self._is_ipv6 = is_ipv6
        self._rule_name = rule_name

    @classmethod
    def from_dict(cls, dikt) -> 'NATNetworkRemovePortForwardRuleRequestBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The NATNetworkRemovePortForwardRuleRequestBody of this NATNetworkRemovePortForwardRuleRequestBody.  # noqa: E501
        :rtype: NATNetworkRemovePortForwardRuleRequestBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def is_ipv6(self) -> bool:
        """Gets the is_ipv6 of this NATNetworkRemovePortForwardRuleRequestBody.


        :return: The is_ipv6 of this NATNetworkRemovePortForwardRuleRequestBody.
        :rtype: bool
        """
        return self._is_ipv6

    @is_ipv6.setter
    def is_ipv6(self, is_ipv6: bool):
        """Sets the is_ipv6 of this NATNetworkRemovePortForwardRuleRequestBody.


        :param is_ipv6: The is_ipv6 of this NATNetworkRemovePortForwardRuleRequestBody.
        :type is_ipv6: bool
        """

        self._is_ipv6 = is_ipv6

    @property
    def rule_name(self) -> str:
        """Gets the rule_name of this NATNetworkRemovePortForwardRuleRequestBody.


        :return: The rule_name of this NATNetworkRemovePortForwardRuleRequestBody.
        :rtype: str
        """
        return self._rule_name

    @rule_name.setter
    def rule_name(self, rule_name: str):
        """Sets the rule_name of this NATNetworkRemovePortForwardRuleRequestBody.


        :param rule_name: The rule_name of this NATNetworkRemovePortForwardRuleRequestBody.
        :type rule_name: str
        """

        self._rule_name = rule_name
