# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401


from vbox_server.models.base_model_ import Model
from vbox_server import util


class NATProtocol(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    UDP = "UDP"
    TCP = "TCP"

    def __init__(self):  # noqa: E501
        """NATProtocol - a model defined in Swagger

        """
        self.swagger_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'NATProtocol':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The NATProtocol of this NATProtocol.  # noqa: E501
        :rtype: NATProtocol
        """
        return util.deserialize_model(dikt, cls)
