# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401


from vbox_server.models.base_model_ import Model
from vbox_server.models.network_adapter import NetworkAdapter
from vbox_server import util


class NetworkAdapterResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, adapter: NetworkAdapter=None):  # noqa: E501
        """NetworkAdapterResponse - a model defined in Swagger

        :param adapter: The adapter of this NetworkAdapterResponse.  # noqa: E501
        :type adapter: NetworkAdapter
        """
        self.swagger_types = {
            'adapter': NetworkAdapter
        }

        self.attribute_map = {
            'adapter': 'adapter'
        }

        self._adapter = adapter

    @classmethod
    def from_dict(cls, dikt) -> 'NetworkAdapterResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The NetworkAdapter_response of this NetworkAdapterResponse.  # noqa: E501
        :rtype: NetworkAdapterResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def adapter(self) -> NetworkAdapter:
        """Gets the adapter of this NetworkAdapterResponse.


        :return: The adapter of this NetworkAdapterResponse.
        :rtype: NetworkAdapter
        """
        return self._adapter

    @adapter.setter
    def adapter(self, adapter: NetworkAdapter):
        """Sets the adapter of this NetworkAdapterResponse.


        :param adapter: The adapter of this NetworkAdapterResponse.
        :type adapter: NetworkAdapter
        """

        self._adapter = adapter
