# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401


from vbox_server.models.base_model_ import Model
from vbox_server import util


class PlatformX86(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, hpet_enabled: bool=None):  # noqa: E501
        """PlatformX86 - a model defined in Swagger

        :param hpet_enabled: The hpet_enabled of this PlatformX86.  # noqa: E501
        :type hpet_enabled: bool
        """
        self.swagger_types = {
            'hpet_enabled': bool
        }

        self.attribute_map = {
            'hpet_enabled': 'HPETEnabled'
        }

        self._hpet_enabled = hpet_enabled

    @classmethod
    def from_dict(cls, dikt) -> 'PlatformX86':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PlatformX86 of this PlatformX86.  # noqa: E501
        :rtype: PlatformX86
        """
        return util.deserialize_model(dikt, cls)

    @property
    def hpet_enabled(self) -> bool:
        """Gets the hpet_enabled of this PlatformX86.


        :return: The hpet_enabled of this PlatformX86.
        :rtype: bool
        """
        return self._hpet_enabled

    @hpet_enabled.setter
    def hpet_enabled(self, hpet_enabled: bool):
        """Sets the hpet_enabled of this PlatformX86.


        :param hpet_enabled: The hpet_enabled of this PlatformX86.
        :type hpet_enabled: bool
        """

        self._hpet_enabled = hpet_enabled
