# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401


from vbox_server.models.base_model_ import Model
from vbox_server.models.port_mode import PortMode
from vbox_server.models.uart_type import UartType
from vbox_server import util


class SerialPort(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, slot: int=None, enabled: bool=None, io_address: int=None, irq: int=None, host_mode: PortMode=None, server: bool=None, path: str=None, uart_type: UartType=None):  # noqa: E501
        """SerialPort - a model defined in Swagger

        :param slot: The slot of this SerialPort.  # noqa: E501
        :type slot: int
        :param enabled: The enabled of this SerialPort.  # noqa: E501
        :type enabled: bool
        :param io_address: The io_address of this SerialPort.  # noqa: E501
        :type io_address: int
        :param irq: The irq of this SerialPort.  # noqa: E501
        :type irq: int
        :param host_mode: The host_mode of this SerialPort.  # noqa: E501
        :type host_mode: PortMode
        :param server: The server of this SerialPort.  # noqa: E501
        :type server: bool
        :param path: The path of this SerialPort.  # noqa: E501
        :type path: str
        :param uart_type: The uart_type of this SerialPort.  # noqa: E501
        :type uart_type: UartType
        """
        self.swagger_types = {
            'slot': int,
            'enabled': bool,
            'io_address': int,
            'irq': int,
            'host_mode': PortMode,
            'server': bool,
            'path': str,
            'uart_type': UartType
        }

        self.attribute_map = {
            'slot': 'slot',
            'enabled': 'enabled',
            'io_address': 'IOAddress',
            'irq': 'IRQ',
            'host_mode': 'hostMode',
            'server': 'server',
            'path': 'path',
            'uart_type': 'uartType'
        }

        self._slot = slot
        self._enabled = enabled
        self._io_address = io_address
        self._irq = irq
        self._host_mode = host_mode
        self._server = server
        self._path = path
        self._uart_type = uart_type

    @classmethod
    def from_dict(cls, dikt) -> 'SerialPort':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SerialPort of this SerialPort.  # noqa: E501
        :rtype: SerialPort
        """
        return util.deserialize_model(dikt, cls)

    @property
    def slot(self) -> int:
        """Gets the slot of this SerialPort.


        :return: The slot of this SerialPort.
        :rtype: int
        """
        return self._slot

    @slot.setter
    def slot(self, slot: int):
        """Sets the slot of this SerialPort.


        :param slot: The slot of this SerialPort.
        :type slot: int
        """

        self._slot = slot

    @property
    def enabled(self) -> bool:
        """Gets the enabled of this SerialPort.


        :return: The enabled of this SerialPort.
        :rtype: bool
        """
        return self._enabled

    @enabled.setter
    def enabled(self, enabled: bool):
        """Sets the enabled of this SerialPort.


        :param enabled: The enabled of this SerialPort.
        :type enabled: bool
        """

        self._enabled = enabled

    @property
    def io_address(self) -> int:
        """Gets the io_address of this SerialPort.


        :return: The io_address of this SerialPort.
        :rtype: int
        """
        return self._io_address

    @io_address.setter
    def io_address(self, io_address: int):
        """Sets the io_address of this SerialPort.


        :param io_address: The io_address of this SerialPort.
        :type io_address: int
        """

        self._io_address = io_address

    @property
    def irq(self) -> int:
        """Gets the irq of this SerialPort.


        :return: The irq of this SerialPort.
        :rtype: int
        """
        return self._irq

    @irq.setter
    def irq(self, irq: int):
        """Sets the irq of this SerialPort.


        :param irq: The irq of this SerialPort.
        :type irq: int
        """

        self._irq = irq

    @property
    def host_mode(self) -> PortMode:
        """Gets the host_mode of this SerialPort.


        :return: The host_mode of this SerialPort.
        :rtype: PortMode
        """
        return self._host_mode

    @host_mode.setter
    def host_mode(self, host_mode: PortMode):
        """Sets the host_mode of this SerialPort.


        :param host_mode: The host_mode of this SerialPort.
        :type host_mode: PortMode
        """

        self._host_mode = host_mode

    @property
    def server(self) -> bool:
        """Gets the server of this SerialPort.


        :return: The server of this SerialPort.
        :rtype: bool
        """
        return self._server

    @server.setter
    def server(self, server: bool):
        """Sets the server of this SerialPort.


        :param server: The server of this SerialPort.
        :type server: bool
        """

        self._server = server

    @property
    def path(self) -> str:
        """Gets the path of this SerialPort.


        :return: The path of this SerialPort.
        :rtype: str
        """
        return self._path

    @path.setter
    def path(self, path: str):
        """Sets the path of this SerialPort.


        :param path: The path of this SerialPort.
        :type path: str
        """

        self._path = path

    @property
    def uart_type(self) -> UartType:
        """Gets the uart_type of this SerialPort.


        :return: The uart_type of this SerialPort.
        :rtype: UartType
        """
        return self._uart_type

    @uart_type.setter
    def uart_type(self, uart_type: UartType):
        """Sets the uart_type of this SerialPort.


        :param uart_type: The uart_type of this SerialPort.
        :type uart_type: UartType
        """

        self._uart_type = uart_type
