# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401


from vbox_server.models.base_model_ import Model
from vbox_server import util


class SettingsVersion(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    NULL = "null"
    V1_0 = "V1_0"
    V1_1 = "V1_1"
    V1_2 = "V1_2"
    V1_3PRE = "V1_3PRE"
    V1_3 = "V1_3"
    V1_4 = "V1_4"
    V1_5 = "V1_5"
    V1_6 = "V1_6"
    V1_7 = "V1_7"
    V1_8 = "V1_8"
    V1_9 = "V1_9"
    V1_10 = "V1_10"
    V1_11 = "V1_11"
    V1_12 = "V1_12"
    V1_13 = "V1_13"
    V1_14 = "V1_14"
    V1_15 = "V1_15"
    V1_16 = "V1_16"
    V1_17 = "V1_17"
    V1_18 = "V1_18"
    V1_19 = "V1_19"
    V1_20 = "V1_20"
    FUTURE = "FUTURE"

    def __init__(self):  # noqa: E501
        """SettingsVersion - a model defined in Swagger

        """
        self.swagger_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'SettingsVersion':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SettingsVersion of this SettingsVersion.  # noqa: E501
        :rtype: SettingsVersion
        """
        return util.deserialize_model(dikt, cls)
