# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401


from vbox_server.models.base_model_ import Model
from vbox_server.models.storage_bus import StorageBus
from vbox_server.models.storage_controller_type import StorageControllerType
from vbox_server import util


class StorageController(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, name: str=None, max_devices_per_port_count: int=None, min_port_count: int=None, max_port_count: int=None, instance: int=None, port_count: int=None, bus: StorageBus=None, controller_type: StorageControllerType=None, use_host_io_cache: bool=None, bootable: bool=None):  # noqa: E501
        """StorageController - a model defined in Swagger

        :param name: The name of this StorageController.  # noqa: E501
        :type name: str
        :param max_devices_per_port_count: The max_devices_per_port_count of this StorageController.  # noqa: E501
        :type max_devices_per_port_count: int
        :param min_port_count: The min_port_count of this StorageController.  # noqa: E501
        :type min_port_count: int
        :param max_port_count: The max_port_count of this StorageController.  # noqa: E501
        :type max_port_count: int
        :param instance: The instance of this StorageController.  # noqa: E501
        :type instance: int
        :param port_count: The port_count of this StorageController.  # noqa: E501
        :type port_count: int
        :param bus: The bus of this StorageController.  # noqa: E501
        :type bus: StorageBus
        :param controller_type: The controller_type of this StorageController.  # noqa: E501
        :type controller_type: StorageControllerType
        :param use_host_io_cache: The use_host_io_cache of this StorageController.  # noqa: E501
        :type use_host_io_cache: bool
        :param bootable: The bootable of this StorageController.  # noqa: E501
        :type bootable: bool
        """
        self.swagger_types = {
            'name': str,
            'max_devices_per_port_count': int,
            'min_port_count': int,
            'max_port_count': int,
            'instance': int,
            'port_count': int,
            'bus': StorageBus,
            'controller_type': StorageControllerType,
            'use_host_io_cache': bool,
            'bootable': bool
        }

        self.attribute_map = {
            'name': 'name',
            'max_devices_per_port_count': 'maxDevicesPerPortCount',
            'min_port_count': 'minPortCount',
            'max_port_count': 'maxPortCount',
            'instance': 'instance',
            'port_count': 'portCount',
            'bus': 'bus',
            'controller_type': 'controllerType',
            'use_host_io_cache': 'useHostIOCache',
            'bootable': 'bootable'
        }

        self._name = name
        self._max_devices_per_port_count = max_devices_per_port_count
        self._min_port_count = min_port_count
        self._max_port_count = max_port_count
        self._instance = instance
        self._port_count = port_count
        self._bus = bus
        self._controller_type = controller_type
        self._use_host_io_cache = use_host_io_cache
        self._bootable = bootable

    @classmethod
    def from_dict(cls, dikt) -> 'StorageController':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The StorageController of this StorageController.  # noqa: E501
        :rtype: StorageController
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this StorageController.


        :return: The name of this StorageController.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this StorageController.


        :param name: The name of this StorageController.
        :type name: str
        """

        self._name = name

    @property
    def max_devices_per_port_count(self) -> int:
        """Gets the max_devices_per_port_count of this StorageController.


        :return: The max_devices_per_port_count of this StorageController.
        :rtype: int
        """
        return self._max_devices_per_port_count

    @max_devices_per_port_count.setter
    def max_devices_per_port_count(self, max_devices_per_port_count: int):
        """Sets the max_devices_per_port_count of this StorageController.


        :param max_devices_per_port_count: The max_devices_per_port_count of this StorageController.
        :type max_devices_per_port_count: int
        """

        self._max_devices_per_port_count = max_devices_per_port_count

    @property
    def min_port_count(self) -> int:
        """Gets the min_port_count of this StorageController.


        :return: The min_port_count of this StorageController.
        :rtype: int
        """
        return self._min_port_count

    @min_port_count.setter
    def min_port_count(self, min_port_count: int):
        """Sets the min_port_count of this StorageController.


        :param min_port_count: The min_port_count of this StorageController.
        :type min_port_count: int
        """

        self._min_port_count = min_port_count

    @property
    def max_port_count(self) -> int:
        """Gets the max_port_count of this StorageController.


        :return: The max_port_count of this StorageController.
        :rtype: int
        """
        return self._max_port_count

    @max_port_count.setter
    def max_port_count(self, max_port_count: int):
        """Sets the max_port_count of this StorageController.


        :param max_port_count: The max_port_count of this StorageController.
        :type max_port_count: int
        """

        self._max_port_count = max_port_count

    @property
    def instance(self) -> int:
        """Gets the instance of this StorageController.


        :return: The instance of this StorageController.
        :rtype: int
        """
        return self._instance

    @instance.setter
    def instance(self, instance: int):
        """Sets the instance of this StorageController.


        :param instance: The instance of this StorageController.
        :type instance: int
        """

        self._instance = instance

    @property
    def port_count(self) -> int:
        """Gets the port_count of this StorageController.


        :return: The port_count of this StorageController.
        :rtype: int
        """
        return self._port_count

    @port_count.setter
    def port_count(self, port_count: int):
        """Sets the port_count of this StorageController.


        :param port_count: The port_count of this StorageController.
        :type port_count: int
        """

        self._port_count = port_count

    @property
    def bus(self) -> StorageBus:
        """Gets the bus of this StorageController.


        :return: The bus of this StorageController.
        :rtype: StorageBus
        """
        return self._bus

    @bus.setter
    def bus(self, bus: StorageBus):
        """Sets the bus of this StorageController.


        :param bus: The bus of this StorageController.
        :type bus: StorageBus
        """

        self._bus = bus

    @property
    def controller_type(self) -> StorageControllerType:
        """Gets the controller_type of this StorageController.


        :return: The controller_type of this StorageController.
        :rtype: StorageControllerType
        """
        return self._controller_type

    @controller_type.setter
    def controller_type(self, controller_type: StorageControllerType):
        """Sets the controller_type of this StorageController.


        :param controller_type: The controller_type of this StorageController.
        :type controller_type: StorageControllerType
        """

        self._controller_type = controller_type

    @property
    def use_host_io_cache(self) -> bool:
        """Gets the use_host_io_cache of this StorageController.


        :return: The use_host_io_cache of this StorageController.
        :rtype: bool
        """
        return self._use_host_io_cache

    @use_host_io_cache.setter
    def use_host_io_cache(self, use_host_io_cache: bool):
        """Sets the use_host_io_cache of this StorageController.


        :param use_host_io_cache: The use_host_io_cache of this StorageController.
        :type use_host_io_cache: bool
        """

        self._use_host_io_cache = use_host_io_cache

    @property
    def bootable(self) -> bool:
        """Gets the bootable of this StorageController.


        :return: The bootable of this StorageController.
        :rtype: bool
        """
        return self._bootable

    @bootable.setter
    def bootable(self, bootable: bool):
        """Sets the bootable of this StorageController.


        :param bootable: The bootable of this StorageController.
        :type bootable: bool
        """

        self._bootable = bootable
