# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401


from vbox_server.models.base_model_ import Model
from vbox_server import util


class SyntheticServerauthenticateResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, result: object=None):  # noqa: E501
        """SyntheticServerauthenticateResponse - a model defined in Swagger

        :param result: The result of this SyntheticServerauthenticateResponse.  # noqa: E501
        :type result: object
        """
        self.swagger_types = {
            'result': object
        }

        self.attribute_map = {
            'result': 'result'
        }

        self._result = result

    @classmethod
    def from_dict(cls, dikt) -> 'SyntheticServerauthenticateResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The synthetic_serverauthenticate_response of this SyntheticServerauthenticateResponse.  # noqa: E501
        :rtype: SyntheticServerauthenticateResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def result(self) -> object:
        """Gets the result of this SyntheticServerauthenticateResponse.


        :return: The result of this SyntheticServerauthenticateResponse.
        :rtype: object
        """
        return self._result

    @result.setter
    def result(self, result: object):
        """Sets the result of this SyntheticServerauthenticateResponse.


        :param result: The result of this SyntheticServerauthenticateResponse.
        :type result: object
        """

        self._result = result
