# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401


from vbox_server.models.base_model_ import Model
from vbox_server.models.audio_driver_type import AudioDriverType
from vbox_server.models.autostop_type import AutostopType
from vbox_server.models.bitmap_format import BitmapFormat
from vbox_server.models.clipboard_mode import ClipboardMode
from vbox_server.models.clone_options import CloneOptions
from vbox_server.models.dn_d_mode import DnDMode
from vbox_server.models.export_options import ExportOptions
from vbox_server.models.import_options import ImportOptions
from vbox_server.models.keyboard_hid_type import KeyboardHIDType
from vbox_server.models.medium_format import MediumFormat
from vbox_server.models.network_attachment_type import NetworkAttachmentType
from vbox_server.models.platform_architecture import PlatformArchitecture
from vbox_server.models.platform_properties import PlatformProperties
from vbox_server.models.pointing_hid_type import PointingHIDType
from vbox_server.models.port_mode import PortMode
from vbox_server.models.proxy_mode import ProxyMode
from vbox_server.models.recording_audio_codec import RecordingAudioCodec
from vbox_server.models.recording_feature import RecordingFeature
from vbox_server.models.recording_rate_control_mode import RecordingRateControlMode
from vbox_server.models.recording_video_codec import RecordingVideoCodec
from vbox_server.models.recording_video_scaling_mode import RecordingVideoScalingMode
from vbox_server.models.vfs_type import VFSType
from vbox_server.models.vm_proc_priority import VMProcPriority
from vbox_server import util


class SystemProperties(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, platform: PlatformProperties=None, min_guest_ram: int=None, max_guest_ram: int=None, min_guest_vram: int=None, max_guest_vram: int=None, min_guest_cpu_count: int=None, max_guest_cpu_count: int=None, max_guest_monitors: int=None, info_vd_size: int=None, default_machine_folder: str=None, logging_level: str=None, medium_formats: List[MediumFormat]=None, default_hard_disk_format: str=None, free_disk_space_warning: int=None, free_disk_space_percent_warning: int=None, free_disk_space_error: int=None, free_disk_space_percent_error: int=None, vrde_auth_library: str=None, web_service_auth_library: str=None, default_vrde_ext_pack: str=None, default_crypto_ext_pack: str=None, log_history_count: int=None, default_audio_driver: AudioDriverType=None, autostart_database_path: str=None, default_additions_iso: str=None, default_frontend: str=None, screen_shot_formats: List[BitmapFormat]=None, proxy_mode: ProxyMode=None, proxy_url: str=None, supported_platform_architectures: List[PlatformArchitecture]=None, supported_clipboard_modes: List[ClipboardMode]=None, supported_dn_d_modes: List[DnDMode]=None, supported_pointing_hid_types: List[PointingHIDType]=None, supported_keyboard_hid_types: List[KeyboardHIDType]=None, supported_vfs_types: List[VFSType]=None, supported_import_options: List[ImportOptions]=None, supported_export_options: List[ExportOptions]=None, supported_recording_features: List[RecordingFeature]=None, supported_recording_audio_codecs: List[RecordingAudioCodec]=None, supported_recording_video_codecs: List[RecordingVideoCodec]=None, supported_recording_vs_modes: List[RecordingVideoScalingMode]=None, supported_recording_arc_modes: List[RecordingRateControlMode]=None, supported_recording_vrc_modes: List[RecordingRateControlMode]=None, supported_clone_options: List[CloneOptions]=None, supported_autostop_types: List[AutostopType]=None, supported_vm_proc_priorities: List[VMProcPriority]=None, supported_network_attachment_types: List[NetworkAttachmentType]=None, supported_port_modes: List[PortMode]=None, supported_audio_driver_types: List[AudioDriverType]=None, language_id: str=None):  # noqa: E501
        """SystemProperties - a model defined in Swagger

        :param platform: The platform of this SystemProperties.  # noqa: E501
        :type platform: PlatformProperties
        :param min_guest_ram: The min_guest_ram of this SystemProperties.  # noqa: E501
        :type min_guest_ram: int
        :param max_guest_ram: The max_guest_ram of this SystemProperties.  # noqa: E501
        :type max_guest_ram: int
        :param min_guest_vram: The min_guest_vram of this SystemProperties.  # noqa: E501
        :type min_guest_vram: int
        :param max_guest_vram: The max_guest_vram of this SystemProperties.  # noqa: E501
        :type max_guest_vram: int
        :param min_guest_cpu_count: The min_guest_cpu_count of this SystemProperties.  # noqa: E501
        :type min_guest_cpu_count: int
        :param max_guest_cpu_count: The max_guest_cpu_count of this SystemProperties.  # noqa: E501
        :type max_guest_cpu_count: int
        :param max_guest_monitors: The max_guest_monitors of this SystemProperties.  # noqa: E501
        :type max_guest_monitors: int
        :param info_vd_size: The info_vd_size of this SystemProperties.  # noqa: E501
        :type info_vd_size: int
        :param default_machine_folder: The default_machine_folder of this SystemProperties.  # noqa: E501
        :type default_machine_folder: str
        :param logging_level: The logging_level of this SystemProperties.  # noqa: E501
        :type logging_level: str
        :param medium_formats: The medium_formats of this SystemProperties.  # noqa: E501
        :type medium_formats: List[MediumFormat]
        :param default_hard_disk_format: The default_hard_disk_format of this SystemProperties.  # noqa: E501
        :type default_hard_disk_format: str
        :param free_disk_space_warning: The free_disk_space_warning of this SystemProperties.  # noqa: E501
        :type free_disk_space_warning: int
        :param free_disk_space_percent_warning: The free_disk_space_percent_warning of this SystemProperties.  # noqa: E501
        :type free_disk_space_percent_warning: int
        :param free_disk_space_error: The free_disk_space_error of this SystemProperties.  # noqa: E501
        :type free_disk_space_error: int
        :param free_disk_space_percent_error: The free_disk_space_percent_error of this SystemProperties.  # noqa: E501
        :type free_disk_space_percent_error: int
        :param vrde_auth_library: The vrde_auth_library of this SystemProperties.  # noqa: E501
        :type vrde_auth_library: str
        :param web_service_auth_library: The web_service_auth_library of this SystemProperties.  # noqa: E501
        :type web_service_auth_library: str
        :param default_vrde_ext_pack: The default_vrde_ext_pack of this SystemProperties.  # noqa: E501
        :type default_vrde_ext_pack: str
        :param default_crypto_ext_pack: The default_crypto_ext_pack of this SystemProperties.  # noqa: E501
        :type default_crypto_ext_pack: str
        :param log_history_count: The log_history_count of this SystemProperties.  # noqa: E501
        :type log_history_count: int
        :param default_audio_driver: The default_audio_driver of this SystemProperties.  # noqa: E501
        :type default_audio_driver: AudioDriverType
        :param autostart_database_path: The autostart_database_path of this SystemProperties.  # noqa: E501
        :type autostart_database_path: str
        :param default_additions_iso: The default_additions_iso of this SystemProperties.  # noqa: E501
        :type default_additions_iso: str
        :param default_frontend: The default_frontend of this SystemProperties.  # noqa: E501
        :type default_frontend: str
        :param screen_shot_formats: The screen_shot_formats of this SystemProperties.  # noqa: E501
        :type screen_shot_formats: List[BitmapFormat]
        :param proxy_mode: The proxy_mode of this SystemProperties.  # noqa: E501
        :type proxy_mode: ProxyMode
        :param proxy_url: The proxy_url of this SystemProperties.  # noqa: E501
        :type proxy_url: str
        :param supported_platform_architectures: The supported_platform_architectures of this SystemProperties.  # noqa: E501
        :type supported_platform_architectures: List[PlatformArchitecture]
        :param supported_clipboard_modes: The supported_clipboard_modes of this SystemProperties.  # noqa: E501
        :type supported_clipboard_modes: List[ClipboardMode]
        :param supported_dn_d_modes: The supported_dn_d_modes of this SystemProperties.  # noqa: E501
        :type supported_dn_d_modes: List[DnDMode]
        :param supported_pointing_hid_types: The supported_pointing_hid_types of this SystemProperties.  # noqa: E501
        :type supported_pointing_hid_types: List[PointingHIDType]
        :param supported_keyboard_hid_types: The supported_keyboard_hid_types of this SystemProperties.  # noqa: E501
        :type supported_keyboard_hid_types: List[KeyboardHIDType]
        :param supported_vfs_types: The supported_vfs_types of this SystemProperties.  # noqa: E501
        :type supported_vfs_types: List[VFSType]
        :param supported_import_options: The supported_import_options of this SystemProperties.  # noqa: E501
        :type supported_import_options: List[ImportOptions]
        :param supported_export_options: The supported_export_options of this SystemProperties.  # noqa: E501
        :type supported_export_options: List[ExportOptions]
        :param supported_recording_features: The supported_recording_features of this SystemProperties.  # noqa: E501
        :type supported_recording_features: List[RecordingFeature]
        :param supported_recording_audio_codecs: The supported_recording_audio_codecs of this SystemProperties.  # noqa: E501
        :type supported_recording_audio_codecs: List[RecordingAudioCodec]
        :param supported_recording_video_codecs: The supported_recording_video_codecs of this SystemProperties.  # noqa: E501
        :type supported_recording_video_codecs: List[RecordingVideoCodec]
        :param supported_recording_vs_modes: The supported_recording_vs_modes of this SystemProperties.  # noqa: E501
        :type supported_recording_vs_modes: List[RecordingVideoScalingMode]
        :param supported_recording_arc_modes: The supported_recording_arc_modes of this SystemProperties.  # noqa: E501
        :type supported_recording_arc_modes: List[RecordingRateControlMode]
        :param supported_recording_vrc_modes: The supported_recording_vrc_modes of this SystemProperties.  # noqa: E501
        :type supported_recording_vrc_modes: List[RecordingRateControlMode]
        :param supported_clone_options: The supported_clone_options of this SystemProperties.  # noqa: E501
        :type supported_clone_options: List[CloneOptions]
        :param supported_autostop_types: The supported_autostop_types of this SystemProperties.  # noqa: E501
        :type supported_autostop_types: List[AutostopType]
        :param supported_vm_proc_priorities: The supported_vm_proc_priorities of this SystemProperties.  # noqa: E501
        :type supported_vm_proc_priorities: List[VMProcPriority]
        :param supported_network_attachment_types: The supported_network_attachment_types of this SystemProperties.  # noqa: E501
        :type supported_network_attachment_types: List[NetworkAttachmentType]
        :param supported_port_modes: The supported_port_modes of this SystemProperties.  # noqa: E501
        :type supported_port_modes: List[PortMode]
        :param supported_audio_driver_types: The supported_audio_driver_types of this SystemProperties.  # noqa: E501
        :type supported_audio_driver_types: List[AudioDriverType]
        :param language_id: The language_id of this SystemProperties.  # noqa: E501
        :type language_id: str
        """
        self.swagger_types = {
            'platform': PlatformProperties,
            'min_guest_ram': int,
            'max_guest_ram': int,
            'min_guest_vram': int,
            'max_guest_vram': int,
            'min_guest_cpu_count': int,
            'max_guest_cpu_count': int,
            'max_guest_monitors': int,
            'info_vd_size': int,
            'default_machine_folder': str,
            'logging_level': str,
            'medium_formats': List[MediumFormat],
            'default_hard_disk_format': str,
            'free_disk_space_warning': int,
            'free_disk_space_percent_warning': int,
            'free_disk_space_error': int,
            'free_disk_space_percent_error': int,
            'vrde_auth_library': str,
            'web_service_auth_library': str,
            'default_vrde_ext_pack': str,
            'default_crypto_ext_pack': str,
            'log_history_count': int,
            'default_audio_driver': AudioDriverType,
            'autostart_database_path': str,
            'default_additions_iso': str,
            'default_frontend': str,
            'screen_shot_formats': List[BitmapFormat],
            'proxy_mode': ProxyMode,
            'proxy_url': str,
            'supported_platform_architectures': List[PlatformArchitecture],
            'supported_clipboard_modes': List[ClipboardMode],
            'supported_dn_d_modes': List[DnDMode],
            'supported_pointing_hid_types': List[PointingHIDType],
            'supported_keyboard_hid_types': List[KeyboardHIDType],
            'supported_vfs_types': List[VFSType],
            'supported_import_options': List[ImportOptions],
            'supported_export_options': List[ExportOptions],
            'supported_recording_features': List[RecordingFeature],
            'supported_recording_audio_codecs': List[RecordingAudioCodec],
            'supported_recording_video_codecs': List[RecordingVideoCodec],
            'supported_recording_vs_modes': List[RecordingVideoScalingMode],
            'supported_recording_arc_modes': List[RecordingRateControlMode],
            'supported_recording_vrc_modes': List[RecordingRateControlMode],
            'supported_clone_options': List[CloneOptions],
            'supported_autostop_types': List[AutostopType],
            'supported_vm_proc_priorities': List[VMProcPriority],
            'supported_network_attachment_types': List[NetworkAttachmentType],
            'supported_port_modes': List[PortMode],
            'supported_audio_driver_types': List[AudioDriverType],
            'language_id': str
        }

        self.attribute_map = {
            'platform': 'platform',
            'min_guest_ram': 'minGuestRAM',
            'max_guest_ram': 'maxGuestRAM',
            'min_guest_vram': 'minGuestVRAM',
            'max_guest_vram': 'maxGuestVRAM',
            'min_guest_cpu_count': 'minGuestCPUCount',
            'max_guest_cpu_count': 'maxGuestCPUCount',
            'max_guest_monitors': 'maxGuestMonitors',
            'info_vd_size': 'infoVDSize',
            'default_machine_folder': 'defaultMachineFolder',
            'logging_level': 'loggingLevel',
            'medium_formats': 'mediumFormats',
            'default_hard_disk_format': 'defaultHardDiskFormat',
            'free_disk_space_warning': 'freeDiskSpaceWarning',
            'free_disk_space_percent_warning': 'freeDiskSpacePercentWarning',
            'free_disk_space_error': 'freeDiskSpaceError',
            'free_disk_space_percent_error': 'freeDiskSpacePercentError',
            'vrde_auth_library': 'VRDEAuthLibrary',
            'web_service_auth_library': 'webServiceAuthLibrary',
            'default_vrde_ext_pack': 'defaultVRDEExtPack',
            'default_crypto_ext_pack': 'defaultCryptoExtPack',
            'log_history_count': 'logHistoryCount',
            'default_audio_driver': 'defaultAudioDriver',
            'autostart_database_path': 'autostartDatabasePath',
            'default_additions_iso': 'defaultAdditionsISO',
            'default_frontend': 'defaultFrontend',
            'screen_shot_formats': 'screenShotFormats',
            'proxy_mode': 'proxyMode',
            'proxy_url': 'proxyURL',
            'supported_platform_architectures': 'supportedPlatformArchitectures',
            'supported_clipboard_modes': 'supportedClipboardModes',
            'supported_dn_d_modes': 'supportedDnDModes',
            'supported_pointing_hid_types': 'supportedPointingHIDTypes',
            'supported_keyboard_hid_types': 'supportedKeyboardHIDTypes',
            'supported_vfs_types': 'supportedVFSTypes',
            'supported_import_options': 'supportedImportOptions',
            'supported_export_options': 'supportedExportOptions',
            'supported_recording_features': 'supportedRecordingFeatures',
            'supported_recording_audio_codecs': 'supportedRecordingAudioCodecs',
            'supported_recording_video_codecs': 'supportedRecordingVideoCodecs',
            'supported_recording_vs_modes': 'supportedRecordingVSModes',
            'supported_recording_arc_modes': 'supportedRecordingARCModes',
            'supported_recording_vrc_modes': 'supportedRecordingVRCModes',
            'supported_clone_options': 'supportedCloneOptions',
            'supported_autostop_types': 'supportedAutostopTypes',
            'supported_vm_proc_priorities': 'supportedVMProcPriorities',
            'supported_network_attachment_types': 'supportedNetworkAttachmentTypes',
            'supported_port_modes': 'supportedPortModes',
            'supported_audio_driver_types': 'supportedAudioDriverTypes',
            'language_id': 'languageId'
        }

        self._platform = platform
        self._min_guest_ram = min_guest_ram
        self._max_guest_ram = max_guest_ram
        self._min_guest_vram = min_guest_vram
        self._max_guest_vram = max_guest_vram
        self._min_guest_cpu_count = min_guest_cpu_count
        self._max_guest_cpu_count = max_guest_cpu_count
        self._max_guest_monitors = max_guest_monitors
        self._info_vd_size = info_vd_size
        self._default_machine_folder = default_machine_folder
        self._logging_level = logging_level
        self._medium_formats = medium_formats
        self._default_hard_disk_format = default_hard_disk_format
        self._free_disk_space_warning = free_disk_space_warning
        self._free_disk_space_percent_warning = free_disk_space_percent_warning
        self._free_disk_space_error = free_disk_space_error
        self._free_disk_space_percent_error = free_disk_space_percent_error
        self._vrde_auth_library = vrde_auth_library
        self._web_service_auth_library = web_service_auth_library
        self._default_vrde_ext_pack = default_vrde_ext_pack
        self._default_crypto_ext_pack = default_crypto_ext_pack
        self._log_history_count = log_history_count
        self._default_audio_driver = default_audio_driver
        self._autostart_database_path = autostart_database_path
        self._default_additions_iso = default_additions_iso
        self._default_frontend = default_frontend
        self._screen_shot_formats = screen_shot_formats
        self._proxy_mode = proxy_mode
        self._proxy_url = proxy_url
        self._supported_platform_architectures = supported_platform_architectures
        self._supported_clipboard_modes = supported_clipboard_modes
        self._supported_dn_d_modes = supported_dn_d_modes
        self._supported_pointing_hid_types = supported_pointing_hid_types
        self._supported_keyboard_hid_types = supported_keyboard_hid_types
        self._supported_vfs_types = supported_vfs_types
        self._supported_import_options = supported_import_options
        self._supported_export_options = supported_export_options
        self._supported_recording_features = supported_recording_features
        self._supported_recording_audio_codecs = supported_recording_audio_codecs
        self._supported_recording_video_codecs = supported_recording_video_codecs
        self._supported_recording_vs_modes = supported_recording_vs_modes
        self._supported_recording_arc_modes = supported_recording_arc_modes
        self._supported_recording_vrc_modes = supported_recording_vrc_modes
        self._supported_clone_options = supported_clone_options
        self._supported_autostop_types = supported_autostop_types
        self._supported_vm_proc_priorities = supported_vm_proc_priorities
        self._supported_network_attachment_types = supported_network_attachment_types
        self._supported_port_modes = supported_port_modes
        self._supported_audio_driver_types = supported_audio_driver_types
        self._language_id = language_id

    @classmethod
    def from_dict(cls, dikt) -> 'SystemProperties':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SystemProperties of this SystemProperties.  # noqa: E501
        :rtype: SystemProperties
        """
        return util.deserialize_model(dikt, cls)

    @property
    def platform(self) -> PlatformProperties:
        """Gets the platform of this SystemProperties.


        :return: The platform of this SystemProperties.
        :rtype: PlatformProperties
        """
        return self._platform

    @platform.setter
    def platform(self, platform: PlatformProperties):
        """Sets the platform of this SystemProperties.


        :param platform: The platform of this SystemProperties.
        :type platform: PlatformProperties
        """

        self._platform = platform

    @property
    def min_guest_ram(self) -> int:
        """Gets the min_guest_ram of this SystemProperties.


        :return: The min_guest_ram of this SystemProperties.
        :rtype: int
        """
        return self._min_guest_ram

    @min_guest_ram.setter
    def min_guest_ram(self, min_guest_ram: int):
        """Sets the min_guest_ram of this SystemProperties.


        :param min_guest_ram: The min_guest_ram of this SystemProperties.
        :type min_guest_ram: int
        """

        self._min_guest_ram = min_guest_ram

    @property
    def max_guest_ram(self) -> int:
        """Gets the max_guest_ram of this SystemProperties.


        :return: The max_guest_ram of this SystemProperties.
        :rtype: int
        """
        return self._max_guest_ram

    @max_guest_ram.setter
    def max_guest_ram(self, max_guest_ram: int):
        """Sets the max_guest_ram of this SystemProperties.


        :param max_guest_ram: The max_guest_ram of this SystemProperties.
        :type max_guest_ram: int
        """

        self._max_guest_ram = max_guest_ram

    @property
    def min_guest_vram(self) -> int:
        """Gets the min_guest_vram of this SystemProperties.


        :return: The min_guest_vram of this SystemProperties.
        :rtype: int
        """
        return self._min_guest_vram

    @min_guest_vram.setter
    def min_guest_vram(self, min_guest_vram: int):
        """Sets the min_guest_vram of this SystemProperties.


        :param min_guest_vram: The min_guest_vram of this SystemProperties.
        :type min_guest_vram: int
        """

        self._min_guest_vram = min_guest_vram

    @property
    def max_guest_vram(self) -> int:
        """Gets the max_guest_vram of this SystemProperties.


        :return: The max_guest_vram of this SystemProperties.
        :rtype: int
        """
        return self._max_guest_vram

    @max_guest_vram.setter
    def max_guest_vram(self, max_guest_vram: int):
        """Sets the max_guest_vram of this SystemProperties.


        :param max_guest_vram: The max_guest_vram of this SystemProperties.
        :type max_guest_vram: int
        """

        self._max_guest_vram = max_guest_vram

    @property
    def min_guest_cpu_count(self) -> int:
        """Gets the min_guest_cpu_count of this SystemProperties.


        :return: The min_guest_cpu_count of this SystemProperties.
        :rtype: int
        """
        return self._min_guest_cpu_count

    @min_guest_cpu_count.setter
    def min_guest_cpu_count(self, min_guest_cpu_count: int):
        """Sets the min_guest_cpu_count of this SystemProperties.


        :param min_guest_cpu_count: The min_guest_cpu_count of this SystemProperties.
        :type min_guest_cpu_count: int
        """

        self._min_guest_cpu_count = min_guest_cpu_count

    @property
    def max_guest_cpu_count(self) -> int:
        """Gets the max_guest_cpu_count of this SystemProperties.


        :return: The max_guest_cpu_count of this SystemProperties.
        :rtype: int
        """
        return self._max_guest_cpu_count

    @max_guest_cpu_count.setter
    def max_guest_cpu_count(self, max_guest_cpu_count: int):
        """Sets the max_guest_cpu_count of this SystemProperties.


        :param max_guest_cpu_count: The max_guest_cpu_count of this SystemProperties.
        :type max_guest_cpu_count: int
        """

        self._max_guest_cpu_count = max_guest_cpu_count

    @property
    def max_guest_monitors(self) -> int:
        """Gets the max_guest_monitors of this SystemProperties.


        :return: The max_guest_monitors of this SystemProperties.
        :rtype: int
        """
        return self._max_guest_monitors

    @max_guest_monitors.setter
    def max_guest_monitors(self, max_guest_monitors: int):
        """Sets the max_guest_monitors of this SystemProperties.


        :param max_guest_monitors: The max_guest_monitors of this SystemProperties.
        :type max_guest_monitors: int
        """

        self._max_guest_monitors = max_guest_monitors

    @property
    def info_vd_size(self) -> int:
        """Gets the info_vd_size of this SystemProperties.


        :return: The info_vd_size of this SystemProperties.
        :rtype: int
        """
        return self._info_vd_size

    @info_vd_size.setter
    def info_vd_size(self, info_vd_size: int):
        """Sets the info_vd_size of this SystemProperties.


        :param info_vd_size: The info_vd_size of this SystemProperties.
        :type info_vd_size: int
        """

        self._info_vd_size = info_vd_size

    @property
    def default_machine_folder(self) -> str:
        """Gets the default_machine_folder of this SystemProperties.


        :return: The default_machine_folder of this SystemProperties.
        :rtype: str
        """
        return self._default_machine_folder

    @default_machine_folder.setter
    def default_machine_folder(self, default_machine_folder: str):
        """Sets the default_machine_folder of this SystemProperties.


        :param default_machine_folder: The default_machine_folder of this SystemProperties.
        :type default_machine_folder: str
        """

        self._default_machine_folder = default_machine_folder

    @property
    def logging_level(self) -> str:
        """Gets the logging_level of this SystemProperties.


        :return: The logging_level of this SystemProperties.
        :rtype: str
        """
        return self._logging_level

    @logging_level.setter
    def logging_level(self, logging_level: str):
        """Sets the logging_level of this SystemProperties.


        :param logging_level: The logging_level of this SystemProperties.
        :type logging_level: str
        """

        self._logging_level = logging_level

    @property
    def medium_formats(self) -> List[MediumFormat]:
        """Gets the medium_formats of this SystemProperties.


        :return: The medium_formats of this SystemProperties.
        :rtype: List[MediumFormat]
        """
        return self._medium_formats

    @medium_formats.setter
    def medium_formats(self, medium_formats: List[MediumFormat]):
        """Sets the medium_formats of this SystemProperties.


        :param medium_formats: The medium_formats of this SystemProperties.
        :type medium_formats: List[MediumFormat]
        """

        self._medium_formats = medium_formats

    @property
    def default_hard_disk_format(self) -> str:
        """Gets the default_hard_disk_format of this SystemProperties.


        :return: The default_hard_disk_format of this SystemProperties.
        :rtype: str
        """
        return self._default_hard_disk_format

    @default_hard_disk_format.setter
    def default_hard_disk_format(self, default_hard_disk_format: str):
        """Sets the default_hard_disk_format of this SystemProperties.


        :param default_hard_disk_format: The default_hard_disk_format of this SystemProperties.
        :type default_hard_disk_format: str
        """

        self._default_hard_disk_format = default_hard_disk_format

    @property
    def free_disk_space_warning(self) -> int:
        """Gets the free_disk_space_warning of this SystemProperties.


        :return: The free_disk_space_warning of this SystemProperties.
        :rtype: int
        """
        return self._free_disk_space_warning

    @free_disk_space_warning.setter
    def free_disk_space_warning(self, free_disk_space_warning: int):
        """Sets the free_disk_space_warning of this SystemProperties.


        :param free_disk_space_warning: The free_disk_space_warning of this SystemProperties.
        :type free_disk_space_warning: int
        """

        self._free_disk_space_warning = free_disk_space_warning

    @property
    def free_disk_space_percent_warning(self) -> int:
        """Gets the free_disk_space_percent_warning of this SystemProperties.


        :return: The free_disk_space_percent_warning of this SystemProperties.
        :rtype: int
        """
        return self._free_disk_space_percent_warning

    @free_disk_space_percent_warning.setter
    def free_disk_space_percent_warning(self, free_disk_space_percent_warning: int):
        """Sets the free_disk_space_percent_warning of this SystemProperties.


        :param free_disk_space_percent_warning: The free_disk_space_percent_warning of this SystemProperties.
        :type free_disk_space_percent_warning: int
        """

        self._free_disk_space_percent_warning = free_disk_space_percent_warning

    @property
    def free_disk_space_error(self) -> int:
        """Gets the free_disk_space_error of this SystemProperties.


        :return: The free_disk_space_error of this SystemProperties.
        :rtype: int
        """
        return self._free_disk_space_error

    @free_disk_space_error.setter
    def free_disk_space_error(self, free_disk_space_error: int):
        """Sets the free_disk_space_error of this SystemProperties.


        :param free_disk_space_error: The free_disk_space_error of this SystemProperties.
        :type free_disk_space_error: int
        """

        self._free_disk_space_error = free_disk_space_error

    @property
    def free_disk_space_percent_error(self) -> int:
        """Gets the free_disk_space_percent_error of this SystemProperties.


        :return: The free_disk_space_percent_error of this SystemProperties.
        :rtype: int
        """
        return self._free_disk_space_percent_error

    @free_disk_space_percent_error.setter
    def free_disk_space_percent_error(self, free_disk_space_percent_error: int):
        """Sets the free_disk_space_percent_error of this SystemProperties.


        :param free_disk_space_percent_error: The free_disk_space_percent_error of this SystemProperties.
        :type free_disk_space_percent_error: int
        """

        self._free_disk_space_percent_error = free_disk_space_percent_error

    @property
    def vrde_auth_library(self) -> str:
        """Gets the vrde_auth_library of this SystemProperties.


        :return: The vrde_auth_library of this SystemProperties.
        :rtype: str
        """
        return self._vrde_auth_library

    @vrde_auth_library.setter
    def vrde_auth_library(self, vrde_auth_library: str):
        """Sets the vrde_auth_library of this SystemProperties.


        :param vrde_auth_library: The vrde_auth_library of this SystemProperties.
        :type vrde_auth_library: str
        """

        self._vrde_auth_library = vrde_auth_library

    @property
    def web_service_auth_library(self) -> str:
        """Gets the web_service_auth_library of this SystemProperties.


        :return: The web_service_auth_library of this SystemProperties.
        :rtype: str
        """
        return self._web_service_auth_library

    @web_service_auth_library.setter
    def web_service_auth_library(self, web_service_auth_library: str):
        """Sets the web_service_auth_library of this SystemProperties.


        :param web_service_auth_library: The web_service_auth_library of this SystemProperties.
        :type web_service_auth_library: str
        """

        self._web_service_auth_library = web_service_auth_library

    @property
    def default_vrde_ext_pack(self) -> str:
        """Gets the default_vrde_ext_pack of this SystemProperties.


        :return: The default_vrde_ext_pack of this SystemProperties.
        :rtype: str
        """
        return self._default_vrde_ext_pack

    @default_vrde_ext_pack.setter
    def default_vrde_ext_pack(self, default_vrde_ext_pack: str):
        """Sets the default_vrde_ext_pack of this SystemProperties.


        :param default_vrde_ext_pack: The default_vrde_ext_pack of this SystemProperties.
        :type default_vrde_ext_pack: str
        """

        self._default_vrde_ext_pack = default_vrde_ext_pack

    @property
    def default_crypto_ext_pack(self) -> str:
        """Gets the default_crypto_ext_pack of this SystemProperties.


        :return: The default_crypto_ext_pack of this SystemProperties.
        :rtype: str
        """
        return self._default_crypto_ext_pack

    @default_crypto_ext_pack.setter
    def default_crypto_ext_pack(self, default_crypto_ext_pack: str):
        """Sets the default_crypto_ext_pack of this SystemProperties.


        :param default_crypto_ext_pack: The default_crypto_ext_pack of this SystemProperties.
        :type default_crypto_ext_pack: str
        """

        self._default_crypto_ext_pack = default_crypto_ext_pack

    @property
    def log_history_count(self) -> int:
        """Gets the log_history_count of this SystemProperties.


        :return: The log_history_count of this SystemProperties.
        :rtype: int
        """
        return self._log_history_count

    @log_history_count.setter
    def log_history_count(self, log_history_count: int):
        """Sets the log_history_count of this SystemProperties.


        :param log_history_count: The log_history_count of this SystemProperties.
        :type log_history_count: int
        """

        self._log_history_count = log_history_count

    @property
    def default_audio_driver(self) -> AudioDriverType:
        """Gets the default_audio_driver of this SystemProperties.


        :return: The default_audio_driver of this SystemProperties.
        :rtype: AudioDriverType
        """
        return self._default_audio_driver

    @default_audio_driver.setter
    def default_audio_driver(self, default_audio_driver: AudioDriverType):
        """Sets the default_audio_driver of this SystemProperties.


        :param default_audio_driver: The default_audio_driver of this SystemProperties.
        :type default_audio_driver: AudioDriverType
        """

        self._default_audio_driver = default_audio_driver

    @property
    def autostart_database_path(self) -> str:
        """Gets the autostart_database_path of this SystemProperties.


        :return: The autostart_database_path of this SystemProperties.
        :rtype: str
        """
        return self._autostart_database_path

    @autostart_database_path.setter
    def autostart_database_path(self, autostart_database_path: str):
        """Sets the autostart_database_path of this SystemProperties.


        :param autostart_database_path: The autostart_database_path of this SystemProperties.
        :type autostart_database_path: str
        """

        self._autostart_database_path = autostart_database_path

    @property
    def default_additions_iso(self) -> str:
        """Gets the default_additions_iso of this SystemProperties.


        :return: The default_additions_iso of this SystemProperties.
        :rtype: str
        """
        return self._default_additions_iso

    @default_additions_iso.setter
    def default_additions_iso(self, default_additions_iso: str):
        """Sets the default_additions_iso of this SystemProperties.


        :param default_additions_iso: The default_additions_iso of this SystemProperties.
        :type default_additions_iso: str
        """

        self._default_additions_iso = default_additions_iso

    @property
    def default_frontend(self) -> str:
        """Gets the default_frontend of this SystemProperties.


        :return: The default_frontend of this SystemProperties.
        :rtype: str
        """
        return self._default_frontend

    @default_frontend.setter
    def default_frontend(self, default_frontend: str):
        """Sets the default_frontend of this SystemProperties.


        :param default_frontend: The default_frontend of this SystemProperties.
        :type default_frontend: str
        """

        self._default_frontend = default_frontend

    @property
    def screen_shot_formats(self) -> List[BitmapFormat]:
        """Gets the screen_shot_formats of this SystemProperties.


        :return: The screen_shot_formats of this SystemProperties.
        :rtype: List[BitmapFormat]
        """
        return self._screen_shot_formats

    @screen_shot_formats.setter
    def screen_shot_formats(self, screen_shot_formats: List[BitmapFormat]):
        """Sets the screen_shot_formats of this SystemProperties.


        :param screen_shot_formats: The screen_shot_formats of this SystemProperties.
        :type screen_shot_formats: List[BitmapFormat]
        """

        self._screen_shot_formats = screen_shot_formats

    @property
    def proxy_mode(self) -> ProxyMode:
        """Gets the proxy_mode of this SystemProperties.


        :return: The proxy_mode of this SystemProperties.
        :rtype: ProxyMode
        """
        return self._proxy_mode

    @proxy_mode.setter
    def proxy_mode(self, proxy_mode: ProxyMode):
        """Sets the proxy_mode of this SystemProperties.


        :param proxy_mode: The proxy_mode of this SystemProperties.
        :type proxy_mode: ProxyMode
        """

        self._proxy_mode = proxy_mode

    @property
    def proxy_url(self) -> str:
        """Gets the proxy_url of this SystemProperties.


        :return: The proxy_url of this SystemProperties.
        :rtype: str
        """
        return self._proxy_url

    @proxy_url.setter
    def proxy_url(self, proxy_url: str):
        """Sets the proxy_url of this SystemProperties.


        :param proxy_url: The proxy_url of this SystemProperties.
        :type proxy_url: str
        """

        self._proxy_url = proxy_url

    @property
    def supported_platform_architectures(self) -> List[PlatformArchitecture]:
        """Gets the supported_platform_architectures of this SystemProperties.


        :return: The supported_platform_architectures of this SystemProperties.
        :rtype: List[PlatformArchitecture]
        """
        return self._supported_platform_architectures

    @supported_platform_architectures.setter
    def supported_platform_architectures(self, supported_platform_architectures: List[PlatformArchitecture]):
        """Sets the supported_platform_architectures of this SystemProperties.


        :param supported_platform_architectures: The supported_platform_architectures of this SystemProperties.
        :type supported_platform_architectures: List[PlatformArchitecture]
        """

        self._supported_platform_architectures = supported_platform_architectures

    @property
    def supported_clipboard_modes(self) -> List[ClipboardMode]:
        """Gets the supported_clipboard_modes of this SystemProperties.


        :return: The supported_clipboard_modes of this SystemProperties.
        :rtype: List[ClipboardMode]
        """
        return self._supported_clipboard_modes

    @supported_clipboard_modes.setter
    def supported_clipboard_modes(self, supported_clipboard_modes: List[ClipboardMode]):
        """Sets the supported_clipboard_modes of this SystemProperties.


        :param supported_clipboard_modes: The supported_clipboard_modes of this SystemProperties.
        :type supported_clipboard_modes: List[ClipboardMode]
        """

        self._supported_clipboard_modes = supported_clipboard_modes

    @property
    def supported_dn_d_modes(self) -> List[DnDMode]:
        """Gets the supported_dn_d_modes of this SystemProperties.


        :return: The supported_dn_d_modes of this SystemProperties.
        :rtype: List[DnDMode]
        """
        return self._supported_dn_d_modes

    @supported_dn_d_modes.setter
    def supported_dn_d_modes(self, supported_dn_d_modes: List[DnDMode]):
        """Sets the supported_dn_d_modes of this SystemProperties.


        :param supported_dn_d_modes: The supported_dn_d_modes of this SystemProperties.
        :type supported_dn_d_modes: List[DnDMode]
        """

        self._supported_dn_d_modes = supported_dn_d_modes

    @property
    def supported_pointing_hid_types(self) -> List[PointingHIDType]:
        """Gets the supported_pointing_hid_types of this SystemProperties.


        :return: The supported_pointing_hid_types of this SystemProperties.
        :rtype: List[PointingHIDType]
        """
        return self._supported_pointing_hid_types

    @supported_pointing_hid_types.setter
    def supported_pointing_hid_types(self, supported_pointing_hid_types: List[PointingHIDType]):
        """Sets the supported_pointing_hid_types of this SystemProperties.


        :param supported_pointing_hid_types: The supported_pointing_hid_types of this SystemProperties.
        :type supported_pointing_hid_types: List[PointingHIDType]
        """

        self._supported_pointing_hid_types = supported_pointing_hid_types

    @property
    def supported_keyboard_hid_types(self) -> List[KeyboardHIDType]:
        """Gets the supported_keyboard_hid_types of this SystemProperties.


        :return: The supported_keyboard_hid_types of this SystemProperties.
        :rtype: List[KeyboardHIDType]
        """
        return self._supported_keyboard_hid_types

    @supported_keyboard_hid_types.setter
    def supported_keyboard_hid_types(self, supported_keyboard_hid_types: List[KeyboardHIDType]):
        """Sets the supported_keyboard_hid_types of this SystemProperties.


        :param supported_keyboard_hid_types: The supported_keyboard_hid_types of this SystemProperties.
        :type supported_keyboard_hid_types: List[KeyboardHIDType]
        """

        self._supported_keyboard_hid_types = supported_keyboard_hid_types

    @property
    def supported_vfs_types(self) -> List[VFSType]:
        """Gets the supported_vfs_types of this SystemProperties.


        :return: The supported_vfs_types of this SystemProperties.
        :rtype: List[VFSType]
        """
        return self._supported_vfs_types

    @supported_vfs_types.setter
    def supported_vfs_types(self, supported_vfs_types: List[VFSType]):
        """Sets the supported_vfs_types of this SystemProperties.


        :param supported_vfs_types: The supported_vfs_types of this SystemProperties.
        :type supported_vfs_types: List[VFSType]
        """

        self._supported_vfs_types = supported_vfs_types

    @property
    def supported_import_options(self) -> List[ImportOptions]:
        """Gets the supported_import_options of this SystemProperties.


        :return: The supported_import_options of this SystemProperties.
        :rtype: List[ImportOptions]
        """
        return self._supported_import_options

    @supported_import_options.setter
    def supported_import_options(self, supported_import_options: List[ImportOptions]):
        """Sets the supported_import_options of this SystemProperties.


        :param supported_import_options: The supported_import_options of this SystemProperties.
        :type supported_import_options: List[ImportOptions]
        """

        self._supported_import_options = supported_import_options

    @property
    def supported_export_options(self) -> List[ExportOptions]:
        """Gets the supported_export_options of this SystemProperties.


        :return: The supported_export_options of this SystemProperties.
        :rtype: List[ExportOptions]
        """
        return self._supported_export_options

    @supported_export_options.setter
    def supported_export_options(self, supported_export_options: List[ExportOptions]):
        """Sets the supported_export_options of this SystemProperties.


        :param supported_export_options: The supported_export_options of this SystemProperties.
        :type supported_export_options: List[ExportOptions]
        """

        self._supported_export_options = supported_export_options

    @property
    def supported_recording_features(self) -> List[RecordingFeature]:
        """Gets the supported_recording_features of this SystemProperties.


        :return: The supported_recording_features of this SystemProperties.
        :rtype: List[RecordingFeature]
        """
        return self._supported_recording_features

    @supported_recording_features.setter
    def supported_recording_features(self, supported_recording_features: List[RecordingFeature]):
        """Sets the supported_recording_features of this SystemProperties.


        :param supported_recording_features: The supported_recording_features of this SystemProperties.
        :type supported_recording_features: List[RecordingFeature]
        """

        self._supported_recording_features = supported_recording_features

    @property
    def supported_recording_audio_codecs(self) -> List[RecordingAudioCodec]:
        """Gets the supported_recording_audio_codecs of this SystemProperties.


        :return: The supported_recording_audio_codecs of this SystemProperties.
        :rtype: List[RecordingAudioCodec]
        """
        return self._supported_recording_audio_codecs

    @supported_recording_audio_codecs.setter
    def supported_recording_audio_codecs(self, supported_recording_audio_codecs: List[RecordingAudioCodec]):
        """Sets the supported_recording_audio_codecs of this SystemProperties.


        :param supported_recording_audio_codecs: The supported_recording_audio_codecs of this SystemProperties.
        :type supported_recording_audio_codecs: List[RecordingAudioCodec]
        """

        self._supported_recording_audio_codecs = supported_recording_audio_codecs

    @property
    def supported_recording_video_codecs(self) -> List[RecordingVideoCodec]:
        """Gets the supported_recording_video_codecs of this SystemProperties.


        :return: The supported_recording_video_codecs of this SystemProperties.
        :rtype: List[RecordingVideoCodec]
        """
        return self._supported_recording_video_codecs

    @supported_recording_video_codecs.setter
    def supported_recording_video_codecs(self, supported_recording_video_codecs: List[RecordingVideoCodec]):
        """Sets the supported_recording_video_codecs of this SystemProperties.


        :param supported_recording_video_codecs: The supported_recording_video_codecs of this SystemProperties.
        :type supported_recording_video_codecs: List[RecordingVideoCodec]
        """

        self._supported_recording_video_codecs = supported_recording_video_codecs

    @property
    def supported_recording_vs_modes(self) -> List[RecordingVideoScalingMode]:
        """Gets the supported_recording_vs_modes of this SystemProperties.


        :return: The supported_recording_vs_modes of this SystemProperties.
        :rtype: List[RecordingVideoScalingMode]
        """
        return self._supported_recording_vs_modes

    @supported_recording_vs_modes.setter
    def supported_recording_vs_modes(self, supported_recording_vs_modes: List[RecordingVideoScalingMode]):
        """Sets the supported_recording_vs_modes of this SystemProperties.


        :param supported_recording_vs_modes: The supported_recording_vs_modes of this SystemProperties.
        :type supported_recording_vs_modes: List[RecordingVideoScalingMode]
        """

        self._supported_recording_vs_modes = supported_recording_vs_modes

    @property
    def supported_recording_arc_modes(self) -> List[RecordingRateControlMode]:
        """Gets the supported_recording_arc_modes of this SystemProperties.


        :return: The supported_recording_arc_modes of this SystemProperties.
        :rtype: List[RecordingRateControlMode]
        """
        return self._supported_recording_arc_modes

    @supported_recording_arc_modes.setter
    def supported_recording_arc_modes(self, supported_recording_arc_modes: List[RecordingRateControlMode]):
        """Sets the supported_recording_arc_modes of this SystemProperties.


        :param supported_recording_arc_modes: The supported_recording_arc_modes of this SystemProperties.
        :type supported_recording_arc_modes: List[RecordingRateControlMode]
        """

        self._supported_recording_arc_modes = supported_recording_arc_modes

    @property
    def supported_recording_vrc_modes(self) -> List[RecordingRateControlMode]:
        """Gets the supported_recording_vrc_modes of this SystemProperties.


        :return: The supported_recording_vrc_modes of this SystemProperties.
        :rtype: List[RecordingRateControlMode]
        """
        return self._supported_recording_vrc_modes

    @supported_recording_vrc_modes.setter
    def supported_recording_vrc_modes(self, supported_recording_vrc_modes: List[RecordingRateControlMode]):
        """Sets the supported_recording_vrc_modes of this SystemProperties.


        :param supported_recording_vrc_modes: The supported_recording_vrc_modes of this SystemProperties.
        :type supported_recording_vrc_modes: List[RecordingRateControlMode]
        """

        self._supported_recording_vrc_modes = supported_recording_vrc_modes

    @property
    def supported_clone_options(self) -> List[CloneOptions]:
        """Gets the supported_clone_options of this SystemProperties.


        :return: The supported_clone_options of this SystemProperties.
        :rtype: List[CloneOptions]
        """
        return self._supported_clone_options

    @supported_clone_options.setter
    def supported_clone_options(self, supported_clone_options: List[CloneOptions]):
        """Sets the supported_clone_options of this SystemProperties.


        :param supported_clone_options: The supported_clone_options of this SystemProperties.
        :type supported_clone_options: List[CloneOptions]
        """

        self._supported_clone_options = supported_clone_options

    @property
    def supported_autostop_types(self) -> List[AutostopType]:
        """Gets the supported_autostop_types of this SystemProperties.


        :return: The supported_autostop_types of this SystemProperties.
        :rtype: List[AutostopType]
        """
        return self._supported_autostop_types

    @supported_autostop_types.setter
    def supported_autostop_types(self, supported_autostop_types: List[AutostopType]):
        """Sets the supported_autostop_types of this SystemProperties.


        :param supported_autostop_types: The supported_autostop_types of this SystemProperties.
        :type supported_autostop_types: List[AutostopType]
        """

        self._supported_autostop_types = supported_autostop_types

    @property
    def supported_vm_proc_priorities(self) -> List[VMProcPriority]:
        """Gets the supported_vm_proc_priorities of this SystemProperties.


        :return: The supported_vm_proc_priorities of this SystemProperties.
        :rtype: List[VMProcPriority]
        """
        return self._supported_vm_proc_priorities

    @supported_vm_proc_priorities.setter
    def supported_vm_proc_priorities(self, supported_vm_proc_priorities: List[VMProcPriority]):
        """Sets the supported_vm_proc_priorities of this SystemProperties.


        :param supported_vm_proc_priorities: The supported_vm_proc_priorities of this SystemProperties.
        :type supported_vm_proc_priorities: List[VMProcPriority]
        """

        self._supported_vm_proc_priorities = supported_vm_proc_priorities

    @property
    def supported_network_attachment_types(self) -> List[NetworkAttachmentType]:
        """Gets the supported_network_attachment_types of this SystemProperties.


        :return: The supported_network_attachment_types of this SystemProperties.
        :rtype: List[NetworkAttachmentType]
        """
        return self._supported_network_attachment_types

    @supported_network_attachment_types.setter
    def supported_network_attachment_types(self, supported_network_attachment_types: List[NetworkAttachmentType]):
        """Sets the supported_network_attachment_types of this SystemProperties.


        :param supported_network_attachment_types: The supported_network_attachment_types of this SystemProperties.
        :type supported_network_attachment_types: List[NetworkAttachmentType]
        """

        self._supported_network_attachment_types = supported_network_attachment_types

    @property
    def supported_port_modes(self) -> List[PortMode]:
        """Gets the supported_port_modes of this SystemProperties.


        :return: The supported_port_modes of this SystemProperties.
        :rtype: List[PortMode]
        """
        return self._supported_port_modes

    @supported_port_modes.setter
    def supported_port_modes(self, supported_port_modes: List[PortMode]):
        """Sets the supported_port_modes of this SystemProperties.


        :param supported_port_modes: The supported_port_modes of this SystemProperties.
        :type supported_port_modes: List[PortMode]
        """

        self._supported_port_modes = supported_port_modes

    @property
    def supported_audio_driver_types(self) -> List[AudioDriverType]:
        """Gets the supported_audio_driver_types of this SystemProperties.


        :return: The supported_audio_driver_types of this SystemProperties.
        :rtype: List[AudioDriverType]
        """
        return self._supported_audio_driver_types

    @supported_audio_driver_types.setter
    def supported_audio_driver_types(self, supported_audio_driver_types: List[AudioDriverType]):
        """Sets the supported_audio_driver_types of this SystemProperties.


        :param supported_audio_driver_types: The supported_audio_driver_types of this SystemProperties.
        :type supported_audio_driver_types: List[AudioDriverType]
        """

        self._supported_audio_driver_types = supported_audio_driver_types

    @property
    def language_id(self) -> str:
        """Gets the language_id of this SystemProperties.


        :return: The language_id of this SystemProperties.
        :rtype: str
        """
        return self._language_id

    @language_id.setter
    def language_id(self, language_id: str):
        """Sets the language_id of this SystemProperties.


        :param language_id: The language_id of this SystemProperties.
        :type language_id: str
        """

        self._language_id = language_id
