# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401


from vbox_server.models.base_model_ import Model
from vbox_server.models.unattended import Unattended
from vbox_server import util


class UnattendedResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, unattended: Unattended=None):  # noqa: E501
        """UnattendedResponse - a model defined in Swagger

        :param unattended: The unattended of this UnattendedResponse.  # noqa: E501
        :type unattended: Unattended
        """
        self.swagger_types = {
            'unattended': Unattended
        }

        self.attribute_map = {
            'unattended': 'unattended'
        }

        self._unattended = unattended

    @classmethod
    def from_dict(cls, dikt) -> 'UnattendedResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Unattended_response of this UnattendedResponse.  # noqa: E501
        :rtype: UnattendedResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def unattended(self) -> Unattended:
        """Gets the unattended of this UnattendedResponse.


        :return: The unattended of this UnattendedResponse.
        :rtype: Unattended
        """
        return self._unattended

    @unattended.setter
    def unattended(self, unattended: Unattended):
        """Sets the unattended of this UnattendedResponse.


        :param unattended: The unattended of this UnattendedResponse.
        :type unattended: Unattended
        """

        self._unattended = unattended
