# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401


from vbox_server.models.base_model_ import Model
from vbox_server.models.usb_device import USBDevice
from vbox_server import util


class USBDeviceResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, device: USBDevice=None):  # noqa: E501
        """USBDeviceResponse - a model defined in Swagger

        :param device: The device of this USBDeviceResponse.  # noqa: E501
        :type device: USBDevice
        """
        self.swagger_types = {
            'device': USBDevice
        }

        self.attribute_map = {
            'device': 'device'
        }

        self._device = device

    @classmethod
    def from_dict(cls, dikt) -> 'USBDeviceResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The USBDevice_response of this USBDeviceResponse.  # noqa: E501
        :rtype: USBDeviceResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def device(self) -> USBDevice:
        """Gets the device of this USBDeviceResponse.


        :return: The device of this USBDeviceResponse.
        :rtype: USBDevice
        """
        return self._device

    @device.setter
    def device(self, device: USBDevice):
        """Sets the device of this USBDeviceResponse.


        :param device: The device of this USBDeviceResponse.
        :type device: USBDevice
        """

        self._device = device
