# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401


from vbox_server.models.base_model_ import Model
from vbox_server import util

# The special variant of the class VirtualBoxErrorInfo.
# This class has a reference to itself inside. In this case all references must be wrapped by ''
# like "def from_dict(cls, dikt) -> 'VirtualBoxErrorInfo'".
# Otherwise the error "NameError: name 'VirtualBoxErrorInfo' is not defined" occurs.
# See https://github.com/python/mypy/issues/3661
# Swagger can't generate the proper form of class (with quotes '' around the references).
# That's why this file with the class VirtualBoxErrorInfo was invented.
# Just replace the original file (generated by Swagger) with this one.
class VirtualBoxErrorInfo(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, result_code: int=None, result_detail: int=None, interface_id: str=None, component: str=None, text: str=None, next: 'VirtualBoxErrorInfo'=None):  # noqa: E501
        """VirtualBoxErrorInfo - a model defined in Swagger

        :param result_code: The result_code of this VirtualBoxErrorInfo.  # noqa: E501
        :type result_code: int
        :param result_detail: The result_detail of this VirtualBoxErrorInfo.  # noqa: E501
        :type result_detail: int
        :param interface_id: The interface_id of this VirtualBoxErrorInfo.  # noqa: E501
        :type interface_id: str
        :param component: The component of this VirtualBoxErrorInfo.  # noqa: E501
        :type component: str
        :param text: The text of this VirtualBoxErrorInfo.  # noqa: E501
        :type text: str
        :param next: The next of this VirtualBoxErrorInfo.  # noqa: E501
        :type next: VirtualBoxErrorInfo
        """
        self.swagger_types = {
            'result_code': int,
            'result_detail': int,
            'interface_id': str,
            'component': str,
            'text': str,
            'next': VirtualBoxErrorInfo
        }

        self.attribute_map = {
            'result_code': 'resultCode',
            'result_detail': 'resultDetail',
            'interface_id': 'interfaceID',
            'component': 'component',
            'text': 'text',
            'next': 'next'
        }

        self._result_code = result_code
        self._result_detail = result_detail
        self._interface_id = interface_id
        self._component = component
        self._text = text
        self._next = next

    @classmethod
    def from_dict(cls, dikt) -> 'VirtualBoxErrorInfo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The VirtualBoxErrorInfo of this VirtualBoxErrorInfo.  # noqa: E501
        :rtype: VirtualBoxErrorInfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def result_code(self) -> int:
        """Gets the result_code of this VirtualBoxErrorInfo.


        :return: The result_code of this VirtualBoxErrorInfo.
        :rtype: int
        """
        return self._result_code

    @result_code.setter
    def result_code(self, result_code: int):
        """Sets the result_code of this VirtualBoxErrorInfo.


        :param result_code: The result_code of this VirtualBoxErrorInfo.
        :type result_code: int
        """

        self._result_code = result_code

    @property
    def result_detail(self) -> int:
        """Gets the result_detail of this VirtualBoxErrorInfo.


        :return: The result_detail of this VirtualBoxErrorInfo.
        :rtype: int
        """
        return self._result_detail

    @result_detail.setter
    def result_detail(self, result_detail: int):
        """Sets the result_detail of this VirtualBoxErrorInfo.


        :param result_detail: The result_detail of this VirtualBoxErrorInfo.
        :type result_detail: int
        """

        self._result_detail = result_detail

    @property
    def interface_id(self) -> str:
        """Gets the interface_id of this VirtualBoxErrorInfo.


        :return: The interface_id of this VirtualBoxErrorInfo.
        :rtype: str
        """
        return self._interface_id

    @interface_id.setter
    def interface_id(self, interface_id: str):
        """Sets the interface_id of this VirtualBoxErrorInfo.


        :param interface_id: The interface_id of this VirtualBoxErrorInfo.
        :type interface_id: str
        """

        self._interface_id = interface_id

    @property
    def component(self) -> str:
        """Gets the component of this VirtualBoxErrorInfo.


        :return: The component of this VirtualBoxErrorInfo.
        :rtype: str
        """
        return self._component

    @component.setter
    def component(self, component: str):
        """Sets the component of this VirtualBoxErrorInfo.


        :param component: The component of this VirtualBoxErrorInfo.
        :type component: str
        """

        self._component = component

    @property
    def text(self) -> str:
        """Gets the text of this VirtualBoxErrorInfo.


        :return: The text of this VirtualBoxErrorInfo.
        :rtype: str
        """
        return self._text

    @text.setter
    def text(self, text: str):
        """Sets the text of this VirtualBoxErrorInfo.


        :param text: The text of this VirtualBoxErrorInfo.
        :type text: str
        """

        self._text = text

    @property
    def next(self) -> 'VirtualBoxErrorInfo':
        """Gets the next of this VirtualBoxErrorInfo.


        :return: The next of this VirtualBoxErrorInfo.
        :rtype: VirtualBoxErrorInfo
        """
        return self._next

    @next.setter
    def next(self, next: 'VirtualBoxErrorInfo'):
        """Sets the next of this VirtualBoxErrorInfo.


        :param next: The next of this VirtualBoxErrorInfo.
        :type next: VirtualBoxErrorInfo
        """

        self._next = next
