# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401


from vbox_server.models.base_model_ import Model
from vbox_server.models.access_mode import AccessMode
from vbox_server.models.device_type import DeviceType
from vbox_server import util


class VirtualBoxCreateMediumRequestBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, format: str=None, location: str=None, access_mode: AccessMode=None, a_device_type_type: DeviceType=None):  # noqa: E501
        """VirtualBoxCreateMediumRequestBody - a model defined in Swagger

        :param format: The format of this VirtualBoxCreateMediumRequestBody.  # noqa: E501
        :type format: str
        :param location: The location of this VirtualBoxCreateMediumRequestBody.  # noqa: E501
        :type location: str
        :param access_mode: The access_mode of this VirtualBoxCreateMediumRequestBody.  # noqa: E501
        :type access_mode: AccessMode
        :param a_device_type_type: The a_device_type_type of this VirtualBoxCreateMediumRequestBody.  # noqa: E501
        :type a_device_type_type: DeviceType
        """
        self.swagger_types = {
            'format': str,
            'location': str,
            'access_mode': AccessMode,
            'a_device_type_type': DeviceType
        }

        self.attribute_map = {
            'format': 'format',
            'location': 'location',
            'access_mode': 'accessMode',
            'a_device_type_type': 'aDeviceTypeType'
        }

        self._format = format
        self._location = location
        self._access_mode = access_mode
        self._a_device_type_type = a_device_type_type

    @classmethod
    def from_dict(cls, dikt) -> 'VirtualBoxCreateMediumRequestBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The VirtualBoxCreateMediumRequestBody of this VirtualBoxCreateMediumRequestBody.  # noqa: E501
        :rtype: VirtualBoxCreateMediumRequestBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def format(self) -> str:
        """Gets the format of this VirtualBoxCreateMediumRequestBody.


        :return: The format of this VirtualBoxCreateMediumRequestBody.
        :rtype: str
        """
        return self._format

    @format.setter
    def format(self, format: str):
        """Sets the format of this VirtualBoxCreateMediumRequestBody.


        :param format: The format of this VirtualBoxCreateMediumRequestBody.
        :type format: str
        """

        self._format = format

    @property
    def location(self) -> str:
        """Gets the location of this VirtualBoxCreateMediumRequestBody.


        :return: The location of this VirtualBoxCreateMediumRequestBody.
        :rtype: str
        """
        return self._location

    @location.setter
    def location(self, location: str):
        """Sets the location of this VirtualBoxCreateMediumRequestBody.


        :param location: The location of this VirtualBoxCreateMediumRequestBody.
        :type location: str
        """

        self._location = location

    @property
    def access_mode(self) -> AccessMode:
        """Gets the access_mode of this VirtualBoxCreateMediumRequestBody.


        :return: The access_mode of this VirtualBoxCreateMediumRequestBody.
        :rtype: AccessMode
        """
        return self._access_mode

    @access_mode.setter
    def access_mode(self, access_mode: AccessMode):
        """Sets the access_mode of this VirtualBoxCreateMediumRequestBody.


        :param access_mode: The access_mode of this VirtualBoxCreateMediumRequestBody.
        :type access_mode: AccessMode
        """

        self._access_mode = access_mode

    @property
    def a_device_type_type(self) -> DeviceType:
        """Gets the a_device_type_type of this VirtualBoxCreateMediumRequestBody.


        :return: The a_device_type_type of this VirtualBoxCreateMediumRequestBody.
        :rtype: DeviceType
        """
        return self._a_device_type_type

    @a_device_type_type.setter
    def a_device_type_type(self, a_device_type_type: DeviceType):
        """Sets the a_device_type_type of this VirtualBoxCreateMediumRequestBody.


        :param a_device_type_type: The a_device_type_type of this VirtualBoxCreateMediumRequestBody.
        :type a_device_type_type: DeviceType
        """

        self._a_device_type_type = a_device_type_type
