# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401


from vbox_server.models.base_model_ import Model
from vbox_server import util


class VirtualboxGetextradatakeysResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, keys: List[str]=None):  # noqa: E501
        """VirtualboxGetextradatakeysResponse - a model defined in Swagger

        :param keys: The keys of this VirtualboxGetextradatakeysResponse.  # noqa: E501
        :type keys: List[str]
        """
        self.swagger_types = {
            'keys': List[str]
        }

        self.attribute_map = {
            'keys': 'keys'
        }

        self._keys = keys

    @classmethod
    def from_dict(cls, dikt) -> 'VirtualboxGetextradatakeysResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The virtualbox_getextradatakeys_response of this VirtualboxGetextradatakeysResponse.  # noqa: E501
        :rtype: VirtualboxGetextradatakeysResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def keys(self) -> List[str]:
        """Gets the keys of this VirtualboxGetextradatakeysResponse.


        :return: The keys of this VirtualboxGetextradatakeysResponse.
        :rtype: List[str]
        """
        return self._keys

    @keys.setter
    def keys(self, keys: List[str]):
        """Sets the keys of this VirtualboxGetextradatakeysResponse.


        :param keys: The keys of this VirtualboxGetextradatakeysResponse.
        :type keys: List[str]
        """

        self._keys = keys
