# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401


from vbox_server.models.base_model_ import Model
from vbox_server.models.virtual_box import VirtualBox
from vbox_server import util


class VirtualBoxResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, server: VirtualBox=None):  # noqa: E501
        """VirtualBoxResponse - a model defined in Swagger

        :param server: The server of this VirtualBoxResponse.  # noqa: E501
        :type server: VirtualBox
        """
        self.swagger_types = {
            'server': VirtualBox
        }

        self.attribute_map = {
            'server': 'server'
        }

        self._server = server

    @classmethod
    def from_dict(cls, dikt) -> 'VirtualBoxResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The VirtualBox_response of this VirtualBoxResponse.  # noqa: E501
        :rtype: VirtualBoxResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def server(self) -> VirtualBox:
        """Gets the server of this VirtualBoxResponse.


        :return: The server of this VirtualBoxResponse.
        :rtype: VirtualBox
        """
        return self._server

    @server.setter
    def server(self, server: VirtualBox):
        """Sets the server of this VirtualBoxResponse.


        :param server: The server of this VirtualBoxResponse.
        :type server: VirtualBox
        """

        self._server = server
